### ISSUE TITLE
Sponge limits the function of Botania sparks.

### ISSUE THREAD

**Issue by atakle** [SpongePowered/SpongeForge#1000]
Sponge seems to impose a limit on the number of sparks that can be connected to each other.

The image below shows a simple mana pool setup. The spark in the lower left corner has a recessive augment, and the spark on the opposite side has a dominant augment.
![nosponge](https://cloud.githubusercontent.com/assets/6999276/19829616/cfbb6b56-9de6-11e6-9ef7-59f039c97422.png)

The second image shows the same setup, but with Sponge installed. As you can see, several sparks are ignored entirely.
![sponge](https://cloud.githubusercontent.com/assets/6999276/19829617/d3f5a5ce-9de6-11e6-90a0-bdde6b2e275f.png)

**Comment by Aaron1011** [comment]
@atakle: Can you describe how i would replicate this setup on a fresh world?

**Comment by atakle** [comment]
Place down the mana pools and place a spark on each of them. Right click one spark with a "Spark augment: Dominant" and the opposite one with a "Spark augment: Recessive". To start the mana transfer, drop a creative mana tablet into the pool with the recessive spark.

**Comment by NyleGarcia** [comment]
Can confirm this with sponge only having the same issue

**Comment by Aaron1011** [comment]
@atakle @Bebabo10: The issue was due to Sponge's collision configuration system. By default, Sponge only allows a block or entity to collide with 8 other entities at a time (it limits how many results are returned from `getEntitiesWithinAABB`). However, Sparks need all collisions within the AABB to function, so I've added a default config setting which disables collision limiting for Sparks.

You'll notice that right-clicking a Spark with a Wand of the Forest still won't show the proper number of collisions. We're working on a fix for this, but it won't affect the actual operation of the Sparks/Mana Pools.

**Comment by atakle** [comment]
Thank you. However, this issue also affects Corporea sparks, which use a different entity ID. It can be fixed the same way, by adding "botaniacorporeaspark" to the config. I believe Master Corporea Sparks use the same ID as normal Corporea Sparks, so they don't need special treatment.
