### ISSUE TITLE
CommandBlock requires OP to modify

### ISSUE THREAD

**Issue by xf57212** [SpongePowered/SpongeForge#1010]
I was told in https://github.com/PEXPlugins/PermissionsEx/issues/2572 that this is an issue in Sponge.

Apparently sponge doesn't support /op when a permissions plugin is installed and that nothing in sponge should look at the ops list. However this is not the case.

When right clicking a command block, the ops list is checked. EssentialsCmds seems to also be checking for OP as it sets my name prefix to red when I manually added myself to the ops.json file.

Either support the /op command and add a feature to check op in the API or fix the command block so it can be used without op, but only by people with some permission node (note vanilla mc does not have a permission node for this already like they do for other mc commands. they REQUIRE the person to be op)

http://minecraft.gamepedia.com/Command_Block#Modification

Also if op is not going to be supported, https://docs.spongepowered.org/master/en/server/management/permissions.html should be modified since it indicates op is supported and can be checked by mods and plugins.

**Comment by Aaron1011** [comment]
Sponge adds the permission `minecraft.commandblock` - try granting yourself that.

**Comment by ryantheleach** [comment]
Also to clarify "op not being supported" The reason why it's not supported, is anything on the plugin side / game side of things should be querying for permissions, this allows you to separate out the different roles and responsibility. 

/op still works. It is just interpreted by the permissions service however it wants, in the base game with only the default permissions service it should be granting the permissions needed, the permissions service is even free to ignore it completely.

Example: Pex overrides the /op command in order to discourage it's use, but using /minecraft:op instead still allows you to grant yourself all permissions. It's just not recommended because some plugins assume that you won't have all the permissions because they asked you to configure them differently.

**Comment by ghost** [comment]
use /minecraft:op playername
