### ISSUE TITLE
Forge permissions API

### ISSUE THREAD

**Issue by Xfel** [SpongePowered/SpongeForge#1049]
Now that MinecraftForge provides a permissions API (https://github.com/MinecraftForge/MinecraftForge/pull/3155), SpongeForge should integrate with it, allowing us to query permissions from the mod's side.

**Comment by ST-DDT** [comment]
I'm not sure what you are requesting. 
- Do you want SpongeForge to provide an implementation of the ForgePermission API 
- or do you want SpongeForge to default to Forge's Permission API 
- or both?

What happens if both Forge and Sponge provide a permission plugin?

There are also some fundamental differences between both concepts.
AFAICT there is no "OP" flag in Sponge, but it is used in Forge.

**Comment by Xfel** [comment]
The basic permission check should be interoperable. As far as I can see, it would be pretty difficult to implement the sponge permissions api on top of the forge one, as the sponge api provides a lot more features. 

The other way round seems possible though. The only problem here is forge's DefaultPermissionLevel using the OP concept, which needs to be mapped to those default roles in some way.

**Comment by Xfel** [comment]
I don't think this is related to commands specifically, the API is meant to be used by mods in general.

**Comment by yuuka-miya** [comment]
Hi @ST-DDT and @zml2008 - 

I know this is fairly late (dropped out of the modding scene for quite a while), but I was one of those who helped @LatvianModder design the Forge permissions API. Just came across this issue, so I thought I'd share my thoughts on the matter.

My ideas for SpongeForge was that it provide a single **non-replaceable** implementation of the Forge permissions API, that delegates to Sponge's own permission service. This has the side effect of making SpongeForge automatically incompatible with other Forge-based permission providers, however I personally think that access to the more powerful Sponge permission system is worth the tradeoff in this case.

That way, both Forge mods and Sponge plugins get to be first-class citizens in a multiplayer server world, since now not only can Forge mods be permission aware, they can also take advantage of more powerful Sponge-based permission systems.

**Comment by me4502** [comment]
I disagree with having it non overridable. If that were to be done, it'd make sense to have an option to disable it and a warning in the console if another forge permission mod is found.

**Comment by maxanier** [comment]
+1 would love to register and check Sponge compatible permissions from within my Forge mod.

**Comment by LatvianModder** [comment]
@me4502 the Forge itself already displays warning when a permission handler is replaced with another

**Comment by Zidane** [comment]
@kashike 

Status?

**Comment by kashike** [comment]
I'll get this done tonight most likely.

**Comment by kashike** [comment]
I'll get this done tonight most likely.

**Comment by Zidane** [comment]
Closing as we have an open PR for this and discussion should continue there.

We could use some help in wrapping up that PR and finally get this merged.

https://github.com/SpongePowered/SpongeForge/pull/1660
