### ISSUE TITLE
Making mods compatible with SpongeForge?

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1065]
So I know there is the running issue with some mods (such as EXU2 and AE2) where they instantiate forge classes and that somehow stops sponge from making transformations and crashes everything. I'm trying to setup a server with some of these mods and I'd just like to know what exactly it is that's causing this issue so I can go in and hopefully patch the mods to run on my server. I have working knowledge of Java and everything, I'd just like someone to articulate what exactly the problem is and/or how it needs to be fixed. Also, I'm curious as to why some mod authors refuse to fix the issue. I saw on the issue for AE2, someone mentioned they submitted a pull request but the developers refused to accept it? Why might this be?

**Comment by JBYoshi** [comment]
That happens only when a coremod loads Minecraft classes before all of the coremods are fully set up. If you don't use core mods (`IFMLLoadingPlugin`), you should be perfectly fine.

**Comment by gabizou** [comment]
Basically, to understand what is going on, it's best to read the [Mixin wiki](https://github.com/SpongePowered/Mixin/wiki/Introduction-to-Mixins---Understanding-Mixin-Architecture) and then once you understand how class transformation works, understand that there's an order of how core-mods are loaded at runtime that certain core-mods (such as AE2) are class loading classes before Sponge is instantiated and applies it's transformers. This is where Sponge has issue with these mods, as we are attempting to transform certain classes, but we can't because they are already class loaded.

**Comment by cj89898** [comment]
So I was about to post my issue, but saw this one. So does anybody know if AE2 will be made compatible? I know that the new group that took it over are very active.

**Comment by bloodmc** [comment]
Please avoid creating tickets for non-game issues. Use the forums for questions like this.

https://forums.spongepowered.org/latest
