### ISSUE TITLE
Infinitely flying Wither Skulls

### ISSUE THREAD

**Issue by inklit** [SpongePowered/SpongeForge#1093]
As you can see by this picture....
[http://i.imgur.com/ShNy8u7.png](url)...
a Wither Skull is flying infinitely through my world. Wither Skulls appear to not despawn until they hit something.
They should have a maximum lifetime and then despawn automatically after they reach it.

SpongeForge version 1.10.2 1971

**Comment by Aaron1011** [comment]
I'm fairly certain that this is a Vanilla issue.

**Comment by phit** [comment]
briefly looked over the vanilla source and also couldn't find any confirmation that they despawn in vanilla, so considering this a feature request

**Comment by gabizou** [comment]
Closing this issue, as of today 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please [open a new issue](https://github.com/SpongePowered/SpongeForge/issues/new) with updated information.
