### ISSUE TITLE
Disconnections during structure saves (feature request)

### ISSUE THREAD

**Issue by Dysthymic** [SpongePowered/SpongeForge#1113]
There is a known issue with structure data saving causing immense issues on the recent updates of Sponge. 
I along with several other large server owners have recently experienced frequent mass disconnections during world saves. Essentially what is happening is structures in the /world/data folder are not saving properly either due to lag caused by mods or potentially other various issues. However upon renaming or deleting that folder- the issues go away completely for at least 24 to 72 hours until they arise up again. Spigot and Cauldron both had a feature to disable the saving function of this folder as it is known to cause issues such as this in large map packs and resource heavy servers.

https://www.spigotmc.org/wiki/disabling-structure-saving/

I believe this would help with performance during saves tremendously given the drawbacks of some things not spawning. (this would be an optional configuration for those to opt-in). Large mods such as Pixelmon, witches and the like spawning is not needed therefore a feature to disable to disable structured saves would be a tremendous help and solve these issues many of us are experiencing.

**Comment by Rasgnarok** [comment]
Mapping in the /data folder of a world was causing that, upon timed saves, the players would disconnect on `Gathering id map for writing to world save [world name]` - normally 10 to 25ish players for me.

This was caused by a rushed update to a latest Sponge (at the time, `1.10.2-2171-5.1.0-BETA-1971`). Ever since then, the disconnects were happening no matter the plugins that were added or removed, and the Forge/Sponge versions tried. As OP says here, renaming (hence regenerating) the /data folder allowed the disconnects to stop. However, it has already happened that it gets once again corrupted, causing us to hotfix it again.

Reproduced with `spongeforge-1.10.2-2171-5.1.0-BETA-1992.jar` and its corresponding Forge.

**Comment by Deamon5550** [comment]
We'd need profiling data from warmroast or `/sponge timings` to be able to debug this.

**Comment by Dysthymic** [comment]
Some further information gathered by Jay113355:

https://bukkit.org/threads/psa-minecraft-1-7-update-possibly-losing-structures.186617/

It has been a fairly well known issue in the past and is still relevant. When this occurs again, I will get a timings report for help with debug but just to clarify we just need a method to disable those structures from saving

**Comment by johnfriedrich** [comment]
That seems to be the feature, but more advanced:
https://github.com/SpongePowered/SpongeCommon/pull/887
