### ISSUE TITLE
SpongeForge and LiteLoader causing crash

### ISSUE THREAD

**Issue by DonyorM** [SpongePowered/SpongeForge#1132]
I am trying to load SpongeForge and Lite Loader on the same profile, but minecraft crashes whenever a world is loaded. Minecraft will load up to the title screen and work fine, but as soon  as I try to load any world, it crashes. I am running this on Java 8, Linux Mint 17 (Ubuntu 14.04).

Forge Log: https://gist.github.com/DonyorM/942315c89e08e45e5b4209c81f775ec2
LiteLoader Log: https://gist.github.com/DonyorM/b58529377a62bdf1f118e6f1fb46a0d9
Minecraft Log; https://gist.github.com/DonyorM/1a1cfcb34e7f34e6be77843a24ab0cb3

This was run in a setup with just Forge, SpongeForge, and Liteloader.
Forge version: 2171
SpongeForge version: 5.10-BETA-2000
Liteloader version: 1.10.2 latest stable

I have downloaded all of these files in the last week or so. I can run either just liteloader or just spongeforge without problem. I have seen issue #378, both mods are placed in the main mods folder, not in the 1.10.2 folder. In order to get minecraft to load at all, I renamed the SpongeForge jar from `spongeforge-1.10.2-2171-5.1.0-BETA-2000` to `aa-spongeforge-1.10.2-2171-5.1.0-BETA-2000`. If I tried to load the two files together without this it crashed before even loading the title screen.

**Comment by Mumfrey** [comment]
You just need to re-download [liteloader stable](http://www.liteloader.com/download#stable_11020) (or [latest snapshot](http://jenkins.liteloader.com/view/1.10.2/)). Basically there is a fix I have to apply to the refmap file because Forge actually outright removes a vanilla method and replaces it with its own. However for some reason beyond my comprehension, this patch was omitted from the refmap when I did the production build (I still have no idea how, since it's done automatically by the build script) and so the stable build originally pushed up was (ironically) not stable.

The broken version was only up for about a day so it's just unlucky that you managed to get that version. If you got it from a different source other than through my site can you please let me know where so that I can tell them they are hosting a broken version.

**Comment by DonyorM** [comment]
I downloaded the file today, same error. I just tried redownloading and extracting it but it still didn't work. Is it specific to my setup then?

**Comment by TheRealDadbeard** [comment]
I have the same issue with the newest stable liteloader on beta 2100

**Comment by marshmellion** [comment]
yes the error still exists
EDIT--> sorry Mumfry i stand corrected. am using 1.10.2 2.0.0#16 and this is working with liteloader and forge. (although it seems something like minetweaker or crafttweaker may break this as[crafttweaker for sure])

Edit 2 --> NM it still crashes on world load with that set up.
forge 1.10.2 version 2221 (3 different lite loaders were tried including the newest 1.10.2 snapshot and recommended) and spongeforge 1.10.2-2221-5.1.0-BETA-2158
(i tried all version of liteloader in and out of the mods folder)

https://gist.github.com/marshmellion/1bb39c3df9115b5b5d33e1963f610298

**Comment by phit** [comment]
@Mumfrey Just retested, this is still an issue with spongeforge-1.10.2-2281-5.2.0-BETA-2464.jar
same crashes as shown above, https://gist.github.com/phit/02174792b2afb96bc37ad86b807ca99b

tested with latest stable liteloader, since there is no version in the filename
Name: liteloader-1.10.2-release.jar
SHA1: 6059F3F484776578B451B17DFF54AD5DA2E1E4D6

**Comment by Mumfrey** [comment]
Posting the crash is almost totally useless to me. Post the logs. The issue in the OP was fixed months ago, the error you're listing there is totally different. I don't normally support such ancient versions but it's possible this can be fixed in Sponge and since 1.10.2 is an LTS version.

**Comment by phit** [comment]
The error is exactly the same? before renaming, Sponge crashes, then after renaming crashes due to playerlist.. scroll down there's two crashlogs. Anyway here's the full latest logs, both before and after rename https://gist.github.com/phit/d901328fb195374facacffcc651583a3

If you no longer support this version, feel free to close this issue, I personally couldn't care less, just helping clean up old issues. I don't even use LiteLoader..

**Comment by Mumfrey** [comment]
The error is different, seeing what the error is I can now see how to fix it.

**Comment by Mumfrey** [comment]
I see the issue, I didn't backport the changes to 1.10.2, I should be able to make a liteloader snapshot version which can incorporate the fix for this.

**Comment by bloodmc** [comment]
This is no longer an issue in latest 1.10.2 liteloader snapshots.
