### ISSUE TITLE
[1.11.2-2393-6.1.0-BETA-2442] Item-despawn-rate setting not making a difference

### ISSUE THREAD

**Issue by bhi-elliot** [SpongePowered/SpongeForge#1201]
As per the discussion over at:
https://forums.spongepowered.org/t/item-despawn-rate-not-working/16832/4
brought up by user tridaak.

item-despawn-rate configuration in global.conf, dimension.conf, and world.conf in /config/sponge does not seem to affect the item despawn rate. It always is the default 5 minutes.

from user simon816
"From looking at the code, the despawn rate is only considered when an item goes 'inactive' (a feature of entity activation). However items never go inactive."

Tried suggestions:
entity-activation-range set to true under modules in global.conf

**Comment by simon816** [comment]
Paging @bloodmc 
`EntityItem` never goes into it's [`inactiveTick()`](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/entityactivation/MixinEntityItem_Activation.java#L49) method because [this check](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/plugin/entityactivation/ActivationRange.java#L151) makes it always active

**Comment by bhi-elliot** [comment]
I am still experiencing the default 5 minute despawn time, even though I have it configured to 12000 ticks. This is the case using SpongeForge build 2054 (or 1.11.2-2201-6.0.0-BETA-2054).
Thoughts?

**Comment by bhi-elliot** [comment]
Just tested again with 2069, same result.

**Comment by simon816** [comment]
I've taken a quick look at this. It appears to be using the world-specific config file rather than the `gobal.conf`, even if `config-enabled` is set to false.
This might be highlighting a larger issue with sponge's config inheritance.

**Comment by bhi-elliot** [comment]
Hi Simon. Thanks all for the help with this.
If I understand what you are saying, I believe that is the correct hierarchy.
World overwrites Dimension overwrites Global.
In my case, I have changed the 'item-despawn-rate' in each of those config files to equal 12000, so it shouldn't matter how the inheritance works, it just needs to actually be influencing the game.

But perhaps I am not understanding you correctly, as I am not sure how `config-enabled` works.

ps - one thought I just had is that I have a custom world name. curious if this is somehow affecting it. In my case, the world conf folder is:
config\sponge\worlds\minecraft\overworld\terabithia

**Comment by bhi-elliot** [comment]
Still an issue as of build 2110.
SpongeForge 1.11.2-2226-6.0.0-BETA-2110
Forge 2226
foxcore-0.10.3-208
foxguard-0.20.2-api5-347
ironchest-1.11-7.0.17.799
Nucleus-0.21.0-S5.1-PR2-plugin
worldedit-sponge-6.1.7-SNAPSHOT-dist

**Comment by ryantheleach** [comment]
Possibly related: 
1. https://github.com/SpongePowered/SpongeForge/issues/1324 
2. https://github.com/SpongePowered/SpongeCommon/issues/1212

**Comment by bhi-elliot** [comment]
Still an issue as of build 2442:
spongeforge-1.11.2-2393-6.1.0-BETA-2442
forge-1.11.2-13.20.1.2393-universal
ironchest-1.11.2-7.0.25.815

**Comment by ryantheleach** [comment]
Possible interactions to investigate:

https://github.com/SpongePowered/SpongeCommon/blob/9e6acff2f9c25f346151420d368a26a0e3578a5b/src/main/java/org/spongepowered/common/mixin/realtime/mixin/MixinEntityItem.java

https://github.com/SpongePowered/SpongeCommon/blob/8824c6f4635e721228ac5e211a3c9f3fbf8a6dfb/src/main/java/org/spongepowered/common/mixin/core/entity/item/MixinEntityItem.java

https://github.com/SpongePowered/SpongeCommon/blob/877393fe75621e2ebbe75cd4639bad1a0deb316b/src/main/java/org/spongepowered/common/mixin/entityactivation/MixinEntityItem_Activation.java

I suspect that we arn't checking the forge method of setting an item to undespawnable correctly, aging them when they are not in activation range and possibly ignoring the magic values set in the other mixin.

Will need to investigate this in a debugger, with a sample mod.

https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/a665200c311e68975117d6e1b7dda9232aca2bcd/src/main/java/appeng/entity/EntityGrowingCrystal.java#L54

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeCommon/blob/877393fe75621e2ebbe75cd4639bad1a0deb316b/src/main/java/org/spongepowered/common/mixin/entityactivation/MixinEntityItem_Activation.java#L49

should be calling `getActiveConfig` instead of `getWorldConfig` that fixed the config not working in my dev environment

regarding the despawning of items that shouldn't due to `setNoDespawn`, forge adds its own "[lifespan](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/patches/minecraft/net/minecraft/entity/item/EntityItem.java.patch)" nbt tag which gets set to max int in case of no despawn, currently sponge doesnt deal with that at all hence items despawn like any other when reaching the age set in the config

**Comment by phit** [comment]
@kashike this also applies to 1.10 and 1.12

**Comment by ryantheleach** [comment]
https://github.com/SpongePowered/SpongeForge/issues/1324#issuecomment-325364383 reports that it is not reproducible in single player.
