### ISSUE TITLE
Dupe bug with half blocks 

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1210]
Pistons pushing half blocks will dupe them. I dont know how to exactly explain, but that's a setup:

![a](https://cdn.discordapp.com/attachments/265252707751821313/271670973671931905/unknown.png) 

![a](https://cdn.discordapp.com/attachments/265252707751821313/271671092370866176/unknown.png) 

   Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-b7a6e54
    SpongeForge: 1.10.2-2202-5.1.0-BETA-2053
    Minecraft Forge: 12.18.3.2185

**Comment by Aaron1011** [comment]
This is actually a Vanilla bug, but I haven't been able to find a corresponding Mojira ticket. I'll investigate further, and link the issue I create here.

**Comment by Aaron1011** [comment]
I've determined the following necessary conditions for this bug:

* The top block needs to be moveable, with a `neighborChanged` method that drops it when no longer supported. Both rails and carpets fulfill these requirements, and substituting in carpet for rail causes the same dupe bug to occur
* The bottom block's `getMobilityFlag` method needs to return `EnumPushReaction.DESTROY`, and also allow blocks to be placed on top of it. Both pumpkins and leaves fulfill these requirements - as in the previous example, you can substitute in a leaf block for a pumpkin block, and still reproduce this bug.

**Comment by Aaron1011** [comment]
Since there's no associated Mojira ticket for this, I'll summarize the issue here:

The bug was caused by the second call to `World#setBlockToAir` in `BlockPistonBase#doMove`, which occurs when destroying blocks (blocks that return `EnumPushReaction.DESTROY` from `Block#getMobilityFlag`). `setBlockToAir` calls `setBlockState` with a flag of 3, which causes neighbor notifications to take place.

Normally, causing neighbor notifications is fine - but during a piston move, it causes problems with blocks that can be moved, but require themselves to be 'supported' (carpets and rails). When the neighbor notification occurs, the rail or carpet notices that it is no longer being 'supported' (the block underneath is air), and causes itself to drop and destroy itself. However, this check never should have taken place - the rail or carpet is about to be 'moved' by the piston, which means that the block will be re-created one position lower.

The fix for this issue, which is present in Vanilla 1.11.2, is to directly call `setBlockState`, specifying a flag of 4 (the neighbor notification flag is 2, which is bitwise-AND'ed against the specified flag). This prevents yet-to-be-moved blocks from being updated when the world is in an intermediate state, preventing the erroneous item drop from occuring.

For reference, here's a video which shows how to reproduce the issue (the title refers to 1.9, but it also applies to 1.10.2): https://www.youtube.com/watch?v=WReowIcGI8M

**Comment by Eufranio** [comment]
Thanks!
