### ISSUE TITLE
Possible EntityTracker issue

### ISSUE THREAD

**Issue by CyanGenesis** [SpongePowered/SpongeForge#1215]
Hi, there appears to be a problem related to SpongeForge with a forced entity spawn. As a little background info, this issue happens when trying to use a packet to spawn in an entity(from a GUI) from my mod. I want to note that single player works fine, and launching a test server with the Forge MDK works fine, but upon launching up a small private server for myself with SpongeForge added in, I seem to get this: http://pastebin.com/jCfW0ZjX

Minecraft: 1.10.2
SpongeAPI: 5.1.0-SNAPSHOT-b7a6e54
SpongeForge: 1.10.2-2202-5.1.0-BETA-2068
Minecraft Forge: 12.18.3.2185

Thanks for any help you may be able to provide with this issue.

**Comment by Aaron1011** [comment]
@CyanGenesis: This warning is caused by the fact that your mod is calling `World#spawnEntity` directly from a packet handler method. As [the MinecraftForge docs state](https://mcforge.readthedocs.io/en/latest/networking/simpleimpl/#imessagehandler), packet handlers are run on Netty threads, and therefore should always schedule a task (on the main thread) in order to interact with the main game.
