### ISSUE TITLE
Asynchronous tasks with interval don't wait for the previous occurrence of the task to terminate

### ISSUE THREAD

**Issue by KaiKikuchi** [SpongePowered/SpongeForge#1261]
From [Sponge JavaDoc Task.Builder class, interval method](https://jd.spongepowered.org/5.0.0/org/spongepowered/api/scheduler/Task.Builder.html#interval-long-java.util.concurrent.TimeUnit-):
> If the scheduler detects that two tasks will overlap, the 2nd task will not be started. The next time the task is due to run, the test will be made again to determine if the previous occurrence of the task is still alive (running). As long as a previous occurrence is running no new occurrences of that specific task will start, although the scheduler will never cease in trying to start it a 2nd time.

I'm not sure if I misunderstood. This should avoid that a single Task is running multiple times at the same time. I recently found this doesn't happen.

Using:
forge-1.10.2-12.18.3.2221
spongeforge-1.10.2-2221-5.1.0-BETA-2136

Example:
We have this simple task with a blocking queue:
```java
public class TaskTest implements Runnable {
  public LinkedBlockingQueue<String> blockingQueue = new LinkedBlockingQueue<>();

  @Override
  public void run() {
    try {
      System.out.println("begin");
      blockingQueue.take(); // thread blocks here until a String is offered
      System.out.println("end");
    } catch (InterruptedException e) {

    }
  }
}
```

And we submit this task during the GamePreInitializationEvent (I've tested with GameStartedServerEvent too) as following:
```java
Sponge.getScheduler().createTaskBuilder()
    .execute(new TaskTest())
    .async()
    .interval(100, TimeUnit.MILLISECONDS)
    .submit(this);
```

The server output will be filled with "begin" and no "end".
A thread dump will show a lot of TaskTest threads.

I was expecting just one "begin" line, until another thread offers a String to the queue.

**Comment by Brend-Smits** [comment]
Any update on this by any chance? Seems to be a pretty significant issue

**Comment by ryantheleach** [comment]
I've confirmed this issue, but I'm not entirely confident on my fix.

My instinct is to introduce a TaskState of Stopped, and only start the interval ticket if the task is of state stopped, but then questions of the timing arises.

If the task is overdue, and the task overruns, should it start immediately? or pause for 100 milliseconds after it stops? Should the scheduler warn on overruns?

Additionally, 

```
   /**
     * Gets the timestamp to update the timestamp of a task. This method is task
     * sensitive to support different timestamp types i.e. real time and ticks.
     *
     * <p>Subtracting the result of this method from a previously obtained
     * result should become a representation of the time that has passed
     * between those calls.</p>
     *
     * @param task The task
     * @return Timestamp for the task
     */
    protected long getTimestamp(ScheduledTask task) {
```

Does not return ticks, for the async scheduler.

**Comment by KaiKikuchi** [comment]
In my opinion, it should support both behaviors, similar to Java's [ScheduledExecutorService](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ScheduledExecutorService.html) [scheduleAtFixedRate](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ScheduledExecutorService.html#scheduleAtFixedRate-java.lang.Runnable-long-long-java.util.concurrent.TimeUnit-) and [scheduleWithFixedDelay](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ScheduledExecutorService.html#scheduleWithFixedDelay-java.lang.Runnable-long-long-java.util.concurrent.TimeUnit-) methods as someone wants to use one instead of another based on what they're trying to achieve.

> protected long getTimestamp(ScheduledTask task)

I guess this is probably returning milliseconds from epoch.

**Comment by dualspiral** [comment]
> If the task is overdue, and the task overruns, should it start immediately? or pause for 100 milliseconds after it stops?

_Based on what the docs say_, if the task is overdue, I think it's reasonable to just drop that attempt and wait for the next time around. In this case, the fix you suggest seems to me to be a reasonable way around it, if a task is running when the next attempt to start it comes around and the `TaskState` isn't in the `STOPPED`, just don't start the task that time around.

A plugin author should have a handle on how often they need to run the task, which should also include estimations on how long a task should take, if it's a long running task, and should be aware of this.

I'd argue that queuing attempts to run immediately after might be a problem - if a task continuously overruns, then the schedule is just going to build up these tasks to run, and then we'd probably have to skip some of the queued tasks anyway and having the scheduler is pointless. I _personally_ think we just need to go for the simplest approach here, dropping tasks, but ensure that the docs are clear on this.

> Should the scheduler warn on overruns?

I'd want to say it might be useful, but it's entirely dependent on the time length, and this is only really appropriate for async repeatable tasks. If a method that fires every 100 milliseconds overruns, that's probably not a big deal. If it's a method that fires every 5 minutes that overruns, then... maybe. If a task takes much longer, then sure. We can't know whether the plugin author intends to let it overrun because they only _loosely_ want to run to that schedule or just want to use it as a way to restart a task that ends (which is what the intention is behind the snippet above, I suspect) - in which cases, it wouldn't be.

So, no, on balance, probably not.

**Comment by phit** [comment]
~move to sc

**Comment by limbo-app** [comment]
Hey @KaiKikuchi! I've moved your issue to [SpongePowered/SpongeCommon#2199](https://github.com/SpongePowered/SpongeCommon/issues/2199).
