### ISSUE TITLE
"No entity type is registered for class" errors

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/SpongeForge#1272]
As of spongeforge-1.10.2-2221-5.1.0-BETA-2156, fake players are reporting errors in console:
```
[08:54:52] [Server thread/ERROR] [Sponge/]: No entity type is registered for class ic2.core.Ic2Player
[08:55:08] [Server thread/ERROR] [Sponge/]: No entity type is registered for class com.rwtema.extrautils2.fakeplayer.XUFakePlayer
```

**Comment by Eufranio** [comment]
This is not an error.

**Comment by LemADEC** [comment]
The log does say ERROR.
Either it should be fixed or not being in the logs.

**Comment by Aaron1011** [comment]
Closed in https://github.com/SpongePowered/SpongeCommon/commit/3e1efc372ce74d51ce303ba48f3efbecda43e5d2.

This should have been a warning, not an error - my bad. While it's normally a sign that a mod is doing something wrong, the two classes mentioned above appear to be various 'fake player' classes. Since these never actually get spawned into the world, you can safely ignore them.
