### ISSUE TITLE
Create a warning when a mod overflows it's bounds during worldgen.

### ISSUE THREAD

**Issue by Tencao** [SpongePowered/SpongeForge#1289]
New world, happened to randomly crash when exploring
Sponge version - 1.10.2-2221-5.1.0-BETA-2178
Forge version - 12.18.3.2221
Crash report - https://paste.ee/r/TTdpt

**Comment by Deamon5550** [comment]
Huh I think I can guess what happened. I believe a mod managed to spill so far passed its boundaries that it triggered a new chunk to generate and since generation makes use of a cached biome volume it got moved to the new generating chunk then then when it returned to the original chunk the biomes had been moved from under it and it crashed.

We see far too many errors from mods causing recursive generation by overflowing their bounds. I'm going to start naming and shaming them when a recursive chunk request is detected.

**Comment by Tencao** [comment]
If it helps, I had biomes o plenty biome size set to 6, instead of the default 4. Not sure if that is the direct cause for this, or if it's something else.

**Comment by phit** [comment]
is this still an issue? the log file is no longer available

**Comment by Deamon5550** [comment]
Its still an issue in so far as we should add some logging to recursion during the generation phase (forge already has logging if it happens in the population phase)

**Comment by ryantheleach** [comment]
I'd like to see a reply to this with a 1.12 mod that is able to cause the issue, or a test mod that causes the issue, so I can add logging at the appropriate point.

**Comment by ryantheleach** [comment]
From forges changelog:
```
Build 1.12.2-14.23.4.2708:
	bs2609:
		Fix structure template processors causing cascading world generation
		(#4979)
```

**Comment by gabizou** [comment]
Forge already has a fair bit of cascading world generation logging and warnings now, I'd say it's not worth for us to add on to the warnings that mod authors will probably be annoyed about already. With 1.13+ having already rewritten the world generation pipeline, this won't be an issue in the future, but for 1.12's development, I don't think it's necessary to add even more world generation logging for adding more chunks.
