### ISSUE TITLE
Crashes with Mo'Creatures 

### ISSUE THREAD

**Issue by iLefty** [SpongePowered/SpongeForge#1323]
After installation MoCreatures mod the server began to crash often. In a today already 6 times. I don't want to delete this mod, it is necessary to learn a problem and to fix it.
On the server there is many loaded chunkes (till 6000) and entityes (till 30000). Possibly it also is the reason of crashes.
All information about mods and their versions, present in crash reports.
Reports in archive:
https://yadi.sk/d/O-ZPGo4_3EzRAz

**Comment by iLefty** [comment]
http://pastebin.com/EbTn0aWC
One more crash.

**Comment by ryantheleach** [comment]
@Deamon5550 Cursory look seems like some funky dungeon generation happening outside the required chunk.

However since it's MoCreatures, it's not open source, and neither is it's utility custom mob spawners.

So I'm guessing this is a bug in MoCreatures since my understanding is things shouldn't ever be generating outside the requested bounds.

**Comment by ryantheleach** [comment]
@iLefty Was your issue fixed? If you were closing over my comment it was just a guess.

**Comment by iLefty** [comment]
@ryantheleach, I closed this, because more than 2 months, this crash don't was. All, that I done - updated Sponge and plugins versions. Later I did the game world wipe, but the crash cease to occur until the wipe.
