### ISSUE TITLE
Rendering Glitch - Coke Oven and Blast Furnace

### ISSUE THREAD

**Issue by jmercado808** [SpongePowered/SpongeForge#1343]
This happens on a spongeforge server. Not in SP.

So, for some reason when right clicking on the center block for the Coke Oven and Blast Furnace, more pieces appear. They are not actually there, but they look very strange.

Edit: When breaking any blocks on either of them, additional blocks are created and fly off from the main structure. Causing duplication.

put a wood block in there to show that the blocks are phantom
![image](https://cloud.githubusercontent.com/assets/25890631/23774677/ef3003cc-04c8-11e7-8899-97a8d249f252.png)

![image](https://cloud.githubusercontent.com/assets/11083387/23636785/b3acf37c-0294-11e7-9400-7bde63c52c2a.png)

**Comment by phit** [comment]
seeing the same thing on my ftb beyond server
1.10.2-2221-5.2.0-BETA-2226

**Comment by ryan-hoang** [comment]
Getting the same issue, We're using 1.10.2-2221-5.2.0-BETA-2226 too.

**Comment by StoneLegion** [comment]
Same here

Forge: forge-1.10.2-12.18.3.2254
SpongeForge: spongeforge-1.10.2-2254-5.2.0-BETA-2264

When you build a Coke Oven or a Blast furnace and use the hammer to right click and assemble it causes the multiblock structure to malformed and become bigger then normal. Then when you break it you end up getting extra pieces (duping it).

![Blood has failed me](https://i.imgur.com/EsugfSs.png)

**Comment by gabizou** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/1941#issuecomment-293054534

When I get a chance to investigate the issue, I'll do so.

**Comment by StoneLegion** [comment]
Thanks for the update. It's not so much the dupe but the ugly bases it's causing haha. Dupes are bad too though :) Let us know if you need testing.

**Comment by StoneLegion** [comment]
@gabizou 
Not sure if this will help but we have actually had even bigger errors with it:
https://pastebin.com/Yfy0eiV3

Someone was trying to assemble  it and did not work so they broke it and was causing those errors and did not get all the blocks back. Playing a Hardcore (Expert) Pack these guys are suffering a lot with having to refarm for mats.

**Comment by malte0811** [comment]
I have made some progress on this, it is caused by a race condition with the async lighting. Both the main thread ([here](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/blocks/multiblocks/MultiblockCokeOven.java#L92)) and the lighting thread ([full stacktrace](https://gist.github.com/malte0811/c725b6066f4445b97828d154d17d5701), the light value of IE's blocks depend on the TE in some cases) are calling `getTileEntity`, directly or indirectly. This leads to the creation of 2 TileEntities, one in the Lighting thread and one in the server thread. The TE that is actually kept in the world is the one that is created later. If the server thread gets the earlier TE, it will set the correct values in that TE, which will be removed as soon as the GC finds it. The TE that is kept in this case is the one from the lighting thread, which contains no useful information at all.
I won't look into fixing this today as it is 10:45PM here and this doesn't seem to be the sort of thing I could fix while tired, I might take a look tomorrow though.

**Comment by StoneLegion** [comment]
Thank you for the update. I'm personally waiting before continuing playing myself only because the crazy big machine blocks are crazy looking and of course the other issues that they might face.

http://i.imgur.com/OAsTimy.png

**Comment by StoneLegion** [comment]
Just updating this that removing / disabled async lighting has fixed the issue. 
https://i.imgur.com/FapYZcN.png

**Comment by SynexWolf** [comment]
Hey @KaneHart , How did you disable async lighting?

**Comment by StoneLegion** [comment]
@Lt1489 it's via the sponge config. Just search it should be easily found in there.

**Comment by SynexWolf** [comment]
Thanks @KaneHart found it.

**Comment by FiveEYZ** [comment]
this is happening again on 1.11.2

async-lighting is set to false

versions:
spongeforge-1.11.2-2393-6.1.0-BETA-2463
ImmersiveEngineering-0.11-63

[![Screenshot from Gyazo](https://gyazo.com/0b5cb897d7421b1c09a33f34de4dff57/raw)](https://gyazo.com/0b5cb897d7421b1c09a33f34de4dff57)

**Comment by malte0811** [comment]
Does relogging or F3+A fix this?

**Comment by FiveEYZ** [comment]
No, it doesn't @malte0811

**Comment by phit** [comment]
I'm not seeing this myself with the same IE and Sponge version, async is enabled for me.
You sure this is caused by Sponge?

**Comment by FiveEYZ** [comment]
maybe i should enable async-lighting then
