### ISSUE TITLE
SpongeForge [spongeforge-1.10.2-2254-5.2.0-BETA-2231] Causing a CNF when registering a EventHandler.

### ISSUE THREAD

**Issue by marchermans** [SpongePowered/SpongeForge#1357]
Hello,

I am the mod developer for SmithsCore a library currently in use by some mods I develop.
This library is based of Minecraft Forge and runs fine in a non Spone environment.
However, when my mod is put into a SpongeForge server, it fails to register an Event with a ClassNotFound exception.

The Log: https://gist.github.com/OrionDevelopment/a191e0f29a0b196272af5c4eedc68bbc
The class that is being registered in question: https://github.com/SmithsGaming/SmithsCore/blob/Development-1.10/src/com/smithsmodding/smithscore/common/structures/StructureRegistry.java

Is their something that i am doing wrong here? Do i need to write a mixin to support Sponge?
Any information is welcome.

Greets,

Orion.

**Comment by stephan-gh** [comment]
I get the same error when I install `SmithsCore` on a Forge server without Sponge.

**Comment by marchermans** [comment]
@Minecrell Hmm i tested it again today with the latest versions and i am not getting this. Could you send me a log from the vanilla forge server?

**Comment by stephan-gh** [comment]
@OrionDevelopment Doesn't happen anymore, I'm pretty sure https://github.com/SmithsGaming/SmithsCore/commit/b17a04c97a35efab385c4b9f1d6ae7cbdab14165 fixed it. Please re-test using your latest version and the latest SpongForge.

**Comment by marchermans** [comment]
Yep i was finally able to reliably reproduce it. With the help of the guys from the forge irc channel i fixed it. But we still have no clue why the EventSubscriptionTransformer does not like that IStructureFactory Interface. Inparticularly we have no idea why it throws the cnf when the interface gets clearly loaded when we add -verbose:class as vm argument. But whatever, it works now.

**Comment by stephan-gh** [comment]
@OrionDevelopment 
> Inparticularly we have no idea why it throws the cnf when the interface gets clearly loaded

Class loaders. Forge uses two separate class loaders, and MC and mods are loaded in a special class loader that is able to transform the classes before they are loaded. However, the library that is used to transform the classes (ASM) is loaded in the main class loader which does not have access to the classes of mods.

Normally, this is not a problem because it just needs to transform the bytecode of the classes, however there is a special case that requires ASM to load some classes in order to process the bytecode correctly. I'm not completely sure in which case this is required (usually it is not), but since ASM operates in the main class loader it fails to load the classes from your mod.

**Comment by marchermans** [comment]
Then why does this work when I run the code in a deobfed environment? (Thanks for the Info btw)

**Comment by stephan-gh** [comment]
@OrionDevelopment 
I can't tell for sure but most likely it's the following:

There are two different ways how Forge can load mods: either in a JAR in the `mods` folder or directly from your classpath. Usually, if you run your mod in a deobfuscated environment you load it directly from the classpath (because you are in your mod workspace). If your mod is already on the classpath then it will be available in both class loaders. On the other hand, if your mod is loaded from the JAR, Forge will only add it to the class loader that is used to load and deobfuscate Minecraft.

**Comment by marchermans** [comment]
Ah okey. Thanks for the info
