### ISSUE TITLE
Cancelling of event leading to duping.

### ISSUE THREAD

**Issue by merjilin** [SpongePowered/SpongeForge#1376]
Hey, there! I've been sent by bloodshot regarding the cancelling of an event leading to dupes. I'll merely quote my previous issue.
"I've recently found out that upon updating to the newest GP around 7 hours ago, player have already managed to find and manipulate a bug. The bug allows a player to get duplicate blocks which have been mined using a PSI laser with the tick break block and OreExcavation and it only occurs in claims.
Modpack= Resonant Rise 4 version 4.1.1.1-b (Found on the ATLauncher)
Steps to reproduce:
1.hold down the key for vein miner
2.then use the psi gun spell break block while in another players claim
(it doesnt work if you're trusted)"
SF build: 2236

**Comment by Brend-Smits** [comment]
This is also an issue on Sky Factory 3, has been for quite some time. Could anything be done about this?

**Comment by phit** [comment]
@merjilin was this ever resolved?

**Comment by merjilin** [comment]
I no longer have a 1.10 environment setup for testing, but it wasn't resolved when I had a server on API 5.

**Comment by phit** [comment]
Closing this issue, as of today 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please [open a new issue](https://github.com/SpongePowered/SpongeForge/issues/new) with updated information.
