### ISSUE TITLE
null when completing phase after onChunkPopulateFinish 

### ISSUE THREAD

**Issue by Vhisper** [SpongePowered/SpongeForge#1415]
Hi, I just wanna say that I have no idea what this error means, but it said to report. As far as I know, I didn't notice anything different nor did it crash my server. I also had to format the log file into a .docx because .long isn't supported. I can provide other diagnostics if needed.

[fml-server-latest.docx](https://github.com/SpongePowered/SpongeForge/files/893770/fml-server-latest.docx)

**Comment by gabizou** [comment]
Re-upload the log to something like gist.github.com

**Comment by Vhisper** [comment]
@gabizou 
https://gist.github.com/Vhisper/21246dd23e8d97ef27a762c3f392e98c

Sorry about that.

**Comment by gabizou** [comment]
Closing this issue, as of today 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please [open a new issue](https://github.com/SpongePowered/SpongeForge/issues/new) with updated information.
