### ISSUE TITLE
Major Issue - Preventing World Server Start 1.10.2 - 1.10.2-2281-5.2.0-BETA-2274

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SpongePowered/SpongeForge#1443]
I cannot make a world or start server I am getting infinite spam. The only Sponge mod I have is the Enjin plugin.

Spam from hell "https://gist.github.com/P3rf3ctXZer0/cc9d374b603f1355c7ad754580bd4234"

622506 Copies of this spam

**Comment by P3rf3ctXZer0** [comment]
This spam does not exist with this version 1.10.2-2254-5.2.0-BETA-2272 also the server starts. Using Forge 1.10.2 - 12.18.3.2281 

I am including my modlist maybe it will help.

[DirPrintTemp.txt](https://github.com/SpongePowered/SpongeForge/files/923992/DirPrintTemp.txt)

Redacted - So Its weird it happened again ... seems to happen on new world generation ... It has an additional error code though. https://gist.githubusercontent.com/P3rf3ctXZer0/0088ac520ff64ac4b2a141dde2c4ac13/raw/ddb2d45fc44142a69f90b4fc5caad681c9e158c9/gistfile1.txt

Oh Yay an actual crashlog! Before it didn't produce a crashlog https://gist.github.com/P3rf3ctXZer0/ada7e9e77a2dfe94fdf456dc39b0c96c - Something about updating neighbors.

Okay so I learned something odd ... if I kill Server then Start Server let it get a little further ... and kill it again and start it one last time it will work @.@ I am not remotely sure why this is happening.

**Comment by Deamon5550** [comment]
Could your try uploading an actual log file rather than these rather useless snipets.

From what I can see the issue is mods causing recursive worldgen by loading adjacent chunks. some culprets here are railcraft's [WorldGenQuarry](https://github.com/CovertJaguar/Railcraft/blob/fb37747027c4faf2fb2c80a9ad467369a09f4d00/src/main/java/mods/railcraft/common/worldgen/WorldGenQuarry.java#L109-L126), Pam's harvestcraft's [LogFruitTreeGen](https://github.com/MatrexsVigil/harvestcraft/blob/1.11.2/src/main/java/com/pam/harvestcraft/worldgen/LogFruitTreeGen.java#L51-L61), Quark's [StoneInfoBasedGenerator](https://github.com/Vazkii/Quark/blob/master/src/main/java/vazkii/quark/world/world/StoneInfoBasedGenerator.java#L66-L86).

Please take this issue up with these mods, and if they try and say that its a problem with sponge direct them to [this commit in forge](https://github.com/MinecraftForge/MinecraftForge/commit/4fbc84773650580008295a234302fc5618af5fcb) ([and associated PR](https://github.com/MinecraftForge/MinecraftForge/pull/3756)) which adds detection and warnings for precisely this behaviour as it causes major performance loss during generation and can lead to all sorts of issues with other mods and vanilla ([see this description](https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/)).

**Comment by CovertJaguar** [comment]
It's not Quarries, they only operate on single chunks. You are just blaming everything that happens to be in those chunks rather than the actual cause, which appears to start with Pam's. -.-

**Comment by Deamon5550** [comment]
@CovertJaguar Right here in the middle of that stack posted

```
15.04 20:34:04 [Server] Server thread/ERROR [Sponge]: /* net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120) */
15.04 20:34:04 [Server] Server thread/ERROR [Sponge]: /* net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001) */
15.04 20:34:04 [Server] Server thread/ERROR [Sponge]: /* net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:964) */
15.04 20:34:04 [Server] Server thread/ERROR [Sponge]: /* net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154) */
15.04 20:34:04 [Server] Server thread/ERROR [Sponge]: /* net.minecraft.world.World.func_72964_e(World.java:303) */
15.04 20:34:04 [Server] Server thread/ERROR [Sponge]: /* net.minecraft.world.World.func_175726_f(World.java:298) */
15.04 20:34:04 [Server] Server thread/ERROR [Sponge]: /* net.minecraft.world.World.func_180495_p(World.java:5690) */
15.04 20:34:04 [Server] Server thread/ERROR [Sponge]: /* net.minecraft.world.World.func_175623_d(World.java:223) */
15.04 20:34:04 [Server] Server thread/ERROR [Sponge]: /* mods.railcraft.common.plugins.forge.WorldPlugin.isBlockAir(WorldPlugin.java:69) */
15.04 20:34:04 [Server] Server thread/ERROR [Sponge]: /* mods.railcraft.common.worldgen.WorldGenQuarry.placeAir(WorldGenQuarry.java:120) */
15.04 20:34:04 [Server] Server thread/ERROR [Sponge]: /* mods.railcraft.common.worldgen.WorldGenQuarry.func_180709_b(WorldGenQuarry.java:82) */
15.04 20:34:04 [Server] Server thread/ERROR [Sponge]: /* mods.railcraft.common.worldgen.PopulatorQuarry.populate(PopulatorQuarry.java:48) */
15.04 20:34:04 [Server] Server thread/ERROR [Sponge]: /* mods.railcraft.common.worldgen.Populator.populate(Populator.java:45) */
```

Which is caused by [this line](https://github.com/CovertJaguar/Railcraft/blob/fb37747027c4faf2fb2c80a9ad467369a09f4d00/src/main/java/mods/railcraft/common/worldgen/WorldGenQuarry.java#L120) checking if the neighbouring block is air, which since it is iterating purely within the chunk and not at an 8 block offset is causing the neighbouring chunk to load.

**Comment by CovertJaguar** [comment]
Say what again? 8 block offset?

**Comment by phit** [comment]
explanation of the issue
https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/

>Correct world generation offsets everything by +8, +8 so that all generation happens in the middle of the loaded chunks, and has a low chance of spilling out.
http://i.imgur.com/YJChrfm.png
