### ISSUE TITLE
VeinMiner problem cause by spongeforge

### ISSUE THREAD

**Issue by fabri2000779** [SpongePowered/SpongeForge#1460]
**I am currently running...**

- SpongeForge version: spongeforge-1.10.2-2281-5.2.0-BETA-2274
- Forge version: forge-1.10.2-12.18.3.2281-universal.jar
- Java version: jre1.8.0_121
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
 Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, IvToolkit, Not Enough Items, SpongeAPI, SpongeForge, CoFH ASM, FoamFixCore, ccl-entityhook, InfinityLib, AgriCraft, Just Enough Items, AppleSkin, ArchitectureCraft, Avaritia, Avaritia Additions, Baconators, MineTweaker 3, B.A.S.E, Baubles, Better Builder's Wands, Biomes O' Plenty, Block Armor, Botania, CodeChicken Lib, CoFH Core, Brandon's Core, CatClearLag, Chameleon, Chance Cubes, Chest Transporter, CodeChicken Core, ChickenChunks, Chickens, Chisel, MCMultiPart, Chisels & Bits, Clumps, Cyclops Core, Colossal Chests, 1.12 Concrete, Cooking for Blockheads, Crafting Tweaks, CropDusting, PTRModelLib, Decocraft, Discord Bridge, Draconic Evolution, Elevator Mod, Embers, EnderCore, Waila, Ender IO, EnderStorage, Ender Zoo, Extra Utilities 2, FakeBlocks, Fast Leave Decay, Flat Colored Blocks, FoamFix, FTBLib, FTBUtilities, Gravestone, Hatchery, Hermitron, iChunUtil, Inspector, Inventory Pets, Inventory Tweaks, Iron Chest, Iskallium Reactors, JourneyMap, Loot Bags, LootTweaker, LuckPerms, MalisisCore, MalisisDoors, Mantle, RadixCore, Minecraft Comes Alive, MineTweakerRecipeMaker, Natura, Railcraft, Tinkers' Construct, MoarSigns, mob_grinding_utils, Example Mod, Modifiable Armor 2, MTLib, Mod Tweaker, More Chickens, More Loot Tables, MorePlayerModels, Morpheus, Modern Warfare, Mystical Agriculture, Nether Core, Nucleus, Pam's HarvestCraft, Thermal Foundation, PlusTiC, Recurrent Complex, Storage Drawers, Refined Storage, RFTools, Roguelike Dungeons, ShadowMC, SimpleLabels, Simply Conveyors, Sleeping Bag, Subaraki's Common Library, Thermal Expansion, Tinkers Tool Leveling, Tiny Progressions, TorchMaster, Translocator, Useful Nullifiers, Vein Miner, Mod Support, ViesCraft, WAILA Features, I Can See Everything, What Are We Looking At, Waystones, WeaponCaseLoot, Woot, XP-Plus, Moo Fluids
**What is the expected result?**
I run a Foolcraft server and to be honest all is pretty good, the sponge plugins run good but i see that sponge have trouble with veinminer mod, i would love that you fix this
**What is the current result?**
When server start is perfect everyone can connect to it any any type of problem appear but after some hours nobody can connect to the server is give a error rejection with VeinMiner, i test my server for a day (removed sponge) and all is perfect and when i put sponge back it start the error again
https://github.com/portablejim/VeinMiner/issues/95

When player join to my server:
https://gist.github.com/fabri2000779/144c004479f524c298e5a9912f12532f
client log:
https://gist.github.com/fabri2000779/2b678a34bed3cfc922bd72927735576e

**Comment by gabizou** [comment]
I don't even know where to begin with this since Sponge doesn't hook into forge mod detection in any way (except telling forge to load sponge plugins). Do you have bungee cord usage enabled? This appears to be something very nested within the login process of players, but as far as what is causing it, it's not very well evident.

I can't directly say that sponge is at fault, but it does seem to be a common theme based on the VeinMiner issue.

**Comment by fabri2000779** [comment]
no i dont have bungee cord, but this error dont have sense i mean the veinminer dev dont know what is going to the only that we have is that is happening all the server that use sponge

**Comment by johnfg2610** [comment]
we are having the same issue and are running bungeecord

**Comment by Bennyboy1695** [comment]
Can confirm this is caused by Sponge, had a purely Forge server running a pack with Veinminer in it, players could join it with no issues at all. As soon as it was turned into a sponge server players got the Veinminer mod rejection.

**Comment by ukdyl94** [comment]
Just out of curiosity do these players have VeinMiner client side or is it server only.

**Comment by johnfg2610** [comment]
On our server the client and server had it installed

**Comment by ukdyl94** [comment]
Same here; it makes me wonder if maybe it should only be on the server. My mod pack is currently in a testing phase so I'll give it a go and see if any more issues arise. 
		

		Get Outlook for iOS
	





On Sun, Jun 4, 2017 at 3:38 AM -0400, "Johnfg10" <notifications@github.com> wrote:












On our server the client and server had it installed

**Comment by Bennyboy1695** [comment]
Veinminer is required on both, if its not on the server then its not usable by the clients joining with it. And if its not on client its the same as the client can't tell the server "hey im veinmining break all these blocks"

**Comment by ukdyl94** [comment]
After doing some testing @Bennyboy1695 It's not required for Veinminer to be on the client side.

**Comment by dualspiral** [comment]
Subtle bug, but this turns out to be a thread safety problem. [I've explained it on the VeinMiner issue](https://github.com/portablejim/VeinMiner/issues/95#issuecomment-306060287), but it exposes a Sponge bug too.

[The problem is here, in the event manager code](https://github.com/SpongePowered/SpongeForge/blob/bleeding/src/main/java/org/spongepowered/mod/event/SpongeModEventManager.java#L304-L324). When Sponge posts an event, it sets this active mod container. In a single threaded world, this is all fine and dandy, the active mod container will be set and unset as expected. However, Sponge has a few async events (such as `ClientConnectionEvent.Auth`, which could run for a short but noticable time for anyone doing a database call), and problems start to arise. These events can cross over:

* Sync event fires. It sees there is no active container (null), and stores that.
* Sync event starts looping over the event handlers, setting the containers as required.
* Async method starts. It sees that there _is_ a mod in the active container, and stores that.
* Async method starts looping over the event handlers, setting the containers as required - we've already got a problem here.
* Sync method finishes, sets null to the container.
* Async method finishes, sets the mod it saw in the active container at the time, and sets it as the active mod when it really shouldn't.

Now, VeinMiner was trying to get this active container during connection, _off the main thread_, so if a sponge event was firing on the main thread, it would have gotten that container. [I used this code](https://gist.github.com/dualspiral/dd7006f4c18041ac0e65d757da497101) to fire an event every tick that lasted for 90% of the tick time. I then logged in, and was able to get a mod rejection - and saw that the mod version that VeinMiner was checking for wasn't its own, but that of my test plugin:

![broken](https://cloud.githubusercontent.com/assets/1904167/26764728/88ac5b38-4964-11e7-86a0-09e00de34019.png) 

However, I think the above is also occurring, and so Sponge gets the system stuck in a state where the active mod container is always set, is never VeinMiner, and as a result, the version check always fails. So, the fix is to make this more thread safe, and also to make `getActiveContainer` _always_ get the mod container from the call stack if we're not on the main thread.

I'm going to PR my potential fix, because I'm unsure whether it will potentially break other mods, so would appreciate the review - but my testing indicates that I was able to log in using VeinMiner by doing this.
