### ISSUE TITLE
Server Crash - 1.10.2 During World Chunk Loading

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SpongePowered/SpongeForge#1472]
I crashed during tick loading a chunk. Also if I type /spawn it seems sponge breaks ftb utilitilies.

**I am currently running...**

- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2274
- Forge version: 1.10.2-2281
- Java version: Java 8 u131
- Operating System: Win 10 Pro

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [X ] Windows

- Plugins/Mods: 
https://gist.github.com/P3rf3ctXZer0/eeda9e25e72e8f0497eb701545bac85d
**What is the expected result?**
I was not interested in crashing. I want players to able to warp without issues.
**What is the current result?**
Crash Log
https://gist.github.com/P3rf3ctXZer0/a4babc0f2827984bad8625dd8c0e6bb7

Too much spam in log I am going to have to say get it from my dropbox.
https://www.dropbox.com/s/prh9779o71bcuhn/Sponge%20Full%20Crash%20Log.log?dl=0

**Comment by bloodmc** [comment]
Looks like your server was about to crash which shutdown the async lighting thread causing the java.util.concurrent.RejectedExecutionException. 

According to your logs, the culprit seems to be caused by the BlockDropItemsPhaseState which apparently is not ending properly. Can you try disabling the causetracker verbose logging as a temporary workaround in sponge's global.conf to see if that helps the issue?

**Comment by mkrtes** [comment]
Maybe I have the same problem. https://pastebin.com/pbuRJpAx
Massive error flood in console after start world generation.

**Comment by P3rf3ctXZer0** [comment]
@bloodmc I already did that and yes it works as a work around.
