### ISSUE TITLE
PREINIT Crash

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1473]
i was using forge 2285, but same thing happens with forge 2282. in logs, it says this:
[fml-client-latest.txt](https://github.com/SpongePowered/SpongeForge/files/966333/fml-client-latest.txt)
it says an another coremod loaded the blabla class before sponge blabla.
please help, thanks...

**Comment by ghost** [comment]
and if anyone can let me know what mod causes this bug, i can report this issue to that mods github. thanks..
edit: ok it's not about that mod, sponge should fix it

**Comment by kenijey** [comment]
and if it's not possible to detect the mod in logs, please let me know it to i test all mods to define which mod causes this problem. i'm not testing it right now because it takes billions of hours...

**Comment by gabizou** [comment]
[ServerPropertiesLAN](https://github.com/eileen12/MinecraftForge-Mods-ServerPropertiesLAN/blob/master/src/main/java/JaideepSinghHeer/Minecraft/mod/ServerPropertiesLAN.java) is doing a lot of class loading far too early before Sponge is being loaded.

Borrowing @simon816's explanation from [AppliedEnergistics2 issue](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2482#issuecomment-297527730):

> I'm sure it's been explained already, but just to reiterate, AE2's AppEngCore (the coremod) is loading DummyModContainer.
Now, coremods must be loaded in the root classloader (AppClassLoader).
All normal mod code (as well as Minecraft code) must go through the LaunchClassLoader so that coremods get a chance to apply bytecode transformations.
DummyModContainer is a non-coremod component and therefore should be classloaded through LaunchClassLoader.
We can see the problem here, AppEngCore is forcing DummyModContainer to be loaded through AppClassLoader.
> You may say "This isn't an issue with AE2, look, it doesn't happen with just Forge"
> Just because Forge doesn't give an error it doesn't mean the mod is behaving in a mod compatible way.
> At this moment in time, Forge does not issue a warning when classes are loaded in the wrong class loader. However, this is a valid error condition because only coremod classes (and some core Forge classes) should be loaded directly with AppClassLoader.
This issue is not related to SpongeForge, no amount of changes to sponge's code would stop DummyModContainer getting loaded with AppClassLoader when AE2 is present.
SpongeForge has only highlighted this issue because it made the assumption that DummyModContainer was loaded with LaunchClassLoader.
> I'm not sure what else can be said on the issue, remember that it's not SpongeForge at fault here.
> Don't shoot the messenger.

That being said, the classes being classloaded far too early are as follows:
- MinecraftServer
- DummyModContainer
- Probably all the event classes included in there

I can go and write a PR to split the core mod and the mod container (as they should be separated), but I'm able to do so only as time permits.

**Comment by ghost** [comment]
so i should wait for you to write that?

**Comment by phit** [comment]
or remove the mod if you can

**Comment by ghost** [comment]
i can not remove that mod, sorry for that. :( or... give me 10 mins to decide this...

**Comment by jackytuutykcaj** [comment]
Or use a bootstrap as a work around

**Comment by parlough** [comment]
Yeah it may be worth a shot trying SpongeBootstrap for now: https://forums.spongepowered.org/t/spongebootstrap-fixes-ordering-issue-with-other-coremods/12275

I'm not sure it will work though.

**Comment by ghost** [comment]
just trying, i will let you know it work or not
edit: nah, didn't work.

**Comment by kenijey** [comment]
nah, didn't work.

**Comment by ghost** [comment]
but i really agree that if sponge splits the coremods-mod container, it would be much more stable for sponge.

**Comment by gabizou** [comment]
It's something you can open an issue with the mod developer to have them split up their code, referencing this issue with the reasoning I mentioned above, or of course wait for someone to write a PR to fix it.

**Comment by ghost** [comment]
okay i deleted that mod it's not a terrible problem for me anymore, but please look at my dedicated server crash issue :(

**Comment by yepidoodles** [comment]
@kenijey use this version server side
https://github.com/Stonebound/Applied-Energistics-2

**Comment by ghost** [comment]
what? applied energitics?

**Comment by yepidoodles** [comment]
It's a fork which works with SpongeForge servers, clients with the official version will work with it.

**Comment by ghost** [comment]
i still didn't understand anything, i think u sent me wrong link @yepidoodles

**Comment by yepidoodles** [comment]
On the readme of that fork is the downloads. Use that version of AE2 on your SpongeForge server, and use the Official version of AE2 for your modpack.

**Comment by ghost** [comment]
but i don't use AE2 in my modpack ?  still i didn't understand anything

**Comment by ghost** [comment]
lets go to the real issue
https://github.com/SpongePowered/SpongeForge/issues/1475

**Comment by yepidoodles** [comment]
Sorry, as [this issue](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2482) was mentioned, I assumed it was AE2 related. My bad.
