### ISSUE TITLE
Sponge tracking crashing server

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1474]
https://gist.github.com/xKnightGamingx/fa4989d5a4a9fa97219ce88e51c40e61- skyfactory log
https://gist.github.com/xKnightGamingx/b2a42d417de7369b53351022b9af1759 - Skyfactory crash

https://gist.github.com/xKnightGamingx/f0121d0d073675df8304693606978626 - Foolcraft log
https://gist.github.com/xKnightGamingx/c70f18b3ab811c07633b9519f1eb9b09 - Crash 1
https://gist.github.com/xKnightGamingx/ee027c4106e81143632afc688ceb9916 - Crash 2

**Comment by parlough** [comment]
Again, instead of the zip can you please paste the log on https://gist.github.com/

Then simply include any other relevant information about your server's environment within the issue. 

A downloadable ZIP is not an appropriate method for conveying this information.

**Edit:** By the way, your gist has an extra dash on the end, messing up the link.

**Comment by xKnightGamingx** [comment]
thing is its for two servers

**Comment by xKnightGamingx** [comment]
https://gist.github.com/xKnightGamingx/fa4989d5a4a9fa97219ce88e51c40e61- skyfactory log

**Comment by Meronat** [comment]
Then upload the logs for both.

**Comment by ghost** [comment]
updated

**Comment by phit** [comment]
none of the links work, no reproduction and generic title
please open a new issue if you still have this problem
