### ISSUE TITLE
Crash With Galacticraft(another)

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1481]
used sponge 2296 to 2298(tested all),
[crash-2017-05-02_10.48.01-server.txt](https://github.com/SpongePowered/SpongeForge/files/969750/crash-2017-05-02_10.48.01-server.txt)
 forge 2285

**Comment by kenijey** [comment]
i tested with sponge 2297 too, crashed again. here's that crash report
[crash-2017-05-02_10.03.04-server.txt](https://github.com/SpongePowered/SpongeForge/files/969657/crash-2017-05-02_10.03.04-server.txt)

**Comment by radfast** [comment]
There is an issue in Sponge where **on first time server start** it creates spawn areas for all dimensions added by Forge mods.  This spawn creation - for multiple dimensions - can take longer than 1 minute.  The default server time-out for a tick is set to 60000ms - that's 1 minute.

Our mod's wiki advises server owners to set the ```max-tick-time``` to a large number like 999999 for the first time server start.

It would be nice to have a solution which did not require that setting - for people who don't read the documentation ;)

I am looking for the bug in Sponge with Forge-registered dimensions and will make a PR if I find anything.  No promises, doesn't seem like high priority since there's a solution of just setting the ```max-tick-time```.
