### ISSUE TITLE
Beyond - Quantum Quarry issue

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#1501]
Hi all, recently quarries were fixed and all is working fine, except the main thing really.
The quarry only mines Cobblestone and Dirt.. and nothing else, if you put a filter upgrade on it, it just continues to mine blocks but not give anything but cobble or dirt.

This is happening on our Beyond server, not tested any other yet.

NOTE -  Have tried removing the ExtraUtils2 folder in config/sponge - Didn't help
Deleted the DIM folder from 'worlds' and that did not help either.

Sponge Forge
SpongeAPI: 5.2.0-SNAPSHOT-a26c654
SpongeForge: 1.10.2-2281-5.2.0-BETA-2315
Minecraft Forge: 12.18.3.2254

![2017-05-11_23 41 34](https://cloud.githubusercontent.com/assets/24898745/25975065/19cbd98c-36a4-11e7-9135-d7c90e2ccaa1.png)

**Comment by bloodmc** [comment]
@Keaton1188 I tested with 3 quantum quarries and received some blocks that weren't dirt/cobblestone. However most were but the same exact thing happened in SinglePlayer Forge without SpongeForge so the issue seems to be with the mod. 

https://github.com/rwtema/extrautilities/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20quarry

Many tickets already reported with mining blocks using the quantum quarry.

**Comment by FiveEYZ** [comment]
check what biome u are mining from cause this is what i get https://gyazo.com/1b287773695c0e74e8287e8ac22405f3

**Comment by bloodmc** [comment]
@FiveEYZ Thanks for info! So it is definitely working =) Report any mining output issues based on biomes here
https://github.com/rwtema/extrautilities/issues

Closing as this is not a SpongeForge issue.
