### ISSUE TITLE
1.11.2 Dupe without serverside mods

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeForge#1546]
- SpongeForge version: 1.11.2-2282-6.1.0-BETA-2352
- Forge version: tested with 13.20.0.2298 & 13.20.0.2309
- Plugins/Mods: none

Install JEI on the client! Drop/place/remove any single item from your inventory, its important the item stack size will be 0 after doing so. Click on the right side of your inventory, basically empty JEI space. The item that just left your inventory will be back.

This does not work without Sponge on the server. Probably related to [this](https://www.reddit.com/r/feedthebeast/comments/6bnc1h/psa_for_modders_on_1112_do_not_compare_your/)?

Quick video demonstration: https://phit.link/s/2017-05-28_04-46-40.mp4 
Serverlog, not that it would show anything http://vpaste.net/ZlvN3

**Comment by phit** [comment]
yeah something is really broken with inventories, you can also lose items in a similar way

1. Have an item, remove a couple either via dropping, chest, etc
2. Pick up item(s) again
3. Click empty space around JEI, inventory updates and reverts back to your inventory after step 1

pretty sure JEI is not even needed on the server for this, I'll test in a bit with SpongeVanilla too

**Comment by phit** [comment]
Tested with SpongeVanilla and it doesn't work, but it does work with just pure SpongeForge on the server no mods/plugins. You just need JEI for the reproduction on the client.

**Comment by dualspiral** [comment]
Actually, you don't need JEI at all. I replicated this on my client by just clicking outside the Inventory window.

It's because Sponge captures the changes in the inventory during item drop/pickup/place block, but doesn't clear these transactions. So, when you do a click event outside the window, which causes a drop event, Sponge cancels the transactions - which it has filled from these previous transactions that haven't been cleared. Therefore, it puts the original items back into the inventory, which causes the effect you're seeing.

The fix is to clear the transactions at the end of the handler for these actions, just about to push it now.
