### ISSUE TITLE
Recent Sponge Forge fails to register mod items

### ISSUE THREAD

**Issue by codeHusky** [SpongePowered/SpongeForge#1547]
The SF registry no longer allows you to get mod item item types, rejecting the IDs as invalid. Users can still /give themselves these items, but configs cannot load the items.

1.10.2-2123-6.0.0-BETA-1902
Pixelmon tested but any mod theoretically

**Comment by dualspiral** [comment]
That SF version is 6 months old - it was the last development build for API 6 on 1.10.2 before it was switched to target 1.11.2. You likely found it by selecting "experimental 1.10.2" on the downloads page.

Try it again on the latest stable 1.10.2 (API 5) and/or latest stable 1.11.2 (API 6).

**Comment by codeHusky** [comment]
@dualspiral I'm not entirely sure what exact version the tester was using when they ran into this issue, but they did tell me earlier that it was the latest version. That was just my guess.

**Comment by gabizou** [comment]
Again, need exact test code and build numbers that this failed with, the build that you mention is, as dual spiral said, six months old, after SEVERAL bug fixes, rewrites, refactors, and updates. I have personally tested the registry getting custom modded items after `GameStartServerEvent` which is when you should expect all items to be registered, attempting to get modded items before mods have a chance to complete their registrations is going to result in issues since you're not allowing those mods to finish those registrations.

**Comment by codeHusky** [comment]
https://github.com/codeHusky/HuskyCrates-Sponge/blob/master/src/main/java/pw/codehusky/huskycrates/HuskyCrates.java <-- Event
https://github.com/codeHusky/HuskyCrates-Sponge/blob/master/src/main/java/pw/codehusky/huskycrates/crate/config/CrateRewardHolderParser.java <-- Actual registry accessing code

I'm trying to get a build number from the tester and ill test it myself in a bit.

**Comment by codeHusky** [comment]
spongeforge-1.10.2-2281-5.2.0-BETA-2353

**Comment by codeHusky** [comment]
That's a version that's suffering from this issue

**Comment by Zidane** [comment]
1.10.2-2281-5.2.0-BETA-2379

This is the latest 1.10.2 build. Closing this as the tester needs to update to that build and try again.
