### ISSUE TITLE
[1.11.2] Terrain Gen Issue with ATG & Travel Huts

### ISSUE THREAD

**Issue by Urhas** [SpongePowered/SpongeForge#1549]
**I am currently running...**
- SpongeForge version: 6.1.0-BETA-2354
- Forge version: 2282
- Java version: Version 8 Update 131

- Operating System:
 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
  - [ ] macOS
- [x] Windows

- Plugins/Mods: 
Travel Hut Version: 2.0.7
Alternate Terrain Gen Version: 2.1.4

**What is the expected result?**
Travel Huts are to generate correctly with ATG world Gen Enabled
![image](https://cloud.githubusercontent.com/assets/8009682/26559447/9d4a46ca-44a7-11e7-970d-443702639575.png)

**What is the current result?**
Travel huts are generating twice and stacking on top of each other
![image](https://cloud.githubusercontent.com/assets/8009682/26559469/c79b1062-44a7-11e7-9703-a87cd44298c3.png)

[Logs.zip](https://github.com/SpongePowered/SpongeForge/files/1036466/Logs.zip)

**Comment by Urhas** [comment]
This is only occurring when ATG-Alternate terrain gen is selected in in the World Type options

**Comment by Zidane** [comment]
@Deamon5550 

Take a look into this please.

**Comment by phit** [comment]
Closing this issue, as of today 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please reply here and I'll reopen this issue..
