### ISSUE TITLE
Weather 2 mod storms not forming

### ISSUE THREAD

**Issue by Scratchman** [SpongePowered/SpongeForge#1600]
**I am currently running...**
- SpongeForge version:  spongeforge-1.10.2-2281-5.2.0-BETA-2379
- Forge version: forge-1.10.2-12.18.3.2297-universal
- Java version: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_131
- Operating System: Ubuntu Linux 16.04.2

 - [ x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

Yeah, tried that and got kicked from the server.
- Plugins/Mods: 
  [modslist](http://www.modlister.com/server/ImagineScape)

**What is the expected result?**
I expected the [weather 2 mod](http://coros.us/mods/weather2) to act the same as it does on a plain forge server or even like it did in 1.7.10 when we were a cauldron server.

**What is the current result?**
With our current settings for the weather mod it would usually form a storm on the server once every few hours, but i have been on the server 4 hours a day for the last week and have not had more than rain. I've asked other players, that are on the server regularly, if they have had a storm and they all say they can't remember one forming within the last week. We had been testing our server as just a plain forge server up until about a week ago, with storms regularly forming, but then decided to add sponge to take advantage of all the server side plugins and since adding sponge we haven't had a storm from the weather 2 mod form.

[fml-server-latest.zip](https://github.com/SpongePowered/SpongeForge/files/1096345/fml-server-latest.zip)

**Comment by gigafunk** [comment]
Theres settings in the weather mod to just follow vanillanserver rules for rain or its own weather. Have you messed with those? Just a suggesting I am not with sponge, just a lurker...

**Comment by gabizou** [comment]
Closing this issue, as of today 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please [open a new issue](https://github.com/SpongePowered/SpongeForge/issues/new) with updated information.
