### ISSUE TITLE
ASM Transformer compatibility issue

### ISSUE THREAD

**Issue by CreativeMD** [SpongePowered/SpongeForge#1609]
Hey there,
unfortunately I have found an issue between my mod (CreativeCore) and SpongeForge.

**What CreativeCore changes**

It modifies `net.minecraft.world.World.updateEntities();` ...

Original code:
```java
this.theProfiler.startSection(tileentity.getClass().getSimpleName());
((ITickable)tileentity).update();
this.theProfiler.endSection();
```
Result code:
```java
this.theProfiler.startSection(tileentity.getClass().getSimpleName());
if(tileentity instanceof ICustomTickable && !((ICustomTickable) tileentity).shouldTick())
    iterator.remove();
else
    ((ITickable)tileentity).update();
this.theProfiler.endSection();
```

**The issue**
Sponge seems to overwrite this change. I don't know exactly what happens, but shouldTick() will never be called. There is no crash or what so ever.

I already tried a lot of things, but no matter how I implement my changes, it doesn't work out. Maybe you have an idea what could be the issue?

My code: https://github.com/CreativeMD/CreativeCore/blob/1.11/src/main/java/com/creativemd/creativecore/core/CreativeCoreTransformer.java#L138

**I am currently running...**

- SpongeForge version: 1.11.2-2282-7.0.0-BETA-2376
- Forge version: 13.20.0.2366
- Java version: jre1.8.0_121 64 bit
- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

In Regards
CreativeMD

**Comment by gabizou** [comment]
Just so you're aware and so I can shed some light to the situation, Sponge *does* overwrite the entirety of the `World.updateEntities` method [with the following](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/world/MixinWorld.java#L142). The main reason for all of the overwrites is so that Sponge can effectively perform various tracking operations to throw events for plugins (and in the case of SpongeForge, mods). 

At this very moment, I don't have a solution for you, except for inlining your removal into the `ICustomTickable#update()` such that it will perform it's own checks whether it should tick. Likewise, the original plan to have the tile entity removed from the iterator is awkward, but you could have a "when tick is called, flip a boolean to return `true` for the instance with `tile.isInvalid()` etc.

With the suggestion above, you wouldn't actually need a transformer at all.

**Comment by CreativeMD** [comment]
I need it for LittleTiles. Unfortunately all tileentities implementing the interface ITickable will tick automatically. Most LittleTile blocks don't need to tick, but some do. If you build a lot stuff with LittleTiles, this can affect performance. In my world have about 30,000 blocks, which have to be iterated every tick. So this code should remove all tileentities which don't need to tick from the list.

If a tileentity is invalid it will be removed completely, I only need to remove it from `tickableTileEntities`.

Can i apply those changes to your MixinWorld.class?

**Comment by CreativeMD** [comment]
Ok, it seems like i can transform updateEntities() in your MixingWorld class. Unfortunately it messes it up afterwards. My code won't be removed completely, but it is not working properly anymore.

I guess you don't really like the idea of adding a hook or something similar for it ... so there is nothing i can do from my end.

If you have a different idea just let me know.

**Comment by CreativeMD** [comment]
I could find a better solution for this, without ASM transforming. Thanks for you help anyway.
