### ISSUE TITLE
Sponge cancelling Actually Additions manual right click on machines

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1610]
Actually Additions has an manual (in-game wiki thing) which has a trick of while holding it, shift-right click any machine from the mod will open it's manual page:

![img](https://image.prntscr.com/image/SgTjgOleTSq-r_va7Wqxtg.png)

The mod cancels the right click event (to the machine) and proccess the logic of the book, opening it. However, looks like Sponge is closing the GUI just after it is opened, so we are unable to use this trick. 

*I don't think versions matter here, I tested on latest 1.11.2 and 1.10.2 SF atm and still reproduceable...*

**Comment by Zidane** [comment]
This will be an issue with Sponge because we send a GUI close when cancelling interaction to fix the fact that interacting something like a CommandBlock is handled on the client so without sending a gui close it would never close.

@SpongePowered/developers Thoughts? Fixing this would re-introduce what this was meant to fix to begin with.

**Comment by bloodmc** [comment]
The mod is violating the event contract by cancelling yet still running the item use hook. It should be setting block use to false in the event.

https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/event/entity/player/PlayerInteractEvent.java#L183
