### ISSUE TITLE
Crash server 10.2

### ISSUE THREAD

**Issue by PixelmonPRO** [SpongePowered/SpongeForge#1645]
Hello! Server crash(

Java 8
Operating System: Debian 8 Jessie 64 bit
SpongeForce: spongeforge-1.10.2-2281-5.2.0-BETA-2433

**Comment by PixelmonPRO** [comment]
and crast again: https://pastebin.com/9SGftjJg

**Comment by brunyman** [comment]
Have you find the cause of this? I'm having the same type of crash.

**Comment by Zidane** [comment]
Looks like when LuckPerms is performing some code (likely a db lookup), it is hanging:


    at me.lucko.luckperms.sponge.service.proxy.SubjectProxy.getActiveContexts(SubjectProxy.java:165)

Report to the plugin's issue tracker.

**Comment by lucko** [comment]
The first crash has no trace containing a LuckPerms call, so I don't really see how it is related.

`#getActiveContexts` only calls the registered context calculators on the server, no db lookups.

You're also running old versions of Sponge and LP.

**Comment by PixelmonPRO** [comment]
@lucko i update last LP, and Sponge 1.10.2-2281-5.2.0-BETA-2464
https://gist.github.com/PixelmonPRO/06c9003d04d8802d96bdb05ae8fc644e

**Comment by lucko** [comment]
It's getting stuck on the call to load the Subject for the player. (as this is being called on the main thread)

For online players, this shouldn't be an issue, but offline players aren't loaded until they're needed.

Only a "reference" is kept until a method is called on the player, which is why the data is only being loaded when the getActiveContexts method is called.

https://github.com/lucko/LuckPerms/blob/master/sponge/sponge-service-api6/src/main/java/me/lucko/luckperms/sponge/service/proxy/api6/SubjectProxy.java#L165

It's not really a bug in LP, as the behaviour is intended.

Related:
https://github.com/SpongePowered/SpongeAPI/pull/1524

**Comment by PixelmonPRO** [comment]
@Zidane How fix this problem?
