### ISSUE TITLE
[1.12] Quark is incompatible with SpongeForge

### ISSUE THREAD

**Issue by polyzium** [SpongePowered/SpongeForge#1646]
Running Quark together with SpongeForge results in a crash.
I reported [this](https://github.com/Vazkii/Quark/issues/535) to Quark repo itself then Vazkii said to report it here.

**I am currently running...**

- SpongeForge version: 1.12-2368-7.0.0-BETA-2425
- Forge version: 1.12-14.21.1.2406
- Java version: 1.8.0_131
- Operating System: Arch Linux with kernel 4.9.34-1-lts

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
Quark-r1.2-101

**What is the expected result?**
A SpongeForge server running with Quark

**What is the current result?**
Server crashes when both SpongeForge and Quark are installed

Log: [fml-server-latest.log](https://clbin.com/CtFfj)

**Comment by Mumfrey** [comment]
Looking at the transformer source, it *seems* like Quark is wholesale replacing the method body with a call to a custom method. The Sponge mixin is trying to redirect the individual calls to `isPlayerFullyAsleep` which exist in the target method but is of course failing because the instructions don't exist any more.

There are probably better ways that Quark could achieve the same thing, ultimately it's calling [this method](https://github.com/Vazkii/Quark/blob/cce4855cf87f413754b71d6490a63b917815e3d1/src/main/java/vazkii/quark/tweaks/feature/ImprovedSleeping.java#L70) which doesn't even seem to do anything if the feature is disabled, so gutting the method entirely seems a bit overboard.

A better behaviour on quark's end would be to change the transformer to instead inject the following at the head of the method:

```
INVOKESTATIC  ASM_HOOKS  isEveryoneAsleep  (Lnet/minecraft/world/World;)I
DUP
IFEQ L1
ICONST_1
ISUB
IRETURN
L1
```

and then simply have `ImprovedSleeping::isEveryoneAsleep` return an `int` 0 for vanilla behaviour, 1 for `false` and 2 for `true` and then get rid of `ImprovedSleeping::vanillaCheck` because then the vanilla check actually runs in the vanilla code, with Sponge's (and of course anyone else's) modifications in place.

This would be the equivalent behaviour of a *cancellable short-circuit* injection in Mixin.

**Comment by bookerthegeek** [comment]
@Vazkii

**Comment by Zidane** [comment]
I'm closing this as we cannot support mods who fully replace method code like this. As @Mumfrey has pointed out, there are far better ways the mod author can achieve what he wants to achieve.
