### ISSUE TITLE
[1.10.2] Server spam after remove the plugin

### ISSUE THREAD

**Issue by linkinkov** [SpongePowered/SpongeForge#1649]
**I am currently running...**
- SpongeForge version: latest for 1.10.2
- Java version:  8
- Operating System: debian

- Plugins/Mods: 
http://i.imgur.com/rexBNc3.png

**What is the expected result?**
https://gist.github.com/linkinkov/e2d6354e493a2e897c400c38266b1813

**Comment by ryantheleach** [comment]
I can understand that the spam is annoying and can fill logs.

Maybe we could reduce the amount of lines printed, / lower it from ERROR?

A fix for this would probably be centered around the following Enhancement: https://github.com/SpongePowered/SpongeCommon/issues/448

**Comment by linkinkov** [comment]
problem with spam then its crash the server with GC error.

**Comment by gabizou** [comment]
@ryantheleach this was resolved in API 6 with the inclusion of the new DataRegistration stuff. Granted a stopgap of translation errors can be muted and avoided, I have not considered it quite necessary to back port the entire system in place to 1.10.2 as it had not presented itself necessary to do so at the time. Since it only affects the custom data being removed per custom data holder being loaded, it shouldn't really affect the server after the first few entities or tile entities are loaded without the custom data.

**Comment by linkinkov** [comment]
@gabizou can you backport this to 1.10.2 branch? Because now my server crashed with GC error.

**Comment by linkinkov** [comment]
Also how i can fix this:
https://gist.github.com/linkinkov/a84a83893eeef17e6e2364540cfc22f6

**Comment by Zidane** [comment]
@linkinkov 

In the future, do not piggy back issues on other issues. I'll be nice and allow it this time. For your current reply, not a Sponge issue:

[16:28:14] [Server thread/ERROR] [Sponge/]: /* java.lang.ClassCastException: com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityBerryTree cannot be cast to com.pixelmonmod.pixelmon.blocks.tileEntities.TileEntityApricornTree */
[16:28:14] [Server thread/ERROR] [Sponge/]: /*     com.pixelmonmod.pixelmon.blocks.apricornTrees.BlockApricornTree.func_180639_a(BlockApricornTree.java:208)  

Pixelmon issue.

**Comment by linkinkov** [comment]
@Zidane sorry for my mistake. Thank you for reply.

But, how about spam issue?

**Comment by Zidane** [comment]
The DataRegistration system will not be backported to 1.10.2 as it is a break. As @gabizou said, once the data fails to load for entities, the spam will go away.
