### ISSUE TITLE
Player not accepting BungeeCord messaging channel

### ISSUE THREAD

**Issue by Rob5Underscores-zz** [SpongePowered/SpongeForge#1677]
**I am currently running...**

- SpongeForge version: 5.2.0 (Running 1.10.2 modpacks -> this testing is done WITHOUT other mods)
- Forge version: 2281
- Java version: 1.8.0_131
- Operating System:
 - [x] Linux (Debian 8)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, FastAsyncWorldEdit, WorldEdit, PistonSponge (plugin with error)

**What is the expected result?**
A plugin message is sent.

**What is the current result?**
The player has not accepted the BungeeCord messaging channel and the event returns.
https://github.com/SpongePowered/SpongeForge/blob/71b94055b695b6cb35cf85d54cf4c8a6fcdccee6/src/main/java/org/spongepowered/mod/network/SpongeModChannelBinding.java
(Line 64-66)

BungeePluginMessenger Class: https://hastebin.com/cisexexubi.java
This class is constructed in the GameServerStartedEvent
Log: https://hastebin.com/etunarumig.sql
The log includes my obnoxious debug messages.

**Comment by bloodmc** [comment]
@dualspiral You able to take a look at this?

**Comment by Rob5Underscores-zz** [comment]
Following a tip left here: https://forums.spongepowered.org/t/sponge-bungee/18904/7

This error only occurs when ip forwarding is enabled. If it is disabled (on Bungee and Sponge), this works perfectly..

Given that people tend to generally enable this setting (?), I would suggest that there is still flaw in my implementation of the messaging channels that stop it working when ip forwarding is enabled.

@dualspiral @bloodmc 

Thanks

EDIT: I guess this one is down to me, I had removed SpongePls. 
RE-EDIT: I take it back, adding SpongePls does not resolve this.

**Comment by Rob5Underscores-zz** [comment]
Final update for now.

Was struggling for a while trying to work out why switching everything to offline-mode/no ip-forwarding wasn't working. (I had switched clients between testing sessions).

The messaging works fine in the following configurations;
Using a forge client + SpongePls.
Using a forge client + all offline/no ip-forwarding.

I was unable to get messaging to work with Vanilla clients at all (perhaps I should've been using SpongeVanilla). In any case, I would appreciate any clarification: is there any reason why vanilla clients should be unable to send plugin messages on SpongeForge servers?

**Comment by dualspiral** [comment]
I have had zero time to look at this this weekend due to personal commitments, but I bet this is a Bungee problem. Have you tried with Waterfall? Unfortunately, I don’t think we’re going to get any fixes in with stock Bungee.

Basically, what I get from your testing is that the client type matters. This makes sense, because Bungee does different things based on the client it detects.

I think what’s going on is that the `REGISTER` messages are only being sent if the client is a Forge client, which will include both the BungeeCord channel and any channels that the client is already listening for. I remember writing that in. However, I suspect that if the client is vanilla, register messages are just not being sent.

There are two solutions if this _doesn’t_ work with Waterfall (if I’m right, this is something I’d need to test with a proper setup and test plugins):

* We add special `BungeeCord` channel handling in the implementation if the BungeeCord module is turned on - would solve it for all BungeeCord proxies but I have my doubts about this special treatment - the whole point of these REGISTER messages is that the server knows what to listen to/send on.
* We try (or someone else does) to fix it in Waterfall, at least, who are willing to take on Sponge/Forge compatibility patches, and fix these packets not being sent properly on Vanilla.

Purist in me says we should just push it to the proxy software to fix - option 2 - because option 1 is really only a workaround to a bug in other software (if I’m right).

**Comment by Rob5Underscores-zz** [comment]
@dualspiral 
Thanks for your response. This is essentially resolved for me as I only intend for Forge clients to be used but I imagine this could crop up for someone else in another situation - especially when testing plugins, etc.

I tried using Waterfall and HexagonMC with the vanilla client to no avail.

**Comment by dualspiral** [comment]
After sleeping on it, I realised that there is potentially another reason why this might not work, that Forge doesn't register channels for a non-Forge client, in which case, this is likely a Forge problem. I suspect this is much less likely, but I wanted to make a note of it, just in case.

I need to test this with SV as well before jumping to conclusions.

**Comment by dualspiral** [comment]
So, I wrote a quick set of Mixins to check what's going on: https://gist.github.com/dualspiral/8a1f2bea89d1bf2d07eb599caed74571. The idea behind them was to check `REGISTER` packets at two stages:

* When packets are received by Netty and read (READ)
* When FML/Forge handles the packets (REGISTER)

All I do is log the contents of the packet to the log. I don't do anything fancy!

*With Forge behind Waterfall*

```
[20:28:37] [Netty Epoll Server IO #3/INFO] [FML]: Client protocol version 2
[20:28:37] [Netty Epoll Server IO #3/INFO] [FML]: Client attempting to join with 5 mods : minecraft@1.12.1,mercurius_updater@1.0,FML@8.0.99.99,forge@14.22.0.2444,mcp@9.19
[20:28:37] [Netty Epoll Server IO #3/INFO] [FML]: Attempting connection with missing mods [spongeapi, sponge, luckperms, nucleus] at CLIENT
[20:28:37] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[20:28:37] [Netty Epoll Server IO #3/INFO] [STDOUT]: [net.minecraft.network.play.client.CPacketCustomPayload:handler$onRead$zoe000:527]: READ:FMLFML|HSFORGEBungeeCord
[20:28:37] [Netty Epoll Server IO #3/INFO] [STDOUT]: [net.minecraftforge.fml.common.network.handshake.NetworkDispatcher:handler$injectServerSiderCustomPacket$zod000:689]: REGISTER:FMLFML|HSFORGEBungeeCord
[20:28:37] [Netty Epoll Server IO #3/INFO] [STDOUT]: [net.minecraft.network.play.client.CPacketCustomPayload:handler$onRead$zoe000:527]: READ:FML|HSFMLFML|MPFMLFORGE
[20:28:37] [Netty Epoll Server IO #3/INFO] [STDOUT]: [net.minecraftforge.fml.common.network.handshake.NetworkDispatcher:handler$injectServerSiderCustomPacket$zod000:689]: REGISTER:FML|HSFMLFML|MPFMLFORGE
[20:28:37] [Server thread/INFO]: dualspiral[/127.0.0.1:53231] logged in with entity id 155 in world(0) at (-48.30000001192093, 71.0, 377.69999998807907)
```

*Without Forge, still behind Waterfall*

```
[20:29:02] [Server thread/INFO] [FML]: Connection received without FML marker, assuming vanilla.
[20:29:02] [Server thread/INFO] [FML]: [Server thread] Server side vanilla connection established
[20:29:02] [Netty Epoll Server IO #7/INFO] [STDOUT]: [net.minecraft.network.play.client.CPacketCustomPayload:handler$onRead$zoe000:527]: READ:FMLFML|HSFORGEBungeeCord
[20:29:02] [Server thread/INFO]: dualspiral[/127.0.0.1:60625] logged in with entity id 156 in world(0) at (-48.30000001192093, 71.0, 377.69999998807907)
[20:29:02] [Server thread/INFO]: dualspiral joined the game
[20:29:02] [Server thread/INFO] [FML]: Opening channel which already seems to have a state set. This is a vanilla connection. Handshake handler will stop now
```

What's striking is that Waterfall actually _is_ sending the `REGISTER` packet correctly (see the `READ` line). Forge/FML is _not_ registering it, however. So, this is beginning to look like either a Forge issue or something that Sponge has incorrectly touched. Which it is as of yet, I do not know, and would have to investigate more.

I guess the acid test would be if an SF server running behind Waterfall running WECUI _as a LiteLoader mod_ on the client + GP on the server works as expected.

**Comment by dualspiral** [comment]
It's hard to say who is really at fault here - Bungee could be sending the REGISTER packet too early, or FML isn't listening for it early enough. However, I can solve this by moving [this line in FML](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/common/network/handshake/NetworkDispatcher.java#L163) to above the `completeServerSideConnection` method. 

The act of the player entity joining the server (facilitated by the `completeServerSideConnection` method) causes Bungee to fire the register packet in question - which generally isn't captured by FML properly because their `NetworkDispatcher` has not been inserted into the Netty pipeline at that point, and as the Netty handler is async, gets read before FML has had time to put itself into a position to intercept it. So, by inserting into the channel before telling the player to login, FML can capture this `REGISTER` message during login.

I used the following mixin to test this:

```java
@Mixin(value = NetworkDispatcher.class, remap = false)
public abstract class RegisterMixin {

    @Shadow private void insertIntoChannel() {}

    @Inject(method = "serverToClientHandshake", at = @At(value = "INVOKE",
            target = "Lnet/minecraftforge/fml/common/network/handshake/NetworkDispatcher;completeServerSideConnection"
                    + "(Lnet/minecraftforge/fml/common/network/handshake/NetworkDispatcher$ConnectionType;)V", shift = At.Shift.BEFORE))
    private void onVanillaStartHandshake(EntityPlayerMP player, CallbackInfo ci) {
        insertIntoChannel();
    }

    @Inject(method = "serverToClientHandshake", at = @At(value = "INVOKE", shift = At.Shift.AFTER,
            target = "Lnet/minecraftforge/fml/common/network/handshake/NetworkDispatcher;completeServerSideConnection"
                    + "(Lnet/minecraftforge/fml/common/network/handshake/NetworkDispatcher$ConnectionType;)V"), cancellable = true)
    private void onCompletedServerSideConnection(EntityPlayerMP playerMP, CallbackInfo ci) {
        ci.cancel();
    }
}
```

...but I expect that this should really be something the Forge guys should fix, just in case there is a reason for the ordering of these methods.

**Comment by BrainStone** [comment]
I'm having the same issue. has this been reported on Forge?

**Comment by BrainStone** [comment]
@dualspiral would you mind to report it on Forge, so it can be fixed? I think you have the most insight in this problem.

**Comment by dualspiral** [comment]
As communicated to you previously, @BrainStone, I'm gonna get you to test a mixin plugin to make sure my fix is right - I think it'll work, but I may have missed something, previous conversations with a couple of others makes me think there is something else underlying that may need to be fixed too (just have had no time or test code, really, to test it with).

**Comment by dualspiral** [comment]
@BrainStone 

I've written a plugin for 1.12.1 (bleeding) that should test my theory, above. Could you give it a whirl, check whether it works? [mixin-1677.zip](https://github.com/SpongePowered/SpongeForge/files/1275364/mixin-1677.zip)

Thanks.

**Comment by BrainStone** [comment]
@dualspiral It works. So your theory appears to be correct.
