### ISSUE TITLE
[1.10.2] SpongeForge Crashes Modded Server As Soon As Its Joinable

### ISSUE THREAD

**Issue by RogueRaiden** [SpongePowered/SpongeForge#1708]
My server loads all the way to the end, right about to the point where its joinable and then crashes.
I'm running All The Mods for Minecraft 1.10.2 and we've been playing on the server for a while. I have a testing server where I have the same version of ATM running but with a new world and Sponge runs just fine without crashes. But when I try to add it to the main server it causes the crash. I have logs from right after it crashed if needed. I will provide the crash log now though.

Running:
SpongeBootstrap-0.3.0
spongeforge-1.10.2-2281-5.2.0-BETA-2464
forge-1.10.2-12.18.3.2422-universal
Modpack: "All The Mods" v3.01
[crash-2017-08-10_05.40.28-server.txt](https://github.com/SpongePowered/SpongeForge/files/1213752/crash-2017-08-10_05.40.28-server.txt)

**Comment by RogueRaiden** [comment]
According to the crashlog, it says something about the MineFactory Reloaded Grinder. So I went into my test server and placed down the Grinder, and it instantly crashed the server with the same error.
Not sure if a Sponge problem or a MFR problem.

**Comment by Zidane** [comment]
@EZKatnipz Sponge is only in the log trace as we inject up the tree a bit. Not seeing any Sponge issue here.

**Comment by RogueRaiden** [comment]
The issue only exists when Sponge is installed, the machines causing the crashes can be placed just fine without sponge installed. The crash only happens when those machines are placed, and it totally crashes the server, and immediately crashes the server again if the machines exist anywhere in the world.

**Comment by gabizou** [comment]
From the crash report:
```
java.lang.VerifyError: Bad access to protected data in invokevirtual
Exception Details:
  Location:
    cofh/asmhooks/world/WorldServerProxy.func_147456_g()V @4: invokevirtual
  Reason:
    Type 'net/minecraft/world/WorldServer' (current frame, stack[0]) is not assignable to 'cofh/asmhooks/world/WorldServerProxy'
  Current Frame:
    bci: @4
    flags: { }
    locals: { 'cofh/asmhooks/world/WorldServerProxy' }
    stack: { 'net/minecraft/world/WorldServer' }

```
It screams that there's a transformer issue at hand. Not sure what the output of the actual byte code is, but I cannot confirm nor deny that this is potentially a sponge issue. If you can export the full classes with the two flags:
`-Dlegacy.debugClassLoading=true -Dlegacy.debugClassLoadingSave=true`, there's a `CLASSLOADER_TEMP` folder with all class loaded class at the end. if you can zip that up and provide it to us, we can potentially verify whether sponge or something else is interfering with the classes. Likewise, a full log would be helpful instead of just the crash report.
