### ISSUE TITLE
Galacticraft inventory being disregarded

### ISSUE THREAD

**Issue by hugeblank** [SpongePowered/SpongeForge#1742]
**The Issue**
I am setting up a server with a focus around the mod galacticraft. Now this mod is notorious as it is for being [broken by sponge](https://github.com/SpongePowered/SpongeForge/issues/1591), and I just found another one of those breakages. I have keepInventory enabled on my server, so that when a player dies, all hope isn't completely lost. The only problem is the players items in the galacticraft tab of their inventory disappear. No, not dropped on the ground, they just disappear. 

**I am currently running...**

All valid information can be found [here](https://kaos-network.com/servers/sonarx), on our servers website including server details, and plugin list (scroll down a bit, it's there.)
- Operating System:
Ubuntu Server

**What is the expected result?**
The galacticraft inventory tab gets restored just like the vanilla inventory.
**What is the current result?**
Everything in the galacticraft tab of the players inventory is lost.

**Comment by stephan-gh** [comment]
Explanation for this issue (feel free to ping the Galacticraft developers about this):

The reason this is broken is that Galacticraft attempts to replace `EntityPlayerMP` with a custom class `GCEntityPlayerMP` at runtime, which seems to be used to copy the inventory after the player has died (among other things). That's just asking for trouble with other mods because obviously only a single mod can do this change.

Most of the things in that class should be either handled using Forge events (e.g. the inventory can be copied in `PlayerEvent.Clone`), or - if really necessary - by transforming the methods in `EntityPlayerMP` directly. The other option is to find a solution to inject your custom player class in our [`@Overwrite` to `recreatePlayerEntity`](https://github.com/SpongePowered/SpongeCommon/blob/stable-6/src/main/java/org/spongepowered/common/mixin/core/server/MixinPlayerList.java#L520) but again, this is just asking for trouble and could break various other stuff in Sponge.

We can't do much to fix this on our side because the changes in `recreatePlayerEntity` are necessary to implement various Sponge features.

**Comment by radfast** [comment]
Hi @Minecrell, I'm one of the Galacticraft devs.  Your comments on our detailed coding techniques are a bit misplaced.  Our mod offers the choice of using GCEntityPlayerMP, or if there are (very rare) compatibility issues with that then people can install **PlayerAPI** which provides additional EntityPlayerMP hooks, in which case Galacticraft will automatically not use its GCEntityPlayerMP.

@hugeblank I don't much like the tone of the original post here ... our mod is not "notorious for being broken by Sponge".  Our mod is a large, complex mod doing many advanced things, and therefore will show up bugs in SpongeForge which other, smaller mods will not see.  There's [one issue](https://github.com/SpongePowered/SpongeForge/issues/1552) which is likely manifesting multiple symptoms.  For now the solution is to use the [older version of Sponge we recommend ](https://wiki.micdoodle8.com/wiki/Sponge) which likely does not have those problems.  (**UPDATE: the _latest_ Sponge has fixed it, yay.**)

If there are issues with Galacticraft and a SpongeForge version which our documentation says we are compatible with, then please open them as issues on our Galacticraft issue tracker, not here, and then we can look at doing something to fix them.

@Minecrell I suggest you close this.  If I identify any Sponge-specific problem here I'll comment again or open a more dev-oriented issue.

**Comment by stephan-gh** [comment]
> Hi @Minecrell, I'm one of the Galacticraft devs.  Your comments on our detailed coding techniques are a bit misplaced.  

I'm not sure why they're misplaced? Just trying to help to fix the issue, and it's rather hard to fix it in Sponge.

> Our mod offers the choice of using GCEntityPlayerMP, or if there are (very rare) compatibility issues with that then people can install PlayerAPI which provides additional EntityPlayerMP hooks, in which case Galacticraft will automatically not use its GCEntityPlayerMP.

I'm pretty sure PlayerAPI doesn't work properly with Sponge (which is an entirely different issue and unrelated here). The problem with extending `EntityPlayerMP` is that only **a single mod can do this**. It will usually not cause any compatibility issue with other mods except if they're trying to do the same thing (which is exactly the reason why you shouldn't do it.)

Since the changes you make to `EntityPlayerMP` are rather minor, you could just transform the methods in `EntityPlayerMP` to add the necessary changes.

**Comment by radfast** [comment]
It would be a good idea to get Sponge working with PlayerAPI, as a lot of Forge mods (10+ mods) rely on that for mutual compatibility, and also RenderPlayerAPI clientside but that's probably not of so much interest to Sponge ...

**Comment by phit** [comment]
In reference to PlayerAPI, nothing can be done on Sponge's end to support it.

https://github.com/SpongePowered/SpongeForge/issues/1659#issuecomment-316169095
https://github.com/SpongePowered/SpongeForge/issues/1721#issuecomment-322396990
https://github.com/SpongePowered/SpongeForge/issues/570

**Comment by hugeblank** [comment]
@radfast I think you misread my tone there, I wasn't by any means trying to insult GC; or sponge for that matter. Both are very large mods, like you said, that rely on a set of circumstances that are typically present. When combining both large mods, you get issues, and it happens. I was referring to previous issues that had been discussed in sponge's issue tracker and GC's tracker, there are multiple issues with combining sponge and galacticraft (less now, due to that update), that's a fact. And that fact was the point I was trying to get across with 'notorious for being broken by sponge', or simplified, has had issues with sponge in the past.

**Comment by bloodmc** [comment]
Closing as dev says it is now fixed. Create a new ticket if problem persists.
