### ISSUE TITLE
Latest Mystcraft and Sponge 1.11.2 results in crash

### ISSUE THREAD

**Issue by cuddylier** [SpongePowered/SpongeForge#1774]
- SpongeForge version: spongeforge-1.11.2-2476-6.1.0-BETA-2636
- Forge version: 2476
- Java version: 1.8.0_112
- Operating System: 
 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: https://pastebin.com/raw/UQrpni9v

**What is the expected result?**
Server doesn't crash
**What is the current result?**
Crash with this error: https://pastebin.com/raw/vtehmniQ

Full log: http://paste.ubuntu.com/25560402/

**Comment by phit** [comment]
Closing this issue, as of today 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please [open a new issue](https://github.com/SpongePowered/SpongeForge/issues/new) with updated information.
