### ISSUE TITLE
[1.10.2] TAIGA Mod - Tiberium Ore Explosion Causes Runaway Phase

### ISSUE THREAD

**Issue by CaptainSisko** [SpongePowered/SpongeForge#1777]
**I am currently running...**

- SpongeForge version: spongeforge-1.10.2-2277-5.2.0-BETA-2637
- Forge version: forge-1.10.2-12.18.3.2477-universal.jar
- Java version: 1.8.0_131
- Operating System: Ubuntu 16.04.3 LTS

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
All The Mods 1 (1.10.2)
https://hastebin.com/ehewigewix.py

**What is the expected result?**
The Tiberium Ore from the TAIGA mod has a chance to explode when mined. It should explode without any issues.

**What is the current result?**
When the ore explodes the console spits out a lot of sponge errors. The server process has to be killed in order to recover.

The errors are here
https://gist.github.com/CaptainSisko/8ab38c7fcd1093a5ce8c3a11f7045937

There is an old [Pull Request on the TAIGA github](https://github.com/TeamFRM/TAIGA/pull/123) that addresses this issue by adding a config option to disable the explosion all together. We are currently using [MastaC729's build](https://github.com/MastaC729/TAIGA) on our server as it has the option to disable the explosion, howerver it only disables the explosion via mining. If you detonate TNT next to the ore, the same issue occurs.

If this can be fixed on the sponge side of things i can go back to the original build and leave the explosions enabled.

**Comment by phit** [comment]
Closing this issue, as of today 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please [open a new issue](https://github.com/SpongePowered/SpongeForge/issues/new) with updated information.

**Comment by Jestingstud2020** [comment]
I found out that if the chunk is claimed then explosion damage would be canceled much like a creeper blowing up in claimed land.....also doing this allows you to get the crystals as well :)

**Comment by gabizou** [comment]
If you want to report a new issue, please use the new issue template, this is a two year old issue for an old version that is no longer supported, so you'll need to provide logs for any exceptions that are being printed to console.
