### ISSUE TITLE
[1.12.2] Latest SpongeForge seems to break Shipping Bin in Pam's Harvestcraft

### ISSUE THREAD

**Issue by kwpugh** [SpongePowered/SpongeForge#1801]
I am currently running...

SpongeForge version: spongeforge-1.12.2-2486-7.0.0-BETA-2684.jar
Forge version: forge-1.12.2-14.23.0.2494-installer.jar
Java version: 1.8 144
Operating System: Centos 7

Plugins/Mods:
Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, Lockette, LuckPerms, Nucleus

What is the expected result?
Placing items in the Shipping Bin from Pam's Harvestcraft and selecting the corresponding item should allow you to sell the item for emeralds.  Pressing the SELL button in the GUI causes the items to disappear and emeralds spawn in the player's inventory.

What is the current result?
The items you placed in the slot are taken but no emeralds are placed into player inventory.

I tried this without Spongeforge active and it worked as expected.

Short log with error: https://gist.github.com/kwpugh/f870e443e6b9de91ef197125fa5b43b7

Full log: https://gist.github.com/kwpugh/0c944630ca4b01c2fe1c64397c36b708

**Comment by Dockter** [comment]
Test this with the latest version of Forge and SpongeForge.  I had a similar issue with furnaces acting strange.  Forge: 2509 and SF: 2503 seemed to have solved the issue for me.

**Comment by kwpugh** [comment]
Tested with Forge 2512 and SpongeForge 2700, still no joy.

**Comment by gabizou** [comment]
@kwpugh A workaround is implemented in the latest build. Give it a few minutes to build from the latest commit. The problem is still going to be with Pam's Harvestcraft doing world operations off the main thread, in this case, spawning an entity off the main thread. The work around at the moment is that Sponge will "capture" the entity and still spawn said entity while on the main thread, but the exception will still be printed if verbose is enabled.

**Comment by kwpugh** [comment]
Thank you.
