### ISSUE TITLE
Cyclic Scepter - Dupe Bug 

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#1836]
Hi all, having a issue with the Cyclic Building Scepter.. (Sponge Dupe Bug)

**How to reproduce this:
Get a Cyclic Building Scepter, in the bottom left you'll see arrows etc, make sure its on the chest, right click, put any item in the purple square, hold shift and use the scroll wheel to set it on the square (Place block - normal) then just right click and it will keep placing the item. 

This does NOT happen on single player, only a server with Sponge. (On SP it just places 1 block)

Horizons 3 1.0.0

SpongeForge: 
Minecraft: 1.12.2
SpongeAPI: 7.0.0-SNAPSHOT-421703e
SpongeForge: 1.12.2-2503-7.0.0-BETA-2711
Minecraft Forge: 14.23.0.2515

**Comment by phit** [comment]
see https://github.com/PrinceOfAmber/Cyclic/issues/549

**Comment by dariusc93** [comment]
Oddly enough this can be reproduce in single player. Unsure how this is related to sponge.

**Comment by Keaton1188** [comment]
I was unable to reproduce this in SP, I'll test again.

**Comment by phit** [comment]
The reason this happens is because Sponge overrides `WorldServer#markChunkDirty` to use the tile it has been passed, while the Vanilla method never uses the tile. Cyclic is passing null as tile to `markChunkDirty`, usually this would just throw an NPE and not cause any major issues.

The problem is Cyclic's code to place blocks is in the same try catch, as the markChunklDirty call and they are assuming the block placement failed if there is any error, in this case the NPE. And since it assumes block placement failed, it just never decreases the stack size etc.

I also posted a proposed solution on Cyclic's end here, maybe some dev that's more knowledgeable can offer a better solution https://github.com/PrinceOfAmber/Cyclic/issues/549#issuecomment-343748800

**Comment by ryantheleach** [comment]
I accidentally made it in SpongeVanilla because I was a little rushed, but I think this would resolve it? 

https://gist.github.com/ryantheleach/f5c5ede5d3f2401784cdff5472defded
