### ISSUE TITLE
ProjectileSource implementations lacking

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeForge#184]
I haven't found anyone implement `ProjectileSource` into `EntityPlayer` and other sources. This needs some fixing in order to spawn projectiles correctly.

**Comment by Zidane** [comment]
@gabizou 

Has this been rectified?

**Comment by gabizou** [comment]
@Zidane I believe there are still issues with having some default `velocity` applied to projectiles when they're launched. It's something I've been meaning to resolve at some point but got caught up with the API >.>.

**Comment by simon816** [comment]
I'm taking a look at projectile source's again and I think the `lauchProjectile` method should return an Optional projectile because there are multiple cases where a projectile could fail to be launched.
I have made it [throw an exception](https://github.com/SpongePowered/SpongeCommon/commit/41ca432#diff-6bdb73ca8e3f612a09b73db110192b5cR343) in places where it could not be spawned but I think it would be better as an Optional.absent().
In the API, `UnknownProjectileSource` [returns null](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/projectile/source/UnknownProjectileSource.java#L38) which is definitely not right.

The other issue I'm facing is finding the default velocity of a projectile, used when the velocity is not specified. In vanilla it is not measured as a velocity and I don't know how we can convert it.

**Comment by Zidane** [comment]
@simon816 

Have you resolved this fully regarding default velocity?

**Comment by simon816** [comment]
It's been a while since I last looked at this. From what I remember, pretty much every vanilla projectile works slightly differently so it will be a manual task to find what the default values are.

**Comment by Zidane** [comment]
@simon816 

Get this finished up so projectiles will work properly :).

**Comment by Zidane** [comment]
@simon816 

Status update.

**Comment by simon816** [comment]
Just come back to working on it. It's not straight forward but I have got the basic projectiles firing from dispensers and some entities.

**Comment by simon816** [comment]
I think it's finished now, see https://github.com/SpongePowered/SpongeCommon/compare/feature/projectilesource
I will be pushing this to master if no-one has any issues with it
