### ISSUE TITLE
chunk-gc not working properly?

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/SpongeForge#1871]
I have the chunk-gc from sponge with the default settings enabled, this unloads the chunks frequently but something instantly loads those chunks again which causes the chunks to get loaded and unloaded repeatedly.
Disabling this to use the vanilla chunk-gc prevents this issue.

- I have `deny-chunk-requests` enabled so shouldn't sponge prevent those chunks from getting loaded again?
- How is the chunk-gc from sponge different to the vanilla one?

**I am currently running**

- SpongeForge version: spongeforge-1.10.2-2477-5.2.0-BETA-2691
- Forge version: 2477
- Java version: 1.8
- Operating System: Ubuntu

**Comment by phit** [comment]
Closing this issue, as of today 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please [open a new issue](https://github.com/SpongePowered/SpongeForge/issues/new) with updated information.
