### ISSUE TITLE
Forge + Sponge having issues

### ISSUE THREAD

**Issue by Raycoms** [SpongePowered/SpongeForge#1872]
**I am currently running**

- SpongeForge version:  spongeforge-1.12.2-2529-7.0.0-BETA-2741.jar
- Forge version: forge-1.12.2-14.23.0.2550-universal.jar (Also happening with 2529)
- Java version: OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
- Operating System: Linux (Redhat)

When generating chunks with BOP and spongeforge occasionally totally corrupted chunks appear.

Huge areas up to the size of 512 blocks are cut into water chunks.

![image](https://user-images.githubusercontent.com/6438347/33156009-895c25a8-cfed-11e7-8f5c-9fab848ea5dc.png)

**Comment by Raycoms** [comment]
This does not happen without sponge. And unfortunately the log doesn't say anything useful.

**Comment by ryantheleach** [comment]
I can't help but notice there are some islands in the bottom right of that 'ocean square', and would have expected multiple reports of this.

This smells like the seed changing or the random number generator being messed up in some form, and you are by chance getting ocean?

This also might be due to a potential theoretical difference between the biome generators between BOP and Sponge+BOP.

Does this happen with a fresh world just flying around in Sponge? or is this only reproducible with a world that has been partially generated without Sponge?

**Comment by Raycoms** [comment]
Happening in a completely new world.

**Comment by Dockter** [comment]
@Raycoms I ran into a similar issue today working with Structure generation and how Sponge registers its generators.  This PR solved my issue, perhaps it can help with yours.

https://github.com/SpongePowered/SpongeCommon/pull/1624

**Comment by ryantheleach** [comment]
@Dockter Are you thinking this is something to do with Ocean monuments?

**Comment by Dockter** [comment]
In my testing the changes I made was affecting structure creation only, I didn't have empty spots in the map.  That being said I am not privy to the inter-workings of BOP.

**Comment by phit** [comment]
@Raycoms please update to latest (2753+) and retest

**Comment by phit** [comment]
No reply in a week, closing this for now. If this is still an issue, then please reply with the information you have been asked for and I will reopen this issue.
