### ISSUE TITLE
Spamming and crash after a while

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1901]
I am running 
Forge 1.10.2 12.18.3.2511
Sponge 1.10.2-2477-5.2.0-BETA-2777
Java 8

 Plugins/Mods (38): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, B.A.S.E, Better Questing, Bookshelf, Buycraft, CatClearLag, Chameleon, Chisel, Clumps, CustomNPCs, Dark Roleplay Core, Dark Roleplay Medieval, EconomyLite, FastAsyncWorldEdit, Holograms, Inventory Sync, Iron Chest, LangSwitch, LuckPerms, NPC Integration, Nucleus, PlaceholderAPI, Nucleus Gluon, PaladiumServerTools, Example Mod, PalaMod, ProjectCore for SpongeAPI 5.x, ProjectPortals for SpongeAPI 5.x, WorldEdit, RedProtect, Standard Expansion, Storage Drawers, VoxelSniper

we have massive community and i think this appear when player crash on login

Server log from spaming can't give full log because size are more than 500mo
https://gist.github.com/terrainwax/cb9c9db9484e7de776693f482889ec68

**Comment by phit** [comment]
Closing this issue, as of today 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please [open a new issue](https://github.com/SpongePowered/SpongeForge/issues/new) with updated information.
