### ISSUE TITLE
Phase state error with EU2 Quarry

### ISSUE THREAD

**Issue by Tencao** [SpongePowered/SpongeForge#1902]
**I am currently running**
- SpongeForge version: 1.12.2-2555-7.0.0-BETA-2783
- Forge version: 14.23.1.2566
- Java version: 8
- Operating System: Windows

- Plugins/Mods:

**Issue Description**
When leaving the EU2 Quarry to run, it outputs a phase state error regarding getting chunks or generating chunks

Trace - https://paste.ee/r/DNjZC
Log - https://gist.github.com/Tencao/c9c42e2ae6afc1d12f9d46f9c5a75292

**Comment by LemADEC** [comment]
Anyway to disable the massive console spam that kill servers due to this bug?

**Comment by LemADEC** [comment]
Also to note, the CaptureBlockPos is not reporting actual coordinates in the PhaseContext, so we don't know where to look for the faulty block.

**Comment by gabizou** [comment]
The trace log doesn't appear to be showing the correct sponge forge version. There have been some spam log improvements made in more recent builds than the log shows. Re-test with the latest if you can please.

Otherwise I'm going to continue using what's based on the log, but this appears to be a mod sided bug as the NPE is from the mod accessing a method on a `null` object, but I'm not sure the proper versioning required to reproduce in comparison to what is publicly available on github.

**Comment by LemADEC** [comment]
I've disabled the quarry and updated forge/sponge, still getting a single error:
https://gist.github.com/LemADEC/4b6f984bacdf1725d76b7f33f102c7c3

**Comment by LemADEC** [comment]
Same setup before disabling that quarry with constant spam:
https://gist.github.com/LemADEC/88db98a0a3d3b3a5d1629f799cf2893d

**Comment by JoccE0** [comment]
With Forge 2573 and Sponge 2831 this is fixed, the quarry now works for me.
