### ISSUE TITLE
SpongeForge 1.8.9?

### ISSUE THREAD

**Issue by flawnn** [SpongePowered/SpongeForge#1914]
Hey,
I want to use SpongeForge with 1.8.9. Isn't it available?  And is there a way to do it?

Greetings
Flawn

**Comment by phit** [comment]
http://files.minecraftforge.net/maven/org/spongepowered/spongeforge/index_1.8.9.html

**Comment by flawnn** [comment]
How can i make now Mods with it? @phit

**Comment by phit** [comment]
what?

**Comment by flawnn** [comment]
Like developing Mods with SpongeForge 1.8.9.... Or didn't i get the way how to @phit

**Comment by flawnn** [comment]
How do i use that? @phit

**Comment by phit** [comment]
I don't understand your question, Sponge is a plugin API you don't make mods with it.. you can read the older documentation here https://docs.spongepowered.org/4.1.0/en/index.html

**Comment by flawnn** [comment]
Isn't there a way, to do a Mixin for a Client as Coremod with Sponge?

**Comment by phit** [comment]
Mixin is an independent system from Sponge, you can use it without it. The wiki for it should explain everything you need to know in detail https://github.com/SpongePowered/Mixin/wiki

**Comment by flawnn** [comment]
Ok thanks, but can i use it for changing Clientside Bytecode?

**Comment by flawnn** [comment]
I did my Workingspace, but my problem was, that i couldn't find anything in gradle/maven that imports Client side code.

**Comment by flawnn** [comment]
And i don't see any Documentation how to setup the Workspace. I just did it with the IntelliJ Plugin and chose Sponge....

**Comment by ryantheleach** [comment]
Picking the IntelliJ plugin and choosing Sponge will use an example template for creating Sponge plugins.

Sponge plugins are traditionally server side, so the entire project you have set up will be geared around that.

I believe MCDev has an option for developing a ForgeMod if that's what you want to do, you can select forge mod + Mixin in order to create a new mod that uses mixins.


NOTE: Mixins is not for the faint of heart, and should be considered *core modding* which is **very** much discouraged if you can use an existing coremod or the forge modding framework. I would not recommend using Mixins for your first mod.

Core modding should be a last resort, to add additional API into the game where it's not currently flexible enough to do what you want.
