### ISSUE TITLE
Light Bug

### ISSUE THREAD

**Issue by Mallalei** [SpongePowered/SpongeForge#1916]
**I am currently running**

- SpongeForge version: spongeforge-1.10.2-2477-5.2.0-BETA-2793
- Forge version: 2477
- Java version: 8
- Operating System: Linux

- Plugins/Mods: FTB SkyFactory3 Modpack, PermissionEX, Catclear, simplyChat, SimplyTag, Worldedit, ActionBroadcaster. 

I have a light bug in the whole world. If someone wants to build a mop farm, the light level in the "dark room" is not 0, but sometimes even 14. I've built the darkroom from different materials and always the same result.

**Comment by phit** [comment]
post screenshot of room

**Comment by Mallalei** [comment]
![2017-12-27_17 57 13](https://user-images.githubusercontent.com/22809362/34387631-94a65282-eb2f-11e7-8ad4-d37e38a6df64.png)
![2017-12-27_17 57 18](https://user-images.githubusercontent.com/22809362/34387632-94bd5efa-eb2f-11e7-8f83-28c8e7189187.png)
![2017-12-27_17 57 26](https://user-images.githubusercontent.com/22809362/34387633-94d440c0-eb2f-11e7-8147-92ef66f59c6d.png)
![2017-12-27_17 56 59](https://user-images.githubusercontent.com/22809362/34387634-94ea7f02-eb2f-11e7-9c40-c46b988d27f6.png)
![2017-12-27_17 57 07](https://user-images.githubusercontent.com/22809362/34387635-9501ec28-eb2f-11e7-9927-9c00ddfa5a1f.png)
![2017-12-27_17 53 20](https://user-images.githubusercontent.com/22809362/34387641-a0737d42-eb2f-11e7-8710-8d8aeef34177.png)

**Comment by phit** [comment]
Closing this issue, as of today 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please [open a new issue](https://github.com/SpongePowered/SpongeForge/issues/new) with updated information.
