### ISSUE TITLE
Skins disappearing constantly

### ISSUE THREAD

**Issue by KhaozFrost** [SpongePowered/SpongeForge#1924]
**I am currently running**

- SpongeForge version: 1.12.2-2555-7.0.0-BETA-2807
- Forge version: 2555
- Java version: 1.8.0_151
- Operating System: Linux OS

- Plugins/Mods: 
1st test - SpongeForge / Forge
2nd test - SpongeForge / Forge / Pixelmon Reforged / GriefPrevention / Nucleus / Luckperms ((all on latest versions))

**Issue Description**
http://prntscr.com/hubsbo
http://prntscr.com/hubsif
http://prntscr.com/hubsv9

Ever since I updated/ported from SpongeForge 1.10.2 to 1.12.2 API 7 players have constantly lost their skins for whatever reason; doesn't matter if its modded or vanilla. There doesnt seem to be any server logs or errors showing up when this happens either; they just vanish for a time and then after a relog they come back. relogged players are able to occasionally see others but others are not able to see unless they relog aswell.

**Comment by phit** [comment]
been seeing this too, not sure if it's sponge or nucleus.. havent had time to test this yet
see also https://github.com/NucleusPowered/Nucleus/issues/1041

**Comment by phit** [comment]
To quote dualspiral:
>Try turning `alter-tab-list` in the `vanish` module to `false`, then restart your server. Do so without tab 
manager - then try with.

Closing as this is not a Sponge issue.

**Comment by dualspiral** [comment]
To note, I’m not convinced it’s a Nucleus issue, rather that I expose some issue tying scoreboards and skins together.

The code that is causing this is https://github.com/NucleusPowered/Nucleus/blob/sponge-api/7/src/main/java/io/github/nucleuspowered/nucleus/modules/vanish/service/VanishService.java#L7. I think it’s probably because I fire this too early, and it’s screwing around with the user storage too. I’m going to issue an announcement on the Nucleus channel and an update disabling the system until I can get to the bottom of this, but me altering the tab list should not affect skins like this, nor the user storage.
