### ISSUE TITLE
Generating Woodland Mansion on pre-generated world crashes the server.

### ISSUE THREAD

**Issue by PixelmonPRO** [SpongePowered/SpongeForge#1946]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2555-7.0.0-BETA-2800.jar
- Forge version: forge-1.12.2-14.23.1.2582-universal.jar
- Java version:  1.8.0_144 / 1.8.0_151 (update)
- Operating System: Debian 8 Jessie 64 bit

- Plugins/Mods: https://gist.github.com/PixelmonPRO/5d663870593c452e61d74e2664027223

**Issue Description**
I had a server on version 1.10.2. Map was generated using RTG mod, to world border (created using Nucleus).
I updated my server to version 1.12.2 - RTG mod currently hasn't updated version, so I returned to normal world generator, and reduced size of world border (to prevent generation of new chunks). Also I disabled vanilla structures generation.
When I am flying on my map - in some biomes (like Swamland) server crash happens: https://gist.github.com/PixelmonPRO/f6dae6ec63b754054dddf789efc6b3ba

**Comment by phit** [comment]
can you try loading the same areas without Sponge?

**Comment by PixelmonPRO** [comment]
@phit yes, i go in crash coordinates - no crash without Sponge
![2018-01-08_03 04 49](https://user-images.githubusercontent.com/26658563/34655794-d1b5980a-f420-11e7-8e73-e51ded9197b2.png)

**Comment by phit** [comment]
thanks

**Comment by johnfriedrich** [comment]
Here is another crashreport. Just in case it's needed. But should be the same anyway.
We did not use a custom generator.
Structure gen is disabled aswell (But not for mansions)
https://pastebin.com/3nPmpf63

**Comment by Zidane** [comment]
You have another mod (besides Sponge) that is changing ChunkGeneratorOverworld. Can you remove mods one by one (except Sponge) and see if Sponge never crashes?

**Comment by Zidane** [comment]
Scratch the above, this is odd...

**Comment by johnfriedrich** [comment]
Maybe worth to mention that our world is an updated world too (from 1.10.2).
However as this is our mining world, we removed the data and region folder entirely to reset the map.
Still, after people got to a mansion, it crashed.

**Comment by Zidane** [comment]
@i9hdkill 

Can you get on to a chat so I can give you a SF jar to try? Discord/Teamspeak?

**Comment by Zidane** [comment]
Actually...

@i9hdkill 
Can you get me world data where I can join and trigger a crash? I tried stable-7 AS-IS and get no crash with a seed that is guaranteed to make a mansion nearby.

**Comment by johnfriedrich** [comment]
Try this one:
World is named "mine"
https://www.dropbox.com/s/xrmtnrll703xp0t/mine.zip?dl=0
/tp 4400 90 273
Actually the same chunk/mansion like in the crash.
We "fixed" it by disabling structuresaving for mansions (At least we think we fixed it by doing this)
But probably it just took some crashes to generate the whole mansion:D
You may need Pixelmon Reforged 6.0.1

**Comment by Zidane** [comment]
@i9hdkill 

That doesn't have any region data in it.

**Comment by ryantheleach** [comment]
>However as this is our mining world, we removed the data and region folder entirely to reset the map.

**Comment by johnfriedrich** [comment]
Thats right, I am pretty sure it's the old 1.10 level.dat or sponge in general. When we reset our mine, we delete the data and region folder completely. And after doing so, the server crashed at that coordinates.
(We only keep level.dat and sponge_level.dat to make sure sponge/world uuid doesn't break)

**Comment by johnfriedrich** [comment]
If relevant, this are our sponge settings:
https://www.dropbox.com/s/chs6rn7f07aibo6/sponge.zip?dl=0
Disabled ip forwarding/bungee for you and turned mansion structure saving back on. (Like it was when the servers was crashing on and on)
Forge: 2582
SF: 2800

**Comment by Zidane** [comment]
Using your world level.dat and level_sponge.dat, I cannot reproduce this issue with just Sponge.

Proof:

![2018-01-11_14 25 56](https://user-images.githubusercontent.com/744482/34845715-79e04cb6-f6db-11e7-9769-ebc527a8a110.png)

**Comment by johnfriedrich** [comment]
Okay, thanks for looking into it. I will try to reproduce and narrow it down and report back later.

**Comment by johnfriedrich** [comment]
Seems like the problem only occurs after a restart. (Guess due to saving data)

I updated spongeForge to 7.1.0 2833 and Forge 2587
Client-Forge 2581
Take the world I sent you, join it, let the mansion generate and stop your server. (Just in case do /save-all before)
Start your server and try to join. You will get the following error:
https://pastebin.com/h6KXDWmp

Also happens with just SpongeForge installed. When I remove Forge, the client can join just fine

Update: Try this mine world:
https://www.dropbox.com/s/2d4ur51zrcqfryk/mine_2.zip?dl=0
Still the same coordinates

Thanks again for looking into it!

**Comment by johnfriedrich** [comment]
Were you able to reproduce?
This is still a thing:
https://pastebin.com/DBMDSHv3
SF 2844 + Forge 2590

**Comment by Earthplate** [comment]
This just happened on my server which is running the latest forge/sponge

**Comment by gabizou** [comment]
@Earthplate can you provide some logs and version information?

**Comment by johnfriedrich** [comment]
https://pastebin.com/GZkF07Td
Same crash with recent sponge and forge version.
Same map I uploaded

**Comment by Lorrainrm** [comment]
Guess a world gen (nucleus) fixed it for me.
Peace

**Comment by SnowBlitzz** [comment]
Guess it's still happening. I've provided a crash log on that other ticket that was referenced in case you guys need more data or something.

My world is pre-generated so it's making less sense that the generation of the structure is crashing the server.

**Comment by Mikirae** [comment]
Not sure if this has been fixed and just not marked at all or something, but I spent three hours trying to fix my server due to this crash. Most people simply remove sponge when this happens to their world, but I was unable to do this because it happened in my secondary world. I spent three hours of my time trying to figure out how to fix this issue without deleting a dozen people's homes in my world. Is there some other way to fix this that I'm unaware of. In the end, I had to delete everyone's hard work due to a bug that is over nine months old. I could have had a child in the amount of time that this ticket has gone unfixed.

**Comment by gabizou** [comment]
The bug is rather complicated to fix as the source of the bug is not at all evident, even with the logs. The problem is reproducing in a local development environment to "see" when things are changing that we end up having an NPE (because even with the stack traces, it's not identifiable what is null under what context). I understand the frustration that the issue is causing, but resorting to comparing the issue being old is not going to contribute anything but apathy. I don't have a workaround, and I don't have an idea of where the cause is as the point of error is plainly ambiguous (leading to why this issue is still open). 

There's more that could be done, sure, but everyone has different priorities.

**Comment by gabizou** [comment]
To summarize from the commits, there is what on the surface looks like a workaround, but is likely a byproduct of the nature how chunk loading is piped through the chunk loader on the server versus just normal world generation on the client. The root cause is that because structures are being requested outside the world generation pipeline that sponge otherwise controls, sponge has to delegate back to the vanilla provider for filling blocks in a chunk, but because WoodlandMansions requests to set up the blocks in the chunk primer by itself, sponge did not get to set up the biome array for the structure to be prepared. 

Investigated the 1.13 codebase and the issue is already mitigated entirely due to the world generation and structure handling being rewritten.
