### ISSUE TITLE
Astral Sorcery tree beacon

### ISSUE THREAD

**Issue by anthonysan95** [SpongePowered/SpongeForge#1953]
**I am currently running**

- SpongeForge version: 1.12.2-2555-7.1.0-BETA-2834
- Forge version: 1.12.2-14.23.1.2566
- Java version: 1.8.0_151
- Operating System: Windows

- Plugins/Mods:
Astral Sorcery astralsorcery-1.12.2-1.8.4.jar

**Issue Description**
With sponge installed, the tree beacon from astral sorcery doesn't turn the tree into the fake tree when it grows.. already asked on AS part and they won't do a compat fix..
No errors appears in the console, the tree just grows normally without changing.

Zip containing the server used for testing [here](https://drive.google.com/file/d/11E6P-Gvdi0zhsB5sInb4sU6GzmJL18qs/view?usp=sharing).

**Comment by ryantheleach** [comment]
https://github.com/HellFirePvP/AstralSorcery/issues/504

https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/block/BlockTreeBeacon.java
https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/block/BlockFakeTree.java

https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/tile/TileTreeBeacon.java
https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/tile/TileFakeTree.java

**Comment by phit** [comment]
repro:
>Place the Tree Beacon into the world and plant a sapling next to the Beacon. Encourage the tree to grow with bonemeal and you will notice the tree disappears but a ghostly shadow will stay in its place. Over time, this ghost will decay leaving behind Saplings and Wood. 

still an issue with
spongeforge-1.12.2-2768-7.1.6-RC3586.jar
astralsorcery-1.12.2-1.10.11.jar

**Comment by gabizou** [comment]
To give some context:

AS does capture block checks when trees are grown through the beacon ticks, and because Sponge captures block changes through it's own block snapshot system, AS doesn't get the same list of existing block changes that Sponge has captured, and what is expected to be captured through Forge's capture boolean flags.

I'm working on a fix that is fairly similar to the piston dupe fix, but being that this fix is more intrinsic to Forge's end, I'll keep the two implementation changes branches separate. 

What this does mean though is that captured block changes will need to be verified that changes to the block snapshots will either persist or not persist in sponge's tracking. The other consideration is when mods attempt to modify the underlying list controlled by the PhaseContext, will Sponge respect those changes, or mark those transactions as being cancelled for sponge's event purposes (since forge snapshots are not sponge snapshots, they have to be recreated when the list is being used (and they will be cached))

**Comment by gabizou** [comment]
Thinking about the issue further, It'll very well be possible for sponge to sustain a "view based" list to allow AS to interact with these captured block changes, so that Sponge would be able to likewise cope with mod interactions a bit better. Seeing as the list is not being modified, I can imagine that the list of snapshots will be an unmodifiable list being presented to mods (so that only sponge is once again modifying during iteration, if the mod is editing the list outside of an iterator, then they will be able to do that, but modifying the list with the iterator will not be allowed, as sponge is likely to be modifying the underlying lists itself while blocks are being captured).

Any thoughts on the matter @HellFirePvP?

**Comment by miladydreads** [comment]
Has this been resolved yet?  I am running 2768-7.1.6-RC3604 and am still getting this issue.  Just wondering if there is another version that I need to use instead.

**Comment by gabizou** [comment]
It's taken a bit to resolve it, since it required major refactors in Sponge's tracking and handling to support simplified block snapshot changes, I'm almost sure I'll be able to support what the tree beacon is doing (having written the tracker to properly support these sort of lists being mutated outside of sponge). Likely will be making some branch with a PR in the coming weeks. 

For information on what changes I'm referring to, the two major PR's to change up the tracking handling were: https://github.com/SpongePowered/SpongeCommon/pull/2163 and https://github.com/SpongePowered/SpongeCommon/pull/2219. There's a few things that I do need to prioritize currently before I can tackle the compatibility branch for astral sorcery, namely the [Sponge Schematic Format](https://github.com/SpongePowered/Schematic-Specification/pull/13) changes which involves [updating API](https://github.com/SpongePowered/SpongeAPI/pull/1987) and [implementation](https://github.com/SpongePowered/SpongeCommon/pull/2231).

I know it's not ideal, but due to the nature of the objects being used by the beacon, I can't quite just "flip a switch" to be able to support the sort of block capturing modifications AS is expecting to use for it's purposes, yet.
