### ISSUE TITLE
Failed to save configuration

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1991]
- SpongeForge version: spongeforge-1.12.2-2586-7.1.0-BETA-2887.jar
- Forge version: 14.23.1.2586
- Java version: build 1.8.0_151-b12
- Operating System: 64bit windows 10 home

Plugins: Currently none
Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, Actually Additions, Advanced Generators, Ambience, Applied Energistics 2, Aroma1997Core, AromaBackup, AromaBackuprecovery, AutoRegLib, BD Lib, Baubles, Better Builder's Wands, BetterBedrockGen, Block Armor, Botania, ChickenChunks, Chisel, Chunk Pregenerator, CoFH Core, CoFH World, CodeChicken Lib, Compact Solar Arrays, ComputerCraft, CraftTweaker JEI Support, CraftTweaker2, Cucumber, Cyberware, DeepResonance, ElecCore, Extended Crafting, External Tweaker, Extra Cells 2, Extra Utilities 2, Extreme Reactors, Gravestone Mod, ICBM-Classic, Industrial Foregoing, IndustrialCraft 2, InstantUnify, Iron Chest, IvToolkit, Loot Bags, LootTweaker, MTLib, Magical Psi, Mantle, Mekanism, MekanismGenerators, MekanismTools, MmmMmmMmmMmm, Moar Tinkers, Mod Tweaker, Modern Warfare, OMLib, Open Modular Turrets, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, OreExcavation, PlusTiC, ProjectE, Psi, Quick Leaf Decay, Random Things, Redstone Arsenal, Redstone Flux, Refined Storage, SanAndreasPs Mod Library, SanAndreasPs Player Model, Secret Rooms 5, Shadowfacts' Forgelin, SimpleInventoryStarter, TATW, Tesla Core Lib, Tesla Core Lib Registries, The Lost Cities, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinker I/O, Tinkers Tool Leveling, Tinkers' Addons, Tinkers' Construct, UniDict, Voltz Engine, WanionLib, Zero CORE, mob_grinding_utils

Whenever the server launches this error will sometimes appear and this issue does not happend if sponge ain't present https://pastebin.com/S5jkn7pR

This issue occurs at random during startup and i currently have no logs about it available except from the pastebin above.

**Comment by Zidane** [comment]
I ran a server with just Sponge on my desktop in a folder (to match how you are doing things here) and I cannot reproduce this issue. Even added multiple dimensions just because.

You've got a FileSystem issue or a rare edge case that can fail in Configurate.

**Comment by ghost** [comment]
All file permissions are default

**Comment by ryantheleach** [comment]
Has this issue persisted since you restarted your computer?

**Comment by ghost** [comment]
Yes

**Comment by ghost** [comment]
What other information could i possibly give?

**Comment by ryantheleach** [comment]
If we knew, we would have asked. 

>This issue occurs at random during startup and i currently have no logs about it available except from the pastebin above.

> I ran a server with just Sponge on my desktop in a folder (to match how you are doing things here) and I cannot reproduce this issue.

> You've got a FileSystem issue or a rare edge case that can fail in Configurate.

It's unsolvable until someone who knows how to debug the issue can either reproduce it, or get reproduction steps that hint to what the problem is, thus, "more information needed" It's not a slight against you, it's a label to show the status on the main issue list until more information is turned up (either by you, a dev, or someone with a similar issue).

**Comment by dualspiral** [comment]
For what it's worth, Nucleus had a bug like this because I (currently) use Configurate for saving data, though I do plan to move away from that. It _might_ be this, but I cannot be sure. Just hope this sheds some light on this.

In my case, it was due the file trying to load and save at the same time. In my system, I have a loading cache with a removal listener. In the case where an item was evicted, it would save, but sometimes it would tell the cache to re-add it. The result was that Configurate was trying to save and load at the same time. It's a bug on all platforms, but manifests more verbosely on Windows based systems.

On Linux, this isn't so much of an issue, because of the way the file handling works. If a file is being loaded and written, the handle is held, even though the file might be overwritten. The file path doesn't matter once the inode is located ([good SO explanation here](https://stackoverflow.com/a/2031100)) because read operations then work on the inode, not the file name, so even if the file name was redirected to a different inode, the loading process doesn't care at that point (though may get outdated data).

Windows is a different story. The file gets *locked* during access and cannot be overwritten at that time. It's the same cause as the infamous "this file is locked and cannot be removed" scenario. When reading the file, the file name is still important, so Windows locks the file. The save operation then comes in and fails because the file is locked, which results in an `AccessDenied` exception.

While I imagine the save and load happens on the same thread, I suspect the locks last longer than the code because Windows performs delayed write, causing the file to be locked for longer.

The first place to look is at the config saving/loading code. Is it loading and saving every time? If so, then that's probably the culprit and it needs to be rationalised.

**Comment by dualspiral** [comment]
Just looked through the stack trace and I'm more convinced of what's going on.

Because `config-enabled` is `true` in this scenario (only way this is able to occur), during our injected constructor, the save operation is being called no less than three times, possibly four. In this case, copy operations to the same file name are occurring within what I suspect to be microseconds of each other. Windows won't have had enough time to complete the delayed write and release the lock, I suspect.

I just pushed a commit that reduces the number of savings during construction to one using a boolean flag. It's not the most elegant fix, but should hopefully solve the issue by only saving when all changes are made. Please give the latest version a go (should be available in about 15 minutes, will be either build 2913 or 2914 on the stable branch) and let me know if that worked.

Edit: the latest builds at https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2 now have the change in.

**Comment by ziceptor** [comment]
I'm seeing this error regularly. Starting with sponge 1.8. This is not just about the sponge. The same thing happens with the plugins. Craftbook, nucleus (rare), placeholder and some others.

spongeforge-1.12.2-2611-7.1.0-BETA-2914.jar
Restarted the server several times. Looks like the problem's solved. Some testing is required.

**Comment by dualspiral** [comment]
Thanks, that’s encouraging to hear.

**Comment by ghost** [comment]
I am however unable to test it currently as i am replacing the 1.10.2 versions of my modpack and server with 1.12.2 and i am still working on the client after which i will continue working on the server.

**Comment by ziceptor** [comment]
ooh https://gist.github.com/ziceptor/a3a0ff62c38f7dfac5f348ec4844757e#file-fml-junk-earlystartup-log-L6163

**Comment by dualspiral** [comment]
That's futher down the load worlds method so I seem to be on the right track. Will take a look when I get time - for my own reference: https://github.com/SpongePowered/SpongeCommon/blob/4b27a932181364707df81b9aae5ec0079cb89182/src/main/java/org/spongepowered/common/world/WorldManager.java#L727

**Comment by ziceptor** [comment]
In piggy Bank.

There were no mistakes for a long time. But after updating the plugin ([commit](https://github.com/trentech/WalletDrop/commit/3cbfe97460d877152cb1ad710519ff65baddc42d)) the server went crazy. Each run is accompanied by a set of errors "Failed to save configuration".

A set of [files](https://i.imgur.com/rfhVEo9.png) with [identical](https://i.imgur.com/qKRqKio.png) contents is created.

[custom_data.conf](https://gist.github.com/ziceptor/4fed0483ae13d326ca78322492db6d6d)

[fml-junk-earlystartup.log](https://gist.github.com/ziceptor/c9c1d18f7329ce7afe49781a038960e7#file-gistfile1-txt-L1795)
[fml-server-latest.log](https://gist.github.com/ziceptor/6fdc4c35e12d7af753f256ea9a57f430)
[latest.log](https://gist.github.com/ziceptor/b7e8d804c84543a5c83fccc290cad739)

forge-1.12.2-14.23.2.2611-universal.jar
spongeforge-1.12.2-2611-7.1.0-BETA-2990.jar

**Comment by ziceptor** [comment]
forge-1.12.2-14.23.3.2655-universal.jar
spongeforge-1.12.2-2655-7.1.0-BETA-3065.jar

We still hope for a fix

**Comment by phit** [comment]
@dualspiral can you take a look at this again, the fix you pushed seems to have caused more issues than it fixed

specifically it seems to lead to the configs being overwritten with their default values in some cases, with the only fix making the config file read only

**Comment by Tommeh1** [comment]
I had my applied energistics config randomly reset a few days ago which caused overlapping dimension ids followed by a crash loop.

**Comment by dualspiral** [comment]
@ziceptor @phit Having looked at the stack traces, that has nothing to do with this specifc bug or my fix. The stack traces in the issue point to custom data config files, not the world config files, which are loaded at a completely different point.

For what it’s worth, all my fix did was defer saving within the same tick to prevent multiple saves occuring. If it was causing problems, I would have expected the issues to occur as soon as the commit was made. If there is a problem with world files then I wonder if there has been a change since, but I’ve not been able to keep up with Sponge recently and so couldn’t tell you.

Unfortunately, I have no time to look at this right now. The custom data thing is probably easy to fix but should be in its own bug rather than this one that concentrates on the world config saving - I am aware I need to finish my work on it but, again, it will be when I have time.

**Comment by dualspiral** [comment]
https://github.com/SpongePowered/SpongeCommon/commit/4bbcc65d26b5659d86c91acb3ae55514aef3fe2e fixes the problem indicated by the stack trace, it was a duplicated save operation when creating the custom data config file.

This is actually something that will likely occur on SpongeVanilla too, this is code affecting SC. I'll move the issue over there.

**Comment by dualspiral** [comment]
~move to sc

**Comment by limbo-app** [comment]
Hey @TomTheHero! I've moved your issue to [SpongePowered/SpongeCommon#1906](https://github.com/SpongePowered/SpongeCommon/issues/1906).

**Comment by phit** [comment]
@dualspiral I wasn't even talking about that custom_data stuff, my comment was purely about the global.conf
>Sponge overwrite it's global.conf with no reason, no errors nothing and if you block writing with chattr it loads the config fine it just spits out a tmp file every restart.

**Comment by ziceptor** [comment]
> SpongePowered/SpongeCommon@4bbcc65 fixes the problem indicated by the stack trace, it was a duplicated save operation when creating the custom data config file.

@dualspiral the fix didn't work.

[debug.log](https://gist.github.com/ziceptor/29f7f75f4b12fe7d5ce6394f60ed9057)
[latest.log](https://gist.github.com/ziceptor/a22ceaa4feb735f9bf837f8543c24949)

forge-1.12.2-14.23.3.2655-universal.jar
spongeforge-1.12.2-2655-7.1.0-BETA-3070.jar

**Comment by ziceptor** [comment]
@phit Do I need to issue a separate issue? ^

**Comment by phit** [comment]
@ziceptor reply in https://github.com/SpongePowered/SpongeCommon/issues/1906
