### ISSUE TITLE
1.10.2 port-over issues

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#1992]
**I am currently running**

- SpongeForge version: 1.10.2-2477-5.2.0-BETA-2793 
- Forge version: 12.18.3.2422
- Java version: 1.8.0_151-b12
- Operating System: CentOS Linux release 7.2.1511

- Plugins/Mods:
Sky Factory 3 

**Issue Description**
Hey.. I know you have stopped accepting issues for 1.10 but having a bit of a dilemma here.. 2793 sponge version will crash the server if someone enters the nether - https://gist.github.com/Keaton1188/f6450813318de955d168041aa5c682cd
So went back to using previous version, (2731 + also tried 2788) but that was just spamming with a completing phase - https://gist.github.com/Keaton1188/fb04f8e6c343e5cb5e4cd75a24fbb3e7

Any help would be appreciated, I think that the phase spam may have been fixed in 2793 but the nether issue is stopping me (and others) from using that version. <3 

Ignore that ^ phase spam is still there with latest :/

**Comment by phit** [comment]
1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please [open a new issue](https://github.com/SpongePowered/SpongeForge/issues/new) with updated information.

---

as noted by you the nether crash in combination with YUNoMakeGoodMap is solved by downgrading to 2788
