### ISSUE TITLE
crash-reports

### ISSUE THREAD

**Issue by xxlio109** [SpongePowered/SpongeForge#2027]
- SpongeForge version: 1.10.2-2477-5.2.0-BETA-2793
- Forge version:  Forge-1.10.2-12.18.3.2511
- Java version:    JAVA8
- Operating System:  centos

- Plugins/Mods:
Baubles-1.10.2-1.3.13
Botania r1.9-341
BloodMagic-1.10.2-2.1.11-80
Guide-API-1.10.2-2.0.3-46
ironchest-1.10.2-7.0.15.804
JurassiCraft-2.1.3-Fix
llibrary-1.7.7-1.10.2
Mantle-1.10.2-1.1.5
mysticalagriculture-1.10.2-1.5.10
SlashBlade-mc1.10.2-r39
spongeforge-1.10.2-2477-5.2.0-BETA-2793
taiga-1.10.2-1.2.6
TConstruct-1.10.2-2.6.3
Thaumcraft-1.10.2-6.0.BETA7

*********ttps://gist.github.com/**********
https://gist.github.com/xxlio109/a6966004f3a28beab2c9df26db0c5b69

**Comment by phit** [comment]
**1.10.2 and 1.11.2 are not longer supported, as of January 2018.** If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please [open a new issue](https://github.com/SpongePowered/SpongeForge/issues/new) with updated information.
