### ISSUE TITLE
Item duping with Integrated Dynamics

### ISSUE THREAD

**Issue by rubensworks** [SpongePowered/SpongeForge#2043]
*Note: this issue was originally reported by @xILikepuddingx in CyclopsMC/IntegratedDynamics#560, so if additional information is required, @xILikepuddingx will be able to help*

**I am currently running**
- SpongeForge version: v1.12.2-2611-7.1.0-BETA-2931
- Forge version: 14.23.2.2619
- Java version: 1.8 (?)
- Operating System: ?

- Plugins/Mods:
Unknown

**Issue Description**

When SpongeForge is installed, some Integrated Dynamics blocks are duped. It looks like that when ID parts are broken, they are dropped multiple times.

Video: https://files.pudding.tk/wgh6cl2lvq.mp4

Original issue: https://github.com/CyclopsMC/IntegratedDynamics/issues/560

_Note that ID uses a custom multipart system. I'll investigate this issue on my end, but reporting this here in any case, as you may be able to help tracking down the cause._

**Comment by gabizou** [comment]
I'm curious about the placement logic. It might have to do with the delay of the block placement being performed while the item being used is not delayed. Since the PhaseTracker does do a bit of handling in this instance, if you're able to load into a development environment with SF and ID specifically, the [unwinding of the InteractionPacketState](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/event/tracking/phase/packet/InteractionPacketState.java#L121) handles all the block changes and inventory changes. I would look into the item class in ID to determine whether there's some logic that won't work in a delayed environment.

**Comment by rubensworks** [comment]
The placement logic is a bit special, because of the multipart system, so I'm not surprised that this can cause issues with SF.

Relevant code:
* https://github.com/CyclopsMC/IntegratedDynamics/blob/4d742e81cac150f89b64f74aaf3ec4889a76b53d/src/main/java/org/cyclops/integrateddynamics/core/item/ItemPart.java#L73-L74
* https://github.com/CyclopsMC/IntegratedDynamics/blob/4d742e81cac150f89b64f74aaf3ec4889a76b53d/src/main/java/org/cyclops/integrateddynamics/core/item/ItemPart.java#L73-L74

I'll look into loading SF into my dev environment soon. I assume I can just deobfuscate the releases and load them?

**Comment by kashike** [comment]
We have dev JARs available: https://files.minecraftforge.net/maven/org/spongepowered/spongeforge/

**Comment by rubensworks** [comment]
Ah, even better, thanks @kashike!

**Comment by josephcsible** [comment]
Deobfuscating the release jar might be a better idea, to avoid a recurrence of CyclopsMC/IntegratedDynamics-Compat#4.

**Comment by gabizou** [comment]
I don’t think it would work in deobfuscating a production jar because the mixin constants wouldn’t be modified I think. The dev jar would more like be best. Otherwise, the cloning and setup can take maybe 10 mins (instructions on spongeforge readme)

**Comment by ghost** [comment]
with the current version of spongeforge, the bug seems to have been fixed

**Comment by rubensworks** [comment]
Ok, so @xILikepuddingx tested it with SF 7.1.0-BETA-2963.

I can confirm that I tested it in a dev environment with SF 8.0.0-BETA-2959 and I was not able to reproduce this.

So I guess this issue can be closed.
