### ISSUE TITLE
Server Resource Pack causes error after rejoining.

### ISSUE THREAD

**Issue by Big-Deaddy** [SpongePowered/SpongeForge#2062]
**I am currently running**

- SpongeForge version: 1.12.2-2611-7.1.0-BETA-2970
- Forge version: 14.23.2.2611
- Java version: Unknown
- Operating System: Unknown

- Plugins/Mods: Plugins (33): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, CarrotShop, CatClearLag, CraftBook, EconomyLite, Enjin Minecraft Plugin, GriefPrevention, Holograms, HuskyCrates, HuskyUI, LuckPerms, MMCRestrict, MagiBridge, NuVotifier, Nucleus, PayDay, Pixelauctions, PixelmonEconomyBridge, PlaceholderAPI, PlayerShopsRPG, PokeClear, Randomizer, RankUpper, SeriousVote, ServerSigns, TabManager, Unity, Valentines, YourCustomPaintings, latch

**Issue Description**
When using the server resource pack feature, users get kicked after a short time and console is spammed with errors from Sponge: https://gist.github.com/Big-Deaddy/4c49d8f6d4fc5c6d503563b29c2d5ea3 

Steps to reproduce:
1) Set `resource-pack=` and `resource-pack-sha1=` in `server.properties`
2) Click "Yes" when prompted to download
3) After download has completed, leave the server
4) Upon joining back, the game freezes, console spams with Sponge errors, and user is able to walk around after console says they left after their game catches up until they receive a timeout error.

**Comment by phit** [comment]
~~@JBYoshi probaly related to https://github.com/SpongePowered/SpongeCommon/pull/1771?~~

got my timeline messed up, @Big-Deaddy please try 2972 or newer

**Comment by Big-Deaddy** [comment]
With 2972 I get the following error when following my steps:
`[23:55:17] [Server thread/WARN]: handleDisconnection() called twice`

The latest version (2981) seems to work okay on my test server, I'll let you know if the issue arises again when I update my main server. Thanks.

**Comment by Big-Deaddy** [comment]
People on my main server timeout after ~20 seconds of being on the server after enabling server resource packs, but the other errors from before are gone. After several retries, however, it does eventually work for some. So far, that number ranges from 2 all the way up to 10+.

**Comment by ryantheleach** [comment]
@Big-Deaddy To confirm, all previous errors are gone, but people still timeout?

Can we have your resource pack + sha1 settings to test with? It's going to be hard to reproduce, and I suspect it may be a vanilla issue. If you could get one of those people with timeout issues to test against a vanilla server with that resource pack enabled it will help work out whose issue it is, ours or Mojangs.

Closing this, as the original issue is fixed in my eyes, If you can succesfully create a timeout (irregardless of Mojang Vanilla vs SpongeForge) create a new ticket about the timeout. We may be able to improve this issue, as other minigames servers have surely run into this problem.
