### ISSUE TITLE
dupe with flans mod

### ISSUE THREAD

**Issue by rippy222** [SpongePowered/SpongeForge#2063]
**I am currently running**

- SpongeForge version:  spongeforge-1.12.2-2611-8.0.0-BETA-2971
- Forge version: 1.12.2
- Java version:  java 8
- Operating System: 

- Plugins/Mods:
Sponge

**Issue Description**
So when  i grab a gun from flans mod, i press q to drop it, then it doesnt drop it out of my inventory but it drops a new same item but keeps the one in my inventory allowing me to dupe it. this also happens on other servers with flansmod running 1.12.2 sponge

https://gist.github.com/rippy222/a7ec53d53357b5ec851499e47ad2e0b5

**Comment by phit** [comment]
confirmed with
spongeforge-1.12.2-2611-7.1.0-BETA-2984.jar
Flan's Mod-1.12.2-5.5.1.jar
Modern Warfare-Content Pack-1.12.2-5.5.2.jar

**Comment by ChrisLane** [comment]
Where ItemTossEvent is cancelled in FlansMod: https://github.com/FlansMods/FlansMod/blob/fd1077cf43b4ae4416731d18aeed96b0e8d9053d/src/main/java/com/flansmod/common/FlansMod.java#L442

This seems like it's related to #1265 which has been open for over a year now.

**Comment by ACPenguin** [comment]
im getting this as well with all versions of sponge

**Comment by Tommeh1** [comment]
Same, had to lockdown my server

**Comment by spaceotter** [comment]
Ran into this issue while playtesting my new pack.
spongeforge-1.12.2-2705-7.1.0-BETA-3206.jar
Flan's Mod-1.12.2-5.5.2.jar

**Comment by NightHawk5755** [comment]
so, anyone find a fix, because I am having the same issue...

**Comment by ryantheleach** [comment]
Flan's mod is open source, Gun dropping: https://github.com/FlansMods/FlansMod/blob/1.12.2/src/main/java/com/flansmod/common/guns/ItemGun.java#L200

**Comment by ghost** [comment]
Wrong line

**Comment by ryantheleach** [comment]
@TomTheHero Can you elaborate?

**Comment by ghost** [comment]
That one is the method for dropping items on reload and on shoot, not the item itself

**Comment by rvveber** [comment]
still a thing

**Comment by RedNesto** [comment]
Found what breaks everything: [that damn cancel](https://github.com/FlansMods/FlansMod/blob/fd1077cf43b4ae4416731d18aeed96b0e8d9053d/src/main/java/com/flansmod/common/CommonTickHandler.java#L90)

The Forge event is cancelled, so Sponge removes the entity that should have been spawned ([reference](https://github.com/SpongePowered/SpongeForge/blob/stable-7/src/main/java/org/spongepowered/mod/event/SpongeToForgeEventFactory.java#L584)) then Sponge sees that there is no entity to be spawned for its own event, so the Sponge event is cancelled ([reference](https://github.com/SpongePowered/SpongeForge/blob/stable-7/src/main/java/org/spongepowered/mod/event/SpongeToForgeEventFactory.java#L588)), meaning the gun is kept in the inventory by Sponge, but Flans adds a replacement entity (for whatever reason) on its side so it is still spawned by Flans ([reference](https://github.com/FlansMods/FlansMod/blob/fd1077cf43b4ae4416731d18aeed96b0e8d9053d/src/main/java/com/flansmod/common/CommonTickHandler.java#L89)).

Apparently, Flans is making it this way because it "Stops concurrent modifications and messing up the entity list"
 ([see this](https://github.com/FlansMods/FlansMod/blob/fd1077cf43b4ae4416731d18aeed96b0e8d9053d/src/main/java/com/flansmod/common/CommonTickHandler.java#L22))

I don't know how to handle that properly though, so I leave my results here and will get some sleep.

**Comment by RedCriterion** [comment]
nice!!!

**Comment by gabizou** [comment]
@RedNesto Awesome detective work!

I have a potential solution for this, and this might have been because how custom items were potentially added as custom entities in forge more recently than the flan's handling code was created.

It involves making the item stack override [Item#hasCustomEntity](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/patches/minecraft/net/minecraft/item/Item.java.patch#L263) which sponge happily handles well these days, and of course, handles them in the main thread no less! 

I wouldn't be too sure about whether this would be a valid fix but seeing as Flan's mod is doing things irregularly, it's not possible to handle it in Sponge by itself, regardless of changes as an entirely new wrapper entity is created, eliminating the possibility of "chaining causes" if you will.

**Comment by RedNesto** [comment]
Thanks to @gabizou's valuable Forge expertise, I was able to find a fix for Flan's mod.
Let me introduce to you [The Holy Anti-Dupe Patch](https://gist.github.com/RedNesto/4181dc67d8902d3c6b16ba304931d6ce#file-patching-patch-L140) (skip of useless imports and minor refactoring included, may contain traces of FLARD).

**Comment by NightHawk5755** [comment]
Great!
So, how do I implement this?

**Comment by RedNesto** [comment]
A developer could apply the patch in a Flan's mod clone (but I did not removed the event listener that causes the duplication in the patch I shared).
Otherwise, you have to wait for Flan's developers to fix the bug, but they have not been active on the repository recently.

I made a [fixed release](https://github.com/RedNesto/FlansMod/releases/tag/1.12.2-5.5.2-for-Sponge) based on the latest commit they made on GitHub. The dupe is fixed for me with this release, but I cannot guarantee the mod works as intended (I had to play with the buildscript to include a apocalypse package they had in their official 5.5.2 release).
For those interested by my solution, they can take a look at [this commit](https://github.com/RedNesto/FlansMod/commit/b64ebaad2dada2bd189ca0447a6843b31e2c0bf7).

**Comment by ChrisLane** [comment]
Thanks @RedNesto, your fix is now in the main repo.
