### ISSUE TITLE
Timings increasing startup time

### ISSUE THREAD

**Issue by broeredaan** [SpongePowered/SpongeForge#2074]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2611-7.1.0-BETA-2996
- Forge version: forge-1.12.2-14.23.2.2635-universal
- Java version: 8
- Operating System: Ubuntu

- Plugins/Mods: Plugins none, Modpack is SevTech Ages 3.0.3

**Issue Description**
As the title suggests. When I add SpongeForge the startup time increases greatly. I think it takes like 5-10 minutes more to startup the modpack in comparison without SpongeForge installed. (This is on a i7 6700K)

**Comment by gabizou** [comment]
Kinda need more info: Do you have some timings to report? Warmroast/VisualVM/other timing programs to help find out what is causing your server to load slowly?

**Comment by broeredaan** [comment]
I thought i'd be easiest if you guys downloaded the server files and see for yourself?
https://minecraft.curseforge.com/projects/sevtech-ages/files/2545727
Its as simple as putting spongeforge in the mods folder and removing it.
Where with sponge startup takes alot longer. And without its normal.
I would assume you guys know better how to track it. But if needed I can try using Warmroast/VisualVm or something.

**Comment by gabizou** [comment]
>downloaded the server files and see for yourself

Assumes we're all sitting at our desktops and have a server available to turn on with a new modpack etc. 

This is an issue tracker, generally we try to gather as much information as possible to *replicate* and *identify* issues in sponge, but sometimes performance issues are not as simple as just downloading a modpack and "trying it".

**Comment by broeredaan** [comment]
My bad. I tried this on both my server and running it locally on my pc. Same outcome With SpongeForge much slower than clean modpack. So I thought you could do it locally aswell.

But I'll see if I can learn how to use WarmRoast/VisualVM and see if I can come back with a result.

**Comment by broeredaan** [comment]
Okay then. Here is the 2 .nps files I could create. I hope I did it correctly. I also included the logs from the startups if that helps.
[SevTech Sponge Issue.zip](https://github.com/SpongePowered/SpongeForge/files/1865869/SevTech.Sponge.Issue.zip)

**Comment by gabizou** [comment]
So, from what it looks like is Timings is spending a lot of time at startup because of how many events are constantly being thrown. I would disable Timings if you're not using them, otherwise, there could be a workaround to disable timings for specific events or during startup (as they shouldn't really be used then).

**Comment by broeredaan** [comment]
I do use timings every now and then but usually tickprofiler is the one that help me the most. So I could turn timings off completely, but I'd rather turn it off for the startup. I cant find a config for this. What can I do to turn it off for startup? Or were you talking more about a possible addition to sponge timings?

For now I'll turn of timing. Thanks! 👍

**Comment by leelawd** [comment]
Just wanted to throw in a theory on this.

After having my server take 10+ minutes to load and having time out issues with new worlds loading I took a look into the log files and found that when someone enters a world that was previously unloaded, These errors get thrown: https://pastebin.com/6RQj5peK

My assumption here is that its due to the modpack removing all but The betweenlands and the Twilight Forest advancements in replacement of its own from triumph.

I removed the advancements files in each of the erroring mods and surely enough, the pack load time went from 10+ minutes to the usual 3-5 minutes (for a pack of this size). I am also not experiencing any time out issues with worlds loading from an un-loaded state.

**Comment by Artitus** [comment]
I never had an issue with load times with sponge, but the current sponge build is not compatible with the latest version of forge which the latest version of the sevtech: ages pack uses. Hope I was able to provide helpful input.

**Comment by Zidane** [comment]
I'm closing this per @leelawd 's comment until I hear otherwise.

@Artitus SpongeForge's current series of builds for stable-7 (API 7.1-SNAPSHOT) are on Forge 2655.

**Comment by Whazaaaaa** [comment]
Okay so I just did some tests with a clean AllTheMods3 install. This is a very heavy pack. So I would think this is also the best to test timings on.
So with timings enabled the startup of the server takes about 2 and a half minutes longer than when timings is disabled in the _global.conf_

I'm running Forge: **forge-1.12.2-14.23.3.2702-universal**
And SpongeForge: **spongeforge-1.12.2-2690-7.1.0-BETA-3110**
Have no further plugins installed.
Mods installed are the mods from AllTheMods3 (5.9.5) which is about 236 mods
Server pack can be found [[HERE]](https://minecraft.curseforge.com/projects/all-the-mods-3/files/2559966)
I should note that ATM3 has a _ServerStart.bat_ that disables sponge by default. So you'll have to do some tweaks. I usually run it once to install the forge libraries and then have a _start.bat_ which includes:
`java -Xmx8G -Xms2G -jar forge-1.12.2-14.23.3.2702-universal.jar nogui`
Note: I did change the forge version for the pack to work with the latest SpongeForge

And then my Debug logs for for both startups
[Timings **Enabled**](https://gist.github.com/Whazaaaaa/93bccab087415ab26a193030200384df)
[Timings **Disabled**](https://gist.github.com/Whazaaaaa/6ef86db4fc0f894dab20c79436b795d0)

**Comment by gabizou** [comment]
Can you give the newest builds a shot? I forgot I included some timings changes for startup with events, it should make an impact. Build 3115 should do the trick.

**Comment by Whazaaaaa** [comment]
So its still happening.
[sponge +timings  debug.log](https://github.com/SpongePowered/SpongeForge/files/2040271/sponge.timings.debug.log)
[sponge -timings debug.log](https://github.com/SpongePowered/SpongeForge/files/2040272/sponge.-timings.debug.log)
[nosponge debug.log](https://github.com/SpongePowered/SpongeForge/files/2040273/nosponge.debug.log)

**Startup Times**
Without Timings: 04:26
With Timings: 06:06
Without Sponge: 02:36

Also did a startup without sponge for the fun of it. And perhaps for improving startup time more with bigger modpacks.

forge-1.12.2-14.23.3.2702-universal
spongeforge-1.12.2-2690-7.1.0-BETA-3115

**Comment by gabizou** [comment]
Once the next build is finished building, give the one with this commit a try: https://github.com/SpongePowered/SpongeForge/commit/3204020c97a709c252696363e9bf86ccc8dfe0f6
With timings enabled of course.

**Comment by Whazaaaaa** [comment]
**Times I got**
No Sponge: 2:51
Sponge + Timings: 3:35
Sponge - Timings: 3:33
This is with ATM3 5.10.1

So seems that theres not much of a difference between having timing on or off. Still takes longer to load the modpack with sponge than without but that makes sense ^^

forge-1.12.2-14.23.4.2760-universal
spongeforge-1.12.2-2705-7.1.0-BETA-3479

**Comment by gabizou** [comment]
Can you run a profiling result during server start up to provide comparison from forge and sponge installed? I'm almost positive there's more events we're timing the receiving of during startup that is causing the slowdown (because everything getting registered through events ends up causing registrations for anything to take a little longer than without timings). It could very well be something else that we're doing during initialization that causes the slowdown as well. Something that I'm not quite able to troubleshoot by itself with a larger mod pack or plugin setup.

**Comment by Whazaaaaa** [comment]
Okay so I'm not too familiar with profiling but this is what I got.
[samples.zip](https://github.com/SpongePowered/SpongeForge/files/2462150/samples.zip)
Note that the sponge version crashes in the end. Seeing as its about startup time and it crashes around the end of startup I didnt think it mattered. Zipfile has both .nps and logs from startup.
Hope it helps.

**Comment by gabizou** [comment]
The server crash is because of foam fix incompatibility. 

Please add the following flags to startup:
`-Dmixin.debug.profiler=true`

And likewise, disable foam fix's block pos modification in its config. 

There's more to the startup that I'm not sure of how much is affected by class loading costs and mixin performing class transformations. Likewise, because load order cannot be guaranteed, I think it's safe to say we'll need multiple snapshots both with and without sponge to further verify the issue for how sponge is adding additional startup time.

**Comment by Whazaaaaa** [comment]
So the .nps are the correct thing you need + the logs?
Would 5 with and without sponge runs be okay?
Anything else I should include?

**Comment by Zidane** [comment]
Closing as the original issue of Timings increasing the server start time was resolved by a change gabizou made months ago.

It is always our goal to improve our perf where we can and we'll address startup time we add over time (as best as we can).
