### ISSUE TITLE
ICBM Classic Explosives Issue

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#2090]
- SpongeForge version: spongeforge-1.12.2-2611-7.1.0-BETA-3002.jar
- Forge version: 1.12.2 - 14.23.2.2611
- Java version: OpenJDK 64-Bit Server VM, version 1.8.0_151
- Operating System: Linux

- Plugins/Mods:
Mods (103): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, Actually Additions, Advanced Generators, Applied Energistics 2, Aroma1997Core, AromaBackup, AromaBackuprecovery, AutoRegLib, BD Lib, Baubles, Better Builder's Wands, Biomes O' Plenty, Block Armor, Botania, CLibrary, ChickenChunks, Chisel, Chunk Pregenerator, CoFH Core, CoFH World, CodeChicken Lib, Compact Solar Arrays, ComputerCraft, CraftTweaker JEI Support, CraftTweaker2, Cucumber Library, Cyberware, DeepResonance, ElecCore, Extended Crafting, External Tweaker, Extra Cells 2, Extra Utilities 2, Extreme Reactors, FoamFix, FoamFixCore, Gravestone Mod, ICBM-Classic, Industrial Foregoing, IndustrialCraft 2, InstantUnify, Iron Chest, IvToolkit, Just Enough Dimensions, Less Forgiving Void, Loot Bags, LootTweaker, Lost Souls, MTLib, Magical Psi, Mantle, MatterOverdrive, Mekanism, MekanismGenerators, MekanismTools, MmmMmmMmmMmm, Moar Tinkers, Mod Tweaker, OMLib, Open Modular Turrets, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, OreExcavation, PlusTiC, Psi, Quick Leaf Decay, Random Things, RandomPatches, Redstone Arsenal, Redstone Flux, Refined Storage, Sampling Performance Profiler, SanAndreasPs Mod Library, SanAndreasPs Player Model, Secret Rooms 5, Shadowfacts' Forgelin, TATW, Techguns, Techguns Core, Tesla Core Lib, Tesla Core Lib Registries, The Lost Cities, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinker I/O, Tinkers Tool Leveling, Tinkers' Addons, Tinkers' Construct, UniDict, WanionLib, Zero CORE, mob_grinding_utils

Plugins (19): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, CatClearLag, Eagle Factions, GWMCrates, GWMLibrary, LuckPerms, MMCRestrict, MagiBridge, No Downfall, NuVotifier, Nucleus, Prism, SeriousVote, Total Economy, UniversalMarket, Vanish

This appears whenever i set off an explosive, the blast occurs but it does not damage any blocks and it keeps on spamming my console until i restart the server:
In rare cases the explosion will occur flawlessly.
https://pastebin.com/HDe48sHD

**Comment by ghost** [comment]
I just wanna let you guys know that my server release is delayed until this has been fixed so id appriciate it if this were to be fixed quickly.
I'm willing to try out any experimental fixes myself if nessesairy

**Comment by dualspiral** [comment]
We welcome pull requests if you want this fixed quickly. Please remember that this is a volunteer run, open source project, we do not prioritise issues based on comments like this.

**Comment by ghost** [comment]
Phit, mind telling me if that mod incompatability will be dealt with on spongeforge its side or not, if not imma refer the dev to this issue

**Comment by phit** [comment]
looks like a mod issue from a brief glance, but don't quote me on that
so feel free to also report it to them

**Comment by ghost** [comment]
And 1 explosive(thermobaric) runs into a multi threading issue if that helps: https://pastebin.com/B7Md8zpq
This one explosive might just have an issue on the mod its side though

**Comment by ghost** [comment]
I just tested all explosives without spongeforge and they worked flawlessly, even the thermobaric which had multithreading issues  https://pastebin.com/B7Md8zpq worked

**Comment by gabizou** [comment]
This is more of a bug with the mod itself doing threaded workers without null checking their threads. Otherwise, explosions appear to have been working with SpongeForge unless another ticket is opened with another mod's explosives not working properly.

Reviewing the mod's code, there's a few things they are doing semi-right, but not checking threads and nullable fields is bad practice in general.

**Comment by ghost** [comment]
Is there any chance for me to get a fix on spongeforge its side

**Comment by DarkGuardsman** [comment]
I'll take a look at the bug, next time post on the mod tracker first. I will be able to tell if its a sponge or vanilla mod problem. Based on memory I want to say this is very likely just legacy code failing. The original thread code was made in 1.5.2 Minecraft and has received very little work. As I plan to replace it with the VoltzEngine worker thread system.

**Comment by DarkGuardsman** [comment]
Threaded explosives include Sonic, Rot, Nuclear (Large thread), and AntiGrav (small thread)

I've added a try-catch around the postcode and a null check if the thread failed to run. The first should catch any errors. While the second should let me know if the thread itself is the issue. If it turns out the world is null then something is fishy. As the world shouldn't be able to go null and still have the blast run.

**Comment by phit** [comment]
https://github.com/BuiltBrokenModding/ICBM-Classic/commit/63d52dc976bfa6536e566020919a06c48ca8865d

**Comment by DarkGuardsman** [comment]
Completely forgot about this ticket; good to see someone keeping up with tickets.

As a note, BuiltBrokenModding/ICBM-Classic@63d52dc didn't actually fix the problem but prevents error when thread fails. The actual issue was EntityExplosion being initialized with a tick (entity exists) value greater than 1. Which causes pre-init explosive calls to never run nor threads to start. A simple issue but the cause is still unknown.

https://github.com/BuiltBrokenModding/ICBM-Classic/commit/697bb8a36496e620e91ddb3d2f74810de61a2060
