### ISSUE TITLE
Avaritia attempts to kill entities directly, without damaging them.

### ISSUE THREAD

**Issue by demon57730** [SpongePowered/SpongeForge#2092]
Avaritia-1.12-3.2.0.13-universal.jar
spongeforge-1.12.2-2611-7.1.0-BETA-3012.jar
woot-1.12.2-1.0.1.jar 
Guide-API-1.12-2.1.5-60.jar

as i explained in another subject you told me to open one so voila avaritia has a sword that kills all mob in 1 shot.

without spongeforge the end dragon makes him kill in 1 shot but with the spongeforge he does not die and even the sword and almost ineffective against him

https://youtu.be/-SFUX2TncLc

during the test he has no plugins and the mod that I just gave

**Comment by phit** [comment]
for reference https://github.com/Morpheus1101/Avaritia/blob/master/src/main/java/morph/avaritia/item/tools/ItemSwordInfinity.java#L45

**Comment by Aaron1011** [comment]
For reference, here's the class for the relevant item: https://github.com/Morpheus1101/Avaritia/blob/master/src/main/java/morph/avaritia/item/tools/ItemSwordInfinity.java

**Comment by gabizou** [comment]
To be honest, directly performing death things isn't really supported by sponge very well (noticing it during my refactoring for #2110). My gut feeling is to tell Avaritia to simply do their own void damage absolute damage for the maximum health of the player (since that will perform relatively the same effect than what they're currently doing). AND it will support the likelyhood that the event is cancelled, the entity won't needlessly die due to lack of protection plugins.

**Comment by phit** [comment]
solved in spongeforge-1.12.2-2768-7.1.6-RC3586
