### ISSUE TITLE
Atomic Reconstructor Enchanted Book Splitting

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/SpongeForge#2104]
**Issue Description**
The Atomic Reconstructor from Actually Additions does have a feature which splits enchanted books with multiple enchantments into multiple books with one enchantment.
As seen here: https://github.com/Ellpeck/ActuallyAdditions/issues/985#issuecomment-350949723
Unfortunately does this feature not work with SpongeForge, trying to use it will cause the book to disappear.

**Steps to reproduce**
- Place a Atomic Reconstructor (without lens) and give it power, like creative energy cell
- Throw a book with at least 2 enchantments in front of the Atomic Reconstructor
- Wait until the next beam and see the book disappear with sponge or getting split without sponge

**I am currently running**
- spongeforge-1.12.2-2611-7.1.0-BETA-3019
- forge-1.12.2-14.23.2.2631
- ActuallyAdditions-1.12.2-r133

**Comment by Aaron1011** [comment]
@gabizou: This issue is due to the fact that `TileEntityTickPhaseState` [doesn't check `getBlockDropSupplier` in its `unwind` method](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/event/tracking/phase/tick/TileEntityTickPhaseState.java#L79). There doesn't appear to be a snapshot readily available to use with `TrackingUtil.spawnItemDataForBlockDrop` - is that intentional?

**Comment by phit** [comment]
seems to work fine on ActuallyAdditions-1.12.2-r144 and spongeforge-1.12.2-2768-7.1.5-RC3535
was probably fixed with the big drop rework last year
