### ISSUE TITLE
Bug with Quark and AstralSorcery

### ISSUE THREAD

**Issue by avescarelo** [SpongePowered/SpongeForge#2118]
**I am currently running**

- SpongeForge version: 1.12.2-2655-7.1.0-BETA-3041
- Forge version: 14.23.3.2655
- Java version: 1.8.0_72-b15
- Operating System: Windows/Linux

- Plugins/Mods:

Plugins (12): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, ActiveTime, EconomyLite, GriefPrevention, LuckPerms, Nucleus, Soulbound, TimeWarp, UltimateChat

Mods (35): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AbyssalCraft, Animania, Antique Atlas, AppleCore, Astral Sorcery, AutoRegLib, Baubles, BiblioCraft, Botania, Botaunomy, Chisels & Bits, CraftStudio API, CraftTweaker JEI Support, CraftTweaker2, Earthworks, Example Mod, Hardcore Darkness, Hunger Overhaul, Iron Chest, Magical Psi, Nibbler, Potion Core, Psi, Quality Tools, Quark, Roguelike Dungeons, Rustic, Tails, WorldEdit
> 

**Issue Description**
Hello, I found a problem:
Unable to open interface vanilla note block added by the modification of the Quark. 
The same problem with the telescope interface from mod AstralSorcery. 
When you try to open the interface, it closes immediately. 
This problem only occurs when sponge is installed.

Latest log by server:
https://gist.github.com/pingvikin/d5db3381a938cfc073b81f8e0dd87e29

**Comment by Aaron1011** [comment]
This is going to be somewhat tricky to resolve.

Quark handles its custom NoteBlock gui by calling `openGui` in an `PlayerInteractEvent.RightClickBlock` event handler, and then [cancelling the event](https://github.com/Vazkii/Quark/blob/a0dbd0c69ae00bca778487ac36982fa17480e02c/src/main/java/vazkii/quark/misc/feature/NoteBlockInterface.java#L33). The GUI is purely client-side, so the call to `openGui` on the server doesn't cause a `Container` to be created.

Currently, Sponge [force-closes any open screen](https://github.com/SpongePowered/SpongeForge/blob/stable-7/src/main/java/org/spongepowered/mod/mixin/core/server/management/MixinPlayerInteractionManager.java#L153-L158) when its `InteractBlockEvent` is cancelled. This makes sense when it's a plugin doing the cancellation, since we can't know what the client may have already done. However, our `InteractBlockEvent` is internally mapped to a `PlayerInteractEvent.RightClickBlock`. When Quark cancels the event on the server side, we end up sending a close packet, which isn't Forge's behavior.

One solution might be to track the Forge and Sponge cancellation statuses separately for this event. When a plugin cancels an `InteractBlockEvent`, we send a close packet - but when a mod does the cancellation, we assume that it wants the normal Forge behavior, which is to keep the window open.

I believe this should give us the most consistent results - Sponge protection plugins are still able to prevent clide-side GUIs from staying open when a player clicks a protected block, while mods are able to rely on the Forge behavior.

Pinging @bloodmc and @gabizou for input.

**Comment by gabizou** [comment]
I believe that is a safe solution to implement @Aaron1011, I'll agree to that.
