### ISSUE TITLE
Unable to respawn when AbyssalCraft is installed

### ISSUE THREAD

**Issue by avescarelo** [SpongePowered/SpongeForge#2130]
**I am currently running**

- SpongeForge version: 3064
- Forge version: 14.23.3.2655
- Java version: 1.8.0_72-b15
- Operating System: Windows/Linux

- Plugins/Mods:

Mods (32): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AbyssalCraft, Animania, Antique Atlas, AppleCore, Astral Sorcery, AutoRegLib, Baubles, BiblioCraft, Botania, Botaunomy, CraftStudio API, Earthworks, Example Mod, Hardcore Darkness, Hunger Overhaul, Iron Chest, Magical Psi, Nibbler, Potion Core, Psi, Quality Tools, Quark, Rustic, Tails, The Spice of Life, WorldEdit

Plugins (13): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, ActiveTime, AdminShop, EconomyLite, GriefPrevention, LuckPerms, Nucleus, Soulbound, TimeWarp, VoxelSniper

**Issue Description**
Player sleeping on the bed. Player broken the bed. Even player is died, pkayer is can't respawn.

Log: https://gist.github.com/pingvikin/235e4e85eb7b3732a1a5a9d92e956ec3

**Comment by JBYoshi** [comment]
My analysis:

When a player dies, Minecraft creates a new `EntityPlayerMP` object for them. If the player's bed is not obstructed, it will then copy the spawn point over to the new player object (and Forge fires a `PlayerSetSpawnEvent` in the process). It does not copy the spawn point, or fire the event, if the bed is obstructed, even though the spawn point is technically being changed to `null`.

Sponge changes this behavior. When the bed is obstructed, [Sponge first sets the spawn point to `null`](https://github.com/SpongePowered/SpongeCommon/blob/973c4012eaa945c90df7d89be687f1db3f201c3d/src/main/java/org/spongepowered/common/entity/EntityUtil.java#L702-L708) on the original player. Seeing this, Forge fires a `PlayerSetSpawnEvent` with a new value of `null`. Then, when the new player is created, Sponge [copies the spawn point over](https://github.com/SpongePowered/SpongeCommon/blob/973c4012eaa945c90df7d89be687f1db3f201c3d/src/main/java/org/spongepowered/common/mixin/core/entity/player/MixinEntityPlayerMP.java#L397) without firing a `PlayerSetSpawnEvent`.

AbyssalCraft currently [does not check](https://github.com/Shinoow/AbyssalCraft/blob/master/src/main/java/com/shinoow/abyssalcraft/common/handlers/PurgeEventHandler.java#L64) if `PlayerSetSpawnEvent.getNewSpawn()` is `null`, probably because it doesn't happen without Sponge.

I'm not sure which behavior is correct. To me, Sponge's behavior seems more natural, but mods (like AbyssalCraft) would have to adapt to the change.

**Comment by phit** [comment]
see also https://github.com/SpongePowered/SpongeCommon/pull/1601

IMO we should restore Forge functionality, relying on mods to patch their code for changes we introduced is unrealistic for things like this.

**Comment by Aaron1011** [comment]
This should be fixed in the latest SpongeForge.
