### ISSUE TITLE
Increased memory usage in unstable builds

### ISSUE THREAD

**Issue by MineyShadow** [SpongePowered/SpongeForge#2133]
- SpongeForge version: spongeforge-1.12.2-2655-7.1.0-BETA-3065
- Forge version: forge-1.12.2-14.23.3.2655-universal
- Java version: 8, 64-bit 1.8.0_141
- Operating System: Linux (Shared Hosting)
- Plugins/Mods: Sponge Only

[Server has 2 GB ram, installing sponge makes it use 1.5+/2 GB RAM, without it the server uses 0.6/2 GB]
Apparently the server starts fine, does not crash as far as i know but the memory usage steadily climbs up. There seems to be no CPU issues, just RAM. If sponge is removed from the mods folder there are no issues. I'm not sure if this is normal since old versions of sponge such as 1.11.2 sponge did not do this. [Tried re-installing forge manually but same result, same for using different versions of sponge(3063 to 3065)]

Here is the "debug" log.
https://gist.github.com/MineyShadow/473d0ef39fc0b7a568d4f16546f9842a

Edit: Usage rapidly increases until it stays around 1.5+ GB Ram, i also think the shared host controls this to this point so it can prevent more usage. Basically it feels more like sponge is using more ram than it used to.

**Comment by fhntv24** [comment]
SpongeForge / Forge / Plugins&Mods same as OP
Information gathered with JProfiler:
After starup server uses 1GB of memory ( After manual GC's )
After 5 minutes and calling manual GC again it dropped down to 1GB. Most of allocations are vanilla, and from entity doing it's things ( creating new ent's, AABB's for them ), and sponge creating tick events / etc. There is around 30K of objects being created per second, and is spiked to 100K when server auto-save's.

661 MB of memory is used by HashMap, at least for my world ( Most of it is Sponge ). Next one is jar's Attributes, but that is due to how large Minecraft is. https://snag.gy/9Zc1Du.jpg

Also Mixin's do not release ObjectWeb ASM class instances, or at least parts of it. As this is only takes about 20MB of memory this isn't critical ATM. https://snag.gy/MPHXvE.jpg

I could try running JProfiler for 30 minutes with allocation tracking - if there is any memory leak it should show where it is, but I don't think what that is required as after GC memory goes back to normal.

Also here is memory diff's from forge w/out sponge, with it after startup, and after running it for 120 minutes.
Forge -> Sponge: https://snag.gy/fHoBOg.jpg
Sponge -> 120 minutes in: 0 difference.
(Forge memory did include MC gui, but that is only because no-gui doesn't work for some reason)

So, as far as I can tell there is no memory leak's. While memory does go up in usage - this is normal for JVM, as all objects that wasn't collected in first pass are moved to "older" gen. It will do "massive" GC after some time, if it detects what there is not enough memory.

I will "Heap walk" later to find out where exactly HashMap's are being created.

I hope this helps.

edit:
While still running, after 2 hours server didn't use any additional memory that is measurable ( Less than 10 MB of memory diff. after GC's ). I will try SF 3002, and diff. with that. I think this should be renamed to "Increased memory usage in unstable builds", as no actual leaks are present.

Also I have public server that is running for 24+ hours without memory leaks on latest beta release.

**Comment by MineyShadow** [comment]
While my issue is not resolved, i thought maybe i could try using the older forge [forge-1.12.2-14.23.2.2611] along with its sponge [spongeforge-1.12.2-2611-7.1.0-BETA-3002] as a test. [No Mods and plugins of course]
Results:
It works fine with no issues, server uses 0.8/2 GB RAM, i can't use this old forge version however since some mods started relying on new versions.

**Comment by phit** [comment]
please test this without Sponge and just the Forge version that causes these issues

**Comment by MineyShadow** [comment]
Testing without sponge is also outlined in the first comment?

**Comment by phit** [comment]
sorry, missed that short sentence

**Comment by fhntv24** [comment]
@phit Diff. is also outlined in my comment ( with actual memory difference ).
Do you need help with searching where that HashMap's are ?
(Btw, memory usage looks like there is just tons of empty maps with default ratio. But I'm not 100% sure on this)

**Comment by gabizou** [comment]
There's thousands of usages of maps virtually everywhere in Java. Just saying that there's a bunch of them existing is equivalent to saying that there's Nitrogen in the air we breathe. Profiling for the *owners* is more important as it can potentially view into where objects are being allocated. 

After I manage to get #2110 squared away I can dedicate some time to isolating some memory usages, but if you manage to do some investigating yourself, I'd recommend giving YourKit a go for profiling memory usage.

**Comment by MineyShadow** [comment]
Thought i could try memory profiling, I'm quite new to it and don't know if i did it right but. [This was tested on my own computer and apparently using sponge+forge bumps the memory usage to 2 GB+ and hovers around that point while forge without sponge of course uses 0.6 GB]
![image](https://user-images.githubusercontent.com/37338176/39890396-19659990-54b4-11e8-9352-5d9a11a15044.png)

**Comment by gabizou** [comment]
Yeah, that still doesn't tell us where the hash maps are being stored or utilized. All it tells us is that there's more hash maps.

**Comment by bloodmc** [comment]
We reduced quite a bit of RAM usage in latest builds. If you experience issues with latest, provide a profile dump.
