### ISSUE TITLE
Performance issue with applyArmorDamage

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/SpongeForge#2138]
Tile entities which kill mobs like Mob Grinder from Draconic Evolution or Mob Relocator from Industrial Foregoing are causing performance issues when `applyArmorDamage()` is called.

I'm not sure if this is an issue in sponge or minecraft itself.

spongeforge-1.12.2-2611-7.1.0-BETA-3019

![](https://i.imgur.com/9fqlIbW.jpg)
![](https://camo.githubusercontent.com/18a81e4f13edab61ba32e4dedc865345e52d142b/68747470733a2f2f692e696d6775722e636f6d2f506e76336938482e6a7067)

**Comment by phit** [comment]
![image](https://user-images.githubusercontent.com/2097483/41935873-94e6d902-798b-11e8-8193-371c66c2ece9.png)

seeing the same issue on 7.1.0-BETA-3233

**Comment by gabizou** [comment]
I'm having a hard time accepting that this is Sponge causing issues. The code in question is specifically called by a tile entity attacking/killing entities, which will naturally call what MCP names: `ItemStack#attemptDamageItem` (which is the very last method listed in the profiling).

Sure, it can be a "performance" issue, but it's not caused by Sponge in the slightest, as you can see in the stack, the only actual sponge code here is the ` acceptance, and the wrapper for ticking the `TileEntity`.

It's not possible to identify the direct cause for the bit of code that is affecting the `ItemStack`, as there are several methods in that method calling and delegating to the `Item` of the `ItemStack`.

As far as the original first image showing the Enchantment code being processing unperformant, that's to be expected in this case if multiple entities are being killed while equipped with armor as the enchantments are being queried constantly.
