### ISSUE TITLE
tab complete throw an exception

### ISSUE THREAD

**Issue by azbh111** [SpongePowered/SpongeForge#2207]
**I am currently running**
- SpongeForge version:spongeforge-1.12.2-2655-7.1.0-BETA-3052.jar 
- Forge version: run/forge-1.12.2-14.23.3.2655-universal.jar
- Java version: java8
- Operating System:windows server 2016 , macOS
- Plugins/Mods: PlotSquared-Sponge-18.05.07-59e06c2-1988.jar

**Issue Description**
input "/plot kick" then key down the tab,nothing happen but throw an exception.
then I make a listener to prevent tabCompleteEvent of plotsquared,the code:

```java
@Service(successMessage = "PlotSquared tabcompletion has been disabled",
        needClass = "com.plotsquared.sponge.SpongeMain")
public class PlotSquaredFixer {
    List<String> prefixes = new ArrayList<>();

    public PlotSquaredFixer() {
        prefixes.add("p ");
        prefixes.add("ps ");
        prefixes.add("p2 ");
        prefixes.add("plot ");
        prefixes.add("plots ");
        prefixes.add("plotsquared ");
    }

    @Listener(order = Order.PRE)
    public void onTabCompleteEvent(TabCompleteEvent event) {
        String command = event.getRawMessage().toLowerCase();
        if (command.startsWith("2 ")) {
            event.setCancelled(true);
            return;
        }
        if (!command.startsWith("p")) {
            return;
        }
        for (String prefix : prefixes) {
            if (command.startsWith(prefix)) {
                event.setCancelled(true);
                return;
            }
        }
    }
}
```

"/plot" -> tab : work fine.
"/plot kick" -> exception
"/plot tp" -> excption

the server log
https://gist.github.com/azbh111/7abac518af97df5d9fcbabd00649aedb

**Comment by Aaron1011** [comment]
@azbh111 Can you post the source to the `CommandCallable` for the `plot` command?

**Comment by dualspiral** [comment]
@Aaron1011 [It's because they are returning null when getting suggestions](https://github.com/IntellectualSites/PlotSquared/blob/master/Sponge/src/main/java/com/plotsquared/sponge/util/SpongeCommand.java#L47-L66), and the [`ArrayList` constructor can't deal will nulls](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/java/util/ArrayList.java?av=h#151).

[We should guard against it here](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/command/SpongeCommandManager.java#L390) by checking for `null` and creating an empty list in that circumstance.

**Comment by azbh111** [comment]
the CommandCallable:
https://github.com/IntellectualSites/PlotSquared/blob/master/Sponge/src/main/java/com/plotsquared/sponge/util/SpongeCommand.java

**Comment by dualspiral** [comment]
I've provided a PR to fix it on their end: https://github.com/IntellectualSites/PlotSquared/pull/1986. 

Given we annotate `getSuggestions` with `Nonnull`, should we provide the null check? If not, then this is a plugin issue and should be closed, else, it won't be hard to fix this.
