### ISSUE TITLE
Unable to interact with EU2 shady villagers

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/SpongeForge#2222]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3163.jar
- Forge version: 14.23.4.2707
- Java version: 1.8.0_172
- Operating System: Windows 7

- Plugins/Mods:
SpongeForge + extrautils2-1.12-1.7.6.jar

**Issue Description**
Start single player world
Spawn a villager until you get a Shady villager or Red priest from ExtraUtilities2.
Right click the villager to select your trade
Expected result: GUI is opening
Observed result: no GUI opening, no logs, nothing

Issue was initially observed on FTB Continuum

https://gist.github.com/LemADEC/3cf81c02f104cd68a9d460b4bb3b0541

**Comment by Aaron1011** [comment]
This is caused by the fact that ExtraUtils2 [doesn't use Forge's `VillagerCareer#addTrade`](https://github.com/rwtema/Extra-Utilities-2-Source/blob/5a84281cff5542b7f63353823564147f36db368a/1.10.2/src/main/java/com/rwtema/extrautils2/villagers/XUVillagerCareer.java). Instead, it overrides `getTrades`, and uses its own system for determining the trades for a given level.

@gabizou: On one hand, there's no real reason for ExtraUtils2 to be doing this - it could easily call `addTrade` and skip using two separate lists. On the other hand, `VillagerCareer#getTrades` is non-final, so we should probably support this (especially considering that there's little change of ExtraUtils2 changing its behavior in the future).

**Comment by LemADEC** [comment]
As of 
    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-SNAPSHOT-d453c3e
    SpongeForge: 1.12.2-2705-7.1.0-BETA-3186
    Minecraft Forge: 14.23.4.2707
Issue is still reproduced

**Comment by LemADEC** [comment]
Using    SpongeForge: 1.12.2-2705-7.1.0-BETA-3189
Issue is still reproduced

**Comment by gabizou** [comment]
I forgot to mention, you need to re-create the villagers as they may have empty merchant lists already created, because I just downloaded 3188 and it works:

<img width="800" alt="screen shot 2018-06-15 at 8 02 05 pm" src="https://user-images.githubusercontent.com/1203877/41495221-1ce8f08c-70d7-11e8-889e-0a860c800262.png">

And for further reference, went and downloaded the latest:
<img width="983" alt="screen shot 2018-06-15 at 8 06 24 pm" src="https://user-images.githubusercontent.com/1203877/41495241-a7f1d018-70d7-11e8-8604-70581aac39f2.png">

**Comment by LemADEC** [comment]
ok, it does work with 3189, thanks!
