### ISSUE TITLE
Movement Module crash with other mods

### ISSUE THREAD

**Issue by JoeSGT** [SpongePowered/SpongeForge#2244]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3212 
- Forge version: 1.12.2-14.23.4.2705
- Java version:  8
- Operating System: Windows 10

- Plugins/Mods:
spongeforge-1.12.2-2705-7.1.0-BETA-3212 
plethora-1.12.2-1.1.11
cc-tweaked-1.80pr1.5

**Issue Description**
Just go on global.conf and enable movement module and you will crash 
[crash-2018-06-19_22.00.07-server.txt](https://github.com/SpongePowered/SpongeForge/files/2117515/crash-2018-06-19_22.00.07-server.txt)

**Comment by Aaron1011** [comment]
@phit: I wouldn't say that this is 'high priority', since this mixin just disables some annoying Vanilla messages (and can be disabled in the config). However, I'll take a look.

**Comment by Aaron1011** [comment]
This crash happens without either of those mods installed. It appears to happen only in production - it seems to be a problem with the `@ModifyConstant` injector.

**Comment by Aaron1011** [comment]
Fixed in https://github.com/SpongePowered/SpongeForge/commit/e80cb0e1f1ba783cd996fe826f4254d5b7f94aa4.

This was a really weird issue. The `BeforeInvoke` ordinal was wrong this entire time, but it worked anyway until commit https://github.com/SpongePowered/SpongeCommon/commit/d05b375618ccc38b980ddbbdef01a03f32a6a037 bumped our Mixin version to include https://github.com/SpongePowered/Mixin/commit/d7d1d37ffeb58aa313dc62f0f72bc96c18613221, which changed the behavior of `Slice`s with an unresolved `to` target.

Then, the wrong ordinal continued to accidentally work in development, due to https://github.com/SpongePowered/Mixin/issues/266.

**Comment by Aaron1011** [comment]
Slightly unrelated: Debugging this issue lead me to submit https://github.com/MinecraftForge/MinecraftForge/pull/4989, since I was having trouble running Plethora in my IDE.
