### ISSUE TITLE
The PhaseState having an exception: EntityTickPhase: (Galacticraft and null UUIDs)

### ISSUE THREAD

**Issue by cestofmir** [SpongePowered/SpongeForge#2261]
**I am currently running**
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3206
- Forge version: 1.12.2 - 14.23.4.2705
- Java version: Assumed to be latest, handled by the host "ShockByte"
- Operating System: Windows 10 Pro

- Plugins/Mods: https://i.imgur.com/02gZK7Q.png

**Issue Description**
Galacticraft adds new dimensions to minecraft, which are accessed through launching a rocket into space until you hit around Y1200. Normally, would bring one to a planet selection GUI. 

The issue which I am facing is that the rocket despawns when it's supposed to advance to the planet selection GUI, and the player simply falls back down to the ground in the overworld. 

I also did notice though that many dimensions have "null" UUIDs. I am not sure what is causing this or how to fix it. 

Full server log:
https://gist.github.com/cestofmir/63c9d39a38b61079af2b4685ca65eb58

Specific issue:
https://gist.github.com/cestofmir/8bd1c3db7ddc1bd78cc7ef5d2fa21cd2

**Comment by gabizou** [comment]
For reference, it looks like it's this line here:
https://github.com/micdoodle8/Galacticraft/blob/9bbb881405ea947de611929dc674fc37538ad10c/src/main/java/micdoodle8/mods/galacticraft/core/util/WorldUtil.java#L220

I'm not sure whether @radfast could provide some insight, but I'm not familiar enough with all the checks and "requirements" for what states some things can be in for that line to fail like it is currently.

**Comment by radfast** [comment]
hey @gabizou  :)

@cestofmir this is a crash in Galacticraft code which Sponge has trapped.  I'm not sure that it's a Sponge issue at all.  Please can you open an issue on the [Galacticraft issue tracker](https://github.com/micdoodle8/Galacticraft/issues) for now, so that our messages to try to resolve this don't create a whole bunch of extra emails for the Sponge guys.

I suggest this can be closed.  (If it turns out to be a Sponge issue after I've investigated it further, I'll open a fresh issue report here.)

**Comment by cestofmir** [comment]
@radfast Thanks, I'll do that.
