### ISSUE TITLE
ITeleporter cannot be cast to org.spongepowered.api.world.PortalAgent

### ISSUE THREAD

**Issue by wormzjl** [SpongePowered/SpongeForge#2266]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3243
- Forge version: forge-1.12.2-14.23.4.2725-universal
- Java version: 1.8.0_144
- Operating System: linux

- Plugins/Mods:
 Mods (260): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, AI Improvements, ATM Tweaks, Actually Additions, Actually Baubles, Additional Banners, Advanced Generators, Advanced Rocketry, Akashic Tome, AngelRing 2 Bauble, AppleCore, AppleSkin, Applied Energistics 2, Armory Expansion, Aroma1997's Dimensional World, Aroma1997Core, Astral Sorcery, AutoRegLib, Autoverse, BD Lib, Bad Wither No Cookie! Reloaded, Baubles, Bed Patch, Better Builder's Wands, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Blockcraftery, Bookshelf, Botania, Brandon's Core, Ceramics, Chameleon, Chisel, Chisels & Bits, CoFH Core, CoFH World, CodeChicken Lib, Colossal Chests, CommonCapabilities, Compact Machines 3, ComputerCraft, Computronics, Construct's Armory, CosmeticArmorReworked, CraftTweaker JEI Support, CraftTweaker2, Crafting Tweaks, Cucumber Library, Cyclic, Cyclops Core, Dark Utilities, Default World Generator, Diet Hopper, Dismantler, Doomlike Dungeons, Draconic Evolution, EXCore, EluCore, EluLib, Embers, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Environmental Tech, Extra Cells 2, Extra Rails, Extra Utilities 2, Extreme Reactors, FTB Utilities, FTBLib, Fairy Lights, FastWorkbench, Fence Jumper, Flat Colored Blocks, FoamFix, FoamFixCore, Forestry, Forge Microblocks, Forge Multipart CBE, Funky Locomotion, GenDustry, Gotta Go Fast, Guide-API, Guidebook, Harvest, HelpFixer, Immersive Engineering, Immersive Petroleum, Industrial Foregoing, Industrial Wires, IndustrialCraft 2, InitialInventory, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Integration Foregoing, Inventory Generators, Inventory Tweaks, Iron Backpacks, Iron Chest, JAOPCA, Just A Ore Processing Compatibility Attempt: Additions, Just Enough Dimensions, Just Enough Items, KJ Lib, KleeSlabs, LibrarianLib, LibrarianLib Stage 2, Lost Souls, MCMultiPart, MTLib, MagicBees, Magical Psi, Mantle, McJtyLib, Mekanism, MekanismGenerators, MekanismTools, MineColonies, Minecraft Multipart Plugin, Mob Totems, Mod Tweaker, Morph-o-Tool, Morpheus, MrTJPCore, Mystical Agradditions, Mystical Agriculture, Natura, Nature's Compass, No Mob Spawning on Trees, Not Enough Items, Not Enough Wands, NotEnoughIDs, NuclearCraft, Nutrition, OpenBlocks, OpenComputers, OpenComputers (Core), OpenComputers Xnet Driver, OpenModsLib, OpenModsLib Core, OreDictInit, OreExcavation, OreExcavation Integration, Overloaded, PackMode, Placebo, Platforms, PlusTiC, PneumaticCraft: Repressurized, PortalGun, Portality, Practical Logistics 2, Pressure Pipes, ProjectRed Core, ProjectRed Expansion, ProjectRed Exploration, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Relocation, ProjectRed Transmission, ProjectRed Transportation, ProjectRed integration, Psi, QuantumStorage, Quark, Quick Leaf Decay, RFTools, RFTools Control, RFTools Dimensions, RFToolsPower, RandomPatches, Ranged Pumps, Real Filing Cabinet, Reborn Core, RebornStorage, Redstone Arsenal, Redstone Flux, Refined Storage, Refined Storage Addons, Reliquary, Rockhounding Mod: Chemistry, Rockhounding Mod: Core, Roots 2, Rustic, ShadowMC, Shadowfacts' Forgelin, ShetiPhian-Core, Shield Parrying, Simply Jetpacks 2, SlimyBoyos, SonarCore, Soul Shards - The Old Ways, Steve's Carts 2, Storage Drawers, Storage Drawers Extras, TOP Addons, Tech Reborn, Tesla Core Lib, Tesla Core Lib Registries, Thaumcrafft Inventory Scanning, Thaumcraft, The Lost Cities, The One Probe, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinker I/O, Tinkers Tool Leveling, Tinkers' Construct, Tomb Many Graves, TombManyGraves2 API, Traverse, UniDict, Universal Modifiers, Useful Nullifiers, Valkyrie Lib, Vulpes library, WAIM, WanionLib, Water Strainer, Waystones, Wireless Crafting Terminal 2, WirelessCharger, Woot, WrapUp, XNet, Xtones, YNot, Zero CORE, asielib, careerbees, iChunUtil, p455w0rd's Library, projectred-compat

Plugins (13): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge,  FastAsyncWorldEdit, AdamantineShield, Holograms, MagiBridge, Nucleus, Nucleus Gluon, PlaceholderAPI, WorldEdit, spark

**Issue Description**
Not sure how it has happened but I find this in my crash logs

https://gist.github.com/wormzjl/e9330cafc7b71ff3cf9530c3ba466a4f

**Comment by Martmists-GH** [comment]
[Crash log](https://hastebin.com/apibahizay.java)

Context:
Using FTB Utilities commands that teleport you to change dimensions causes this crash.

**Comment by Zidane** [comment]
@aaron1011 look into this please.

**Comment by tgstyle** [comment]
My server did not crash but it did give this error when executing the home command, maybe it will help.

https://gist.github.com/tgstyle/8ce09ef1a18e2a18170ac5219be91126

**Comment by LordRalex** [comment]
@Aaron1011 @Zidane the issue here is that the PortalAgent interface isn't being mixin'ed to the ITeleporter class, rather to the Teleporter class that's above it. 

Since modders can now access that ITeleporter class and not implement Teleporter, the agent isn't applied to their new classes (as it's not in the stack), and so when Sponge force-casts to run it to PortalAgent, it fails. 

https://github.com/SpongePowered/SpongeForge/blob/stable-7/src/main/java/org/spongepowered/mod/mixin/core/common/MixinSpongeImplHooks.java#L345 specifically is what fails.

It seems like just having do a check to see if it is a portal agent would work around it, but does there need to be registration that occurs for these teleporters?

**Comment by gabnerd69** [comment]
Having this issue on the server i am playing on any update on status of possibly fixing this issue its frustrating when everything is running smooth then someone decides to do /home from the nether and crashes everything

**Comment by LordRalex** [comment]
The stacktrace also reveals there's more code that later on will fail even after that method is changed.

https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/entity/EntityUtil.java#L440

A second call later also assumes it's a PortalAgent. It looks like it'd fail as well.

One of the big assumptions that it seems like is being made is that all teleports are related to portals.  Change dimension assumes that all teleports are portal events, so we're assuming it's portals doing stuff here, and that code may not be accurate with modders now using ITeleporter.
https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/entity/EntityUtil.java#L219

Simply skipping the call won't work here, since it does force casting elsewhere, unless it skipped and it also chose to trigger the parent event instead of the portal event. However, I think that's an API-level question on how it should be answered.

**Comment by Keaton1188** [comment]
@Aaron1011 I know this thread is old but did you get a chance to take a look at it?

**Comment by takarabako** [comment]
With the current fix applied `teleporter.placeEntity()` is not called because it failed the
`teleporter instanceof IMixinTeleporter` check [at this line](https://github.com/SpongePowered/SpongeCommon/blob/c3bf48aae09ff3b62036331b69080b816bb25e3b/src/main/java/org/spongepowered/common/entity/EntityUtil.java#L412).

**Comment by Wissi** [comment]
Having same problem as  issue #2555 
Any progress so far? Just curious by no means impatient.

Thank you for looking into it.

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/SpongeCommon/commit/e4ab02080411f211eb2e9afd654174e5e691ecca
