### ISSUE TITLE
Nether Utils UnexpectedBlockChange

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeForge#2271]
**I am currently running**
- SpongeForge version: 7.1.0-BETA-3259 
- Forge version: 2705

- Plugins/Mods:
NetherUtils-1.12-1.4.22.jar
TerraCore-1.12-2.1.13.jar

**Issue Description**
create new world, watch console
https://gist.github.com/phit/c15ed6eecb6f511f36d3267983cf9619

**Comment by phit** [comment]
probably same as https://github.com/SpongePowered/SpongeForge/issues/2007

**Comment by gabizou** [comment]
I've an idea on how to fix this. Though, it's a little interesting. I'll have to revisit the branch https://github.com/SpongePowered/SpongeCommon/tree/refactor/merge-frames-and-states to resolve listeners and basically expect forge event listeners to be considered "capturable" or "trackable" in some way. Definitely a bug on our end it looks like, as the main thread check has already since been passed if it's getting to the phase context check.

**Comment by phit** [comment]
doesnt seem to error anymore, i think this was fixed with https://github.com/SpongePowered/SpongeForge/commit/85cf30cdb10e1e78ebc31bfc20f4db9163f51fb1
