### ISSUE TITLE
Ore Excavation mod broken after update

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/SpongeForge#2274]
After updating SpongeForge from 3247 to 3262 using Ore Excavation breaks the blocks but does only drop one block.
Same issue with 3266.

![](https://i.imgur.com/dciAfHg.gif)

**Comment by gabizou** [comment]
Is there a specific build this breaks with?

**Comment by Sir-Will** [comment]
Yes but I didn't go through the builds to find which one, only got the range which I mentioned in the issue.

**Comment by Aaron1011** [comment]
This issue is that OreExcavation explicitly sets Forge's `World.captureBlockSnapshots` field to `true`, and checks `World.capturedBlockSnapshots` after calling `PlayerInteractionManager.tryHarvestBlock`.

Sponge needs to properly add to `World.capturedBlockSnapshots` in our `setBlockState` rewrite.

**EDIT**: While this is necessary to make 'undo' support work in Ore Excavation, it doesn't appear to be the cause of the main issue.

**Comment by Aaron1011** [comment]
This should be fixed in the next SpongeForge build.

**Comment by Sir-Will** [comment]
Yep, works again, thanks.
