### ISSUE TITLE
Crash on updateWorldGenerator

### ISSUE THREAD

**Issue by Tencao** [SpongePowered/SpongeForge#2331]
**I am currently running**
- SpongeForge version: 2705-7.1.0-BETA-3328
- Forge version: 14.23.4.2705
- Java version: 8
- Operating System: Windows 10

- Plugins/Mods: Unable to get full list due to server not starting, but the main mod seems to be Streams

**Issue Description**
As the server starts up, even on a fresh world I'm met with an immediate crash. This did work on the recommended build of sponge, but not the latest

Crash Report - https://gist.github.com/Tencao/f3933019fe7329acf93509fc0176f6df
Full Log - https://gist.github.com/Tencao/22194c24ba8f82028f53f316147c50fa

**Comment by gabizou** [comment]
Looks like Farseek is trying to use reflection to do something with Sponge’s world generation. If we change our interfaces, for our implementation, and someone else relies on it, it’s their fault. 

Link to offending code: 
https://github.com/delvr/Farseek/blob/1.12/src/main/scala/farseek/world/gen/structure/StructureGenerationChunkProvider.scala#L34

To be completely honest, I understand wanting to use Sponge's code to sync it back up, but there's better ways to do this, i.e. depending on the interface `IMixinWorldServer` as an optional interface, and just surround with a try catch of sorts. Using reflection as it is isn't recommended because of potential renames like this.
