### ISSUE TITLE
Spongeforge 3361+ at least won't load with forge 2739 

### ISSUE THREAD

**Issue by limbo-app** [SpongePowered/SpongeForge#2370]
This issue was originally submitted by @trender7 in [SpongePowered/SpongeCommon#2049](https://github.com/SpongePowered/SpongeCommon/issues/2049).
___
**I am currently running**

- SpongeForge version: 3361
- Java version: 8
- Operating System: windows 10

- Plugins/Mods:  sponge wont load

**Issue Description**
Sponge 3361 wont load with Forge 2739.
I can for example use Sponge 3206 and it loads.
But latest sponge it just won't load like if u didnt put the .jar, also tried beta versions and the same. 3206 works fine. Modpack is enigmatica 2

**Comment by Trillo7** [comment]
You can try this faster and better explained: 
You can download i.e a modpack Im using enigmatica 2, latest version uses forge 2739.
I run the server and then install sponge in the mods folder. I run the server again and it just runs it like if you didn't even put the sponge jar file there.  
Just do the same but with Sponge 3206 and it will load sponge.

**Comment by gabizou** [comment]
Forge made breaking changes that we can't upgrade to because Forge's recommended build is 2705. SpongeForge is built against Forge 2705. We're not going to break the recommended usage availability or maintain two forks for compatibility. Since the Forge build is newer than the recommended, we can't provide support for it as it would break compatibility with the actual recommended build. Sorry.

**Comment by ryantheleach** [comment]
@Trender7 Thanks for the notification, Additionally I just tested with forge-1.12.2-14.23.4.2747-universal.jar vs spongeforge-1.12.2-2705-7.1.0-BETA-3375.jar

Loaded fine. Without logs I can't diagnose your true issue, (but yes, I used newer versions of both then you, so we could have different results)

**Comment by ryantheleach** [comment]
[latest.log](https://github.com/SpongePowered/SpongeForge/files/2264790/latest.log)
[2018-08-07-1.log.gz](https://github.com/SpongePowered/SpongeForge/files/2264791/2018-08-07-1.log.gz)
[debug.log](https://github.com/SpongePowered/SpongeForge/files/2264792/debug.log)
[debug-1.log.gz](https://github.com/SpongePowered/SpongeForge/files/2264793/debug-1.log.gz)

**Comment by Trillo7** [comment]
@ryantheleach oh well then thats weird.
I also tried same versions as you and mine still didnt load sponge hmm.
3206 loaded.
I could load 3361 with that good old SpongeBootstrap, but some plugins are bugged and doesnt work.
Ill upload the debug.log then (witouth the bootstrap, it doesnt load sponge newer versions huh); then I guess it must be some mods of the modpack, kinda weird because older sponge loads just fine

**Comment by Trillo7** [comment]
[2018-08-07-4.log.gz](https://github.com/SpongePowered/SpongeForge/files/2264836/2018-08-07-4.log.gz)
[debug.log](https://github.com/SpongePowered/SpongeForge/files/2264837/debug.log)
[debug-1.log.gz](https://github.com/SpongePowered/SpongeForge/files/2264838/debug-1.log.gz)
[latest.log](https://github.com/SpongePowered/SpongeForge/files/2264839/latest.log)

**Comment by ryantheleach** [comment]
@trender7 You have a known issue due to a version conflict of Mixin between Sponge and MalisisCore. 

See https://github.com/SpongePowered/SpongeForge/issues/2254 https://github.com/SpongePowered/SpongeForge/issues/2351

This issue will be fixed for good if https://github.com/SpongePowered/SpongeForge/pull/2252 is validated to work correctly and pulled.
