### ISSUE TITLE
MKUltra Skills cannot be used on a sponge server

### ISSUE THREAD

**Issue by luenlin** [SpongePowered/SpongeForge#2372]
Some of the professional skills are not working properly on the Sponge Server.
For example, Druid's Ball Lightning and Flame Blade, Phoenix Aspect.
The specific performance is that the potion effect cannot be correctly given.

**Comment by ryantheleach** [comment]
@luenlin Please follow the issue template, it's actually rather important if you want to get dev attention to fix your issue.

Even if you think "Oh it's pretty easy if they spend 30m to google and download things" it could be weeks before we see it, and by that time versioning info is out of date.

(It's especially going to be weeks, as the team prioritizes bugs and issues that are well written, and easily replicated because they don't like wasting their time)

Edit this issue with the required details / template, and I'll reopen and remove this comment.
