### ISSUE TITLE
Dimensional Pockets 2 startup crash

### ISSUE THREAD

**Issue by xingcheng2** [SpongePowered/SpongeForge#2381]
**I am currently running**

- SpongeForge version: 
- Forge version: 
- Java version: 
- Operating System:

- Plugins/Mods:

**Issue Description**

With regard to using with Dimensional-Pockets, once this MOD is added, the server can't start!
But if you delete spong or Dimensional-Pockets, then the server will start.
It is emphasized that the two can not be used together, but once it is used, it cannot start.
I begged the author to correct this BUG?
This is the wrong document：

https://gist.github.com/phit/0ac9f7d1e1009cdfcf1e86b3ef8590ea

**Comment by xingcheng2** [comment]
When loading DIM98 world, BUG appears!

**Comment by phit** [comment]
still an issue 
https://gist.github.com/phit/d274a7f68ef1e1e97ad9ebf4d3fbaec6
spongeforge-1.12.2-2768-7.1.5-RC3513.jar

**Comment by gabizou** [comment]
So, I'm not sure why, but here's what I've found:
[Dimensional Pockets 2 is initializing it's biome provider for the Pocket Dimension](https://github.com/TheRealZeher/DimensionalPockets-II/commit/240a6e56eca1a6cd52efd99ad6e054a3bcb5c048#diff-57d4797417718ba3164ddbb22993cfb8R74) in source on GitHub, but none of the releases [on CurseForge](https://minecraft.curseforge.com/projects/dimensional-pockets-ii/files) appear to have that initialization, which is required since the biome will otherwise be null. Likewise, it seems as though the various releases are erroneous in not having some updated classes to respect what is showing on GitHub. I've tested this without sponge and of course, this will work because Dimensional Pockets 2 will be able to do it's own awkward dimension creation and handling directly. 

Investigating further, it's a mystery how the release versions are functioning compared to the source on GitHub, but I've found a solution: changing `load-on-startup` to false for the dimension would resolve the issue of the world crashing due to the biome provider being null, because as previously mentioned, there's a huge difference of the code that is being distributed in production versus the code that exists on GitHub.


~~Short of saying "disable `generate-spawn-on-load` and `load-on-startup`", I can't think of another way to fix this. There's a small chance that @Zidane or @bloodmc may need to review how we manage Worlds and how mods are registering dimensions, but these systems are complicated as is.~~

Edit: I believe I've understood what's going on now. Sponge will treat mod dimensions having `shouldLoadSpawn` as `true` to mean `shouldLoadOnStartup`. I'm in belief this is an error on our part as well as the fact that Sponge is telling worlds to re-initialize with properties every time they are loaded, when the vanilla cases are only being done on server load. Will test with some more changes.
