### ISSUE TITLE
keepondeath incompatible with Corail Tombstone

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/SpongeForge#2383]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3383
- Forge version: 14.23.4.2749
- Java version: "1.8.0_171"
- Operating System: CentOS

- Plugins/Mods:
aether_legacy-1.12.2-v3.2.jar
tombstone-2.10.2-1.12.jar
spongeforge-1.12.2-2705-7.1.0-BETA-3383.jar
LuckPerms-Sponge-4.2.67build727.jar
Nucleus-1.5.2-S7.0-MC1.12.2-plugin.jar
forge-1.12.2-14.23.4.2749-universal.jar

**Issue Description**
Players inventory gets deleted on death when they have nucleus.inventory.keepondeath and Corail Tombestone is installed, while player has content in his alternate inventories (Baubles or Aether legacy).

Steps to reproduce:
1- set your perm for nucleus.inventory.keepondeath = true
2- add a stack of stone into your inventory
3- add gloves into your Aether inventory (open inventory then click the cloud icon)
4- die (/suicide for example)
5- expected inventory remaining unchanged
=> in practice, your inventory is empty with just a tombstone key = error 1
6- upon opening your gravestone, everything should be restored
=> in practice, only Aether gloves were restored = error 2

no specific logs in sight

**Comment by dualspiral** [comment]
Simplified code that causes this:

```java
@Listener
public void onEntityDeath(DestructEntityEvent.Death event) {
    event.setKeepInventory(true);
}
```

**Comment by ghost** [comment]
Tombstone only handles "player drop event" for this and checks for this rule, so i suppose my mod isn't involved in this issue and is only related to "sponge"

**Comment by ryantheleach** [comment]
"Players inventory gets deleted on death when they have nucleus.inventory.keepondeath and Corail Tombestone is installed"

Whilst this seems like unintended behavior, I'd think from 1st principals that nucleus keepondeath and a gravestone like mod would be incompatible.

What is the expected behavior?

You essentially have a conflict between 2 mods, both fighting for what should happen on death.

One wants your inventory to stay with you during death.

The other is trying to make sure it ends up in a chest. 

They can't both win, or else you would end up with a duplication issue.

**Comment by LemADEC** [comment]
It's quite frequent for mods to add keepinv or soulbound effect on death. They work together, that's the whole point of Forge. I don't understand why Sponge wouldn't be able to do it.

Last time I've checked, a Gravestone mod works by saving the player inventory and deleting its content during the death event, then restoring the 'soulbound/keepinv' items when player is respawning.
Depending on the set priority on the event handler, one can override the effect of another mod.
How comes we end up with a deleted inventory here? Do we have an event handler assuming is the only one handling player inventory? Does force world setting while the other expect another value? etc.

**Comment by ghost** [comment]
Tombstone never tries to force a grave, and let others mods do what they want before.
If a grave is generated it's because gamerule is not set to true (my event is only in the drops event...)
And in forge, if the gamerule is set to true (and if i'm right indeed), the drop event isn't triggered at all, even with receiveCanceled to true.

**Comment by ryantheleach** [comment]
```
package au.id.rleach.testkeepinventory;

import com.google.inject.Inject;
import org.slf4j.Logger;
import org.spongepowered.api.Sponge;
import org.spongepowered.api.command.CommandResult;
import org.spongepowered.api.command.CommandSource;
import org.spongepowered.api.command.args.CommandContext;
import org.spongepowered.api.command.args.GenericArguments;
import org.spongepowered.api.command.spec.CommandSpec;
import org.spongepowered.api.event.Listener;
import org.spongepowered.api.event.entity.DestructEntityEvent;
import org.spongepowered.api.event.filter.IsCancelled;
import org.spongepowered.api.event.game.state.GameInitializationEvent;
import org.spongepowered.api.plugin.Plugin;
import org.spongepowered.api.text.Text;
import org.spongepowered.api.text.format.TextColors;
import org.spongepowered.api.util.Tristate;

@Plugin(
        id = "testkeepinventory",
        name = "Testkeepinventory",
        description = "tests the keep inventory gamemode",
        authors = {
                "ryantheleach"
        }
)
public class Testkeepinventory {

    @Inject private Logger logger;

    boolean status = false;

    Text keepInvKey = Text.of("setKeepInventory");

    @Listener
    public void onGameInitialization(final GameInitializationEvent event) {
        Sponge.getCommandManager().register(
                this,
                CommandSpec.builder().arguments(GenericArguments.bool(keepInvKey)).executor(this::status).build(),
                "keepInventory"
        );
    }

    private CommandResult status(final CommandSource commandSource, final CommandContext commandContext) {
        final boolean status = commandContext.<Boolean>getOne(keepInvKey).get();
        this.status = status;
        commandSource.sendMessage(Text.of(TextColors.GREEN, "Setting KeepInv to " + status));
        logger.warn("Setting KeepInv to " + status);
        return CommandResult.success();
    }

    @Listener @IsCancelled(Tristate.UNDEFINED)
    public void onDropItem(final DestructEntityEvent.Death event) {
        event.setKeepInventory(status);
        logger.warn("Entity Destructing, cancelled: "+event.isCancelled());
        logger.warn("Entity Destructing, keepInv: " + status);

    }
}
```
[testKeepInv-1.0-SNAPSHOT.jar.zip](https://github.com/SpongePowered/SpongeForge/files/2300364/testKeepInv-1.0-SNAPSHOT.jar.zip)

**Comment by ghost** [comment]
Thanks Ryan, i made some tests with it : 
- first, my mod works as intended with gamerule keepInventory on forge (the event isn't triggered when the gamerule keepInventory is true)
- then, with the ryan's mod & my mod, i made tests on spongeForge to print the gamerule value (based on the player world) :
[Screen of the output](https://media.discordapp.net/attachments/480722280973074443/480764082866225178/test2.jpg?width=729&height=411)
With the gamerule set to true : the drop event is triggered (that's why my mod shows a golden message about no drop to create a grave) unlike forge that doesn't trigger it, and the gamerule value is false (based on the player world) unlike ryan's mod that shows it's set to true.
NB : i made the tests on the exact version of the initial issue and also with the latest sponge beta (same trouble)

**Comment by Faithcaio** [comment]
Ok so..
`DestructEntityEvent.Death#setKeepInventory` does not set the gamerule it just makes it so the player inventory is not cleared and so no items are dropped. 
The `PlayerDropsEvent` is then fired by Sponge with an empty drops list.
Then baubles adds its items to that the list. [see here](https://github.com/Azanor/Baubles/blob/master/src/main/java/baubles/common/event/EventHandlerEntity.java#L153)
Which is then picked up by the grave.

Easy way to fix it would probably be to just temporarily set the global gamerule.
