### ISSUE TITLE
XP bug

### ISSUE THREAD

**Issue by yaroslav4167** [SpongePowered/SpongeForge#2388]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3406

- Plugins/Mods:
Mods (8): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Hammer Core, Improvable Skills
Plugins (4): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge

**Issue Description**
Earlier I already discovered a similar problem #2168 .
Now this problem with Improvable Skills 3.
**Without a spongeforge, the bug does not appear.** (Forge-server)
[Video reproduction](https://youtu.be/MGEPPb8hD90)

**Comment by RedNesto** [comment]
I can confirm, tested with stable-7 in my development env.

It seems something internally ignores XP changes made by the mod, so earning XP after storing it will rollback the level and add earned XP to it (at least from the client view), all of that without removing XP from the book.
Rollbacks also happens when XP is withdrawn from the book: if you have no XP and withdraw 2 times 10 levels then get XP, it will go back to 10 levels.

**Comment by RedNesto** [comment]
After some searches, there is no way in Forge to be fully aware of experience changes since there is no dedicated method to remove XP (only a method to add, which seems to not work with negative values). As a workaround, modders change directly the experience fields values manually, but Sponge has no way to listen to field values changes.

A workaround would be to recalculate experience when a `SPacketSetExperience` is sent to the client, but Improvable Skills handles XP bank usage differently by using a packet sent to the client with all its custom data in it (including the XP changes).

I have a fix that have to be applied to Sponge and Improvable Skills, but it will have to be accepted by the mod's developer in order to work.

I found the issue has been reported on his side too. [Here it is](https://gitlab.com/DragonForge/ImprovableSkills/issues/14).

**Comment by yaroslav4167** [comment]
Is it possible to correct such errors in modifications without the participation of their developers?
There are many such mods. And turn to everyone about correcting this error.. It will be difficult.
Is there a simpler solution?

**Comment by RedNesto** [comment]
It needs the developer's participation because for now changes made by the mod are absolutely invisible to Sponge.

I tried to only have a fix for Sponge, but what I found requires the mod to send experience in a separate (vanilla) packet. So their participation is needed to make sure informations are sent with vanilla tools.

**Comment by yaroslav4167** [comment]
Can you compile a modification with a fix?
The developer of Improvable Skills has not done anything yet, and it's inconvenient to play with such a mistake.

I'm not strong in Java, especially in sending packets. =c
