### ISSUE TITLE
Sponge removing FTB Utilities chat prefix/color

### ISSUE THREAD

**Issue by Dinip** [SpongePowered/SpongeForge#2421]
**I am currently running**

- SpongeForge version: 2705-7.1.0-BETA-3361
- Forge version: 14.23.4.2750
- Java version: 1.8.0_181
- Operating System: Ubuntu 16.04

- Plugins/Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, FTB Utilities, FTBLib, Just Enough Items

**Issue Description**
I have ranks configured in FTButilites with some permissions for chunk claiming, chat name color, etc... the problem is when I add sponge the chat unformats and removes the colors. I'm not using any other plugin to change chat prefix/sufix, only ftb utilities and spongeforge. There are 2 screenshots. The first one is without sponge, the second is with sponge.
![image](https://user-images.githubusercontent.com/141554/47483008-afff7200-d87f-11e8-8228-47857366983b.png)

![image](https://user-images.githubusercontent.com/141554/47483022-b392f900-d87f-11e8-8f02-3f31149eee8b.png)

Log FTBUtils + SpongeForge: https://gist.github.com/Dinip12/3f28606ae61d21ad90fc71f5de7528af
Log FTBUtils only: https://gist.github.com/Dinip12/b2127a2815d043e341f3b54769ca4d34

**Comment by Magesw** [comment]
I have the same issue, added SpongeForge to both a Stoneblock 1.0.23 and FTB Sky Adventures pack and it stripped all color from my chat as well as conflicting on the StoneBlock server with commands like /home.

**Comment by ryantheleach** [comment]
@Magesw 
>as well as conflicting on the StoneBlock server with commands like /home.

Sponge doesn't create commands like `/home` It's more then likely a plugin or multiple mods that is clashing. 

If you have an issue with commands other then 'clashing' you may want to create (or find a relevent)ticket for it rather then hijacking this one. 

See the section labelled Command Conflicts for assistance in solving your problem with commands:

https://docs.spongepowered.org/stable/en/server/spongineer/commands.html?highlight=conflicts#operator-commands

----------

## Colors

Looking at FTB Utilities issue tracker, the name format not being applied may be symptomatic of the rank itself not applying? Otherwise people may have seen the lack of color and assumed it to be that the rank wasn't applying.

**Comment by phit** [comment]
yeah still not working and the rank does apply

![](https://i.imgur.com/eZngvND.png)

spongeforge-1.12.2-2768-7.1.6-RC3586.jar
FTBLib-5.4.1.84.jar
FTBUtilities-5.3.0.82.jar

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/SpongeForge/commit/2ab93ca820a374c92994942d683745eb767b266e
