### ISSUE TITLE
Catalog types not working correctly

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/SpongeForge#2440]
On 2705-3442, on 2705 Forge, with a Pieconomy-backed economy, the following line returns an empty optional (when the getAllOf call returns a non-empty collection):
```java
Sponge.getRegistry().getType(Currency.class, Sponge.getRegistry().getAllOf(Currency.class).iterator().next().getId())
```
This behavior is not reproducible on SpongeVanilla.

**Comment by gabizou** [comment]
Mind re-testing this these days? There were a few registry fixes done a few weeks ago now.

**Comment by ImMorpheus** [comment]
Not able to reproduce on latest SF (updated to https://github.com/SpongePowered/SpongeForge/commit/56076fef9034ab20d4a3f0704d6fbf26629a1e11)
(SC updated to https://github.com/SpongePowered/SpongeCommon/commit/758d8f43249417cbc715433b7a63c0a18ac0afcc)

using TotalEconomy.

Moreover that's using your plugin's registry module (calling `getAll` and `getById`), so that's probably not an issue with sponge
