### ISSUE TITLE
BattleTower Golem fatal error. (Kicks player for opening chest)

### ISSUE THREAD

**Issue by SlayerTheChikken** [SpongePowered/SpongeForge#2506]
**I am currently running**
- SpongeForge version: 2768-7.1.5-RC3506
- Forge version: 1.12.2-14.23.5.2768
- Plugins/Mods: https://docs.google.com/spreadsheets/d/e/2PACX-1vTkZG-t1afcKNyPPTd79sOlgnGVQOXTaO1UWjjIIoDbKO0bV9cuLQ1wmEhuDokIxWMJPJbpd8msj6y4/pubhtml

**Issue Description**
The top 2 chests in all battle towers cause fatal errors when trying to open (likely due to the tower golem trying to target the player,) breaking these chests instead of opening them gives no error.

**Debugging log**
Important bit: https://gist.github.com/Slayer5934/884a3932340400067037ae13cf6d50cb
Whole log: https://gist.github.com/Slayer5934/df9309d1c6a3a3a67faeffbc7b22d1b4

**Comment by SlayerTheChikken** [comment]
Related issue I found: https://github.com/NucleusPowered/Nucleus/issues/1030

**Comment by Aaron1011** [comment]
This is a bug in BattleTowers - I've opened an issue at https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/issues/235

As a temporary workaround, you can do this:
1. Set `broken-mod=true` in the `modules` section of your Sponge `global.conf`
2. Add `battletowers` to the `broken-network-handler-mods` list under the `broken-mods` section of your Sponge `global.conf`

Note that this workaround might not fully solve the issue. The real solution is for BrokenMods to properly schedule all entity/world interactions on the main thread, instead of running them from a Netty handler.

**Comment by SlayerTheChikken** [comment]
Thank you :)
