### ISSUE TITLE
Sponge issue? WorldEdit

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#2507]
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.5-RC3506
- Forge version: 14.23.4.2707
- Java version:  Java openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-b12)
- Operating System: CentOS Linux release 7.2.1511

- Plugins/Mods: SevTech: Ages

**Issue Description** Hi there, not sure if this is sponge related or not, but trying to remove a block thats about 200 ish blocks away from where I'm standing, we usually do this with worldedit but have recently come into some issues with it actually removing the block, I assume something to do with loading the chunk. 

If this is not sponge related then my bad. 

https://pastebin.com/Af28p7j0

**Comment by gabizou** [comment]
Doesn't seem anything related to sponge specifically? Have you tried removing the block without sponge installed? The line in question giving a null is
https://github.com/Chicken-Bones/ForgeMultipart/blob/master/src/codechicken/multipart/handler/MultipartSaveLoad.scala#L29

**Comment by bs2609** [comment]
FWIW, the offending line is *probably* here (in the version of the mod that's not for 1.7.10):
https://github.com/TheCBProject/ForgeMultipart/blob/b2024a8a5b8b511ff25da687532d30bac9485d4d/src/main/scala/codechicken/multipart/handler/MultipartSaveLoad.scala#L29

but the file has changed since then:
https://github.com/TheCBProject/ForgeMultipart/blob/master/src/main/scala/codechicken/multipart/handler/MultipartSaveLoad.scala

So probably update first?

**Comment by Keaton1188** [comment]
@gabizou Not tried without sponge, although wouldn't be able to, no sponge = no plugins :) 

@bs2609 You mean update Forge? Already using the latest WE.

**Comment by bs2609** [comment]
I meant: make sure you're using the latest version of https://minecraft.curseforge.com/projects/forge-multipart-cbe

**Comment by XakepSDK** [comment]
@Keaton1188 try worldedit forge version

**Comment by gabizou** [comment]
@Keaton1188 The reason why I ask if it happens without sponge is that there's no sponge related code in that stack trace, granted there's other ways of side effects that could be occurring with sponge installed, but the point is to try without sponge (since WorldEdit for forge exists) to see if the issue is *because* of sponge or not.

**Comment by Keaton1188** [comment]
@XakepSDK Already using that, worldedit-forge-mc1.12-6.1.8-dist.jar

@gabizou Ah ok, makes sense.
