### ISSUE TITLE
ClickInventoryEvent.Shift cannot meet the demand

### ISSUE THREAD

**Issue by zhourui123** [SpongePowered/SpongeForge#2532]
**I am currently running**

- SpongeForge version:  1.12.2-2768-7.1.4
- Forge version: 1.12.2-2768
- Java version: java 8
- Operating System: win 10

- Plugins/Mods:
mfbl_common_plugin-1.0.jar /sponge plugin
mfbl-1.0.jar / forge mod( both side own)

**Issue Description**
I want disable player undress leather_chestplate, so i cancelled the following events:
ClickInventoryEvent.Primary,
ClickInventoryEvent.Secondary
ClickInventoryEvent.Shift

code like this for every event:
`
if (event.getCursorTransaction().getOriginal().getType().equals(ItemTypes.LEATHER_CHESTPLATE)) {
	event.setCancelled(true);
}
`
`
if (event.getCursorTransaction().getFinal().getType().equals(ItemTypes.LEATHER_CHESTPLATE)) {
	event.setCancelled(true);
}
`
Primary and Secondary event work well, in shift event, getOriginal()/getFinal() always return 'air', Is this a bug?

**Comment by Faithcaio** [comment]
Not a Bug. When you shift-click you dont change the item on your cursor.
You want to check the List of SlotTransactions

**Comment by zhourui123** [comment]
can you tell me how do i cancel shift specifying item? I print line every content of shift event, doesn't get any useful infomation.

**Comment by XakepSDK** [comment]
Try this:
I'm not sure, what actually `setValid` does.
```java
@Listener
public void onEquipmentChange(ChangeInventoryEvent.Equipment event) {
    Inventory inventory = event.getTargetInventory();
    Inventory query = inventory.query(QueryOperationTypes.INVENTORY_PROPERTY.of(EquipmentSlotType.of(EquipmentTypes.CHESTPLATE)));
    for (SlotTransaction transaction : event.getTransactions()) {
        if (query.containsInventory(transaction.getSlot())) {
            if (!transaction.getOriginal().getType().equals(ItemTypes.LEATHER_CHESTPLATE)) {
                break;
            }
            if (!transaction.getFinal().getType().equals(ItemTypes.LEATHER_CHESTPLATE)) {
                transaction.setValid(false);
//              transaction.setCustom((ItemStackSnapshot) null); // if item will be removed, remove line above and uncomment this line
            }
        }
    }
}
``

**Comment by zhourui123** [comment]
@XakepSDK thank you , I ran it , it doesn't work,  and i don't know why the breakpoint doesn't enter into  the line 1 of 'ChangeInventoryEvent' ,  Maybe it's a version problem（ current 7.1.4 spongeforge）?

**Comment by XakepSDK** [comment]
Well, i think, `ChangeInventoryEvent.Equipment` is not implemented yet.
Also, invalidation transaction, won't reset cursor transaction.
@Faithcaio if i invalidate transaction with chestplate slot and cursor get chestplate slot item, but chestplate slot isn't empty because of invalidation?

**Comment by Faithcaio** [comment]
`setValid(false)` only invalidates that one transaction. In most cases you got multiple.  (e.g. 2 slot-transactions or 1 slot-transaction and 1 cursor-transaction)
So usually its best to just cancel the entire event. 
Sponge will then invalidate all slot-transactions and the cursor-transaction for you.

**Comment by zhourui123** [comment]
sorry, I don't really understand what you mean by "transaction", Is it impossible to simply disable shift for a specified item?

**Comment by ryantheleach** [comment]
The way the sponge inventory events work, is that they record how the inventory changes, after a certain action, (in this case a click event).

It then shows you an event, which exposes the cursor as a https://github.com/SpongePowered/SpongeAPI/blob/stable-7/src/main/java/org/spongepowered/api/data/Transaction.java#L34 of ItemSnapshots.

And a list of SlotTransactions https://github.com/SpongePowered/SpongeAPI/blob/a1418ae3fccbfa1fbc56e05d2f3375dcd1344e1c/src/main/java/org/spongepowered/api/item/inventory/transaction/SlotTransaction.java

Transactions in Sponge generally have the following properties:
Original: is what it was before the event.
Custom: is mutable, and a way to override the final state.
Default: is what it will be after the event, if nothing else changes.

Final: is the custom, if set, otherwise the default.

So this lets you see, 1. what was going to happen, original->default. 2. what other plugins have done: custom/final.

Slot transactions additionally contain slot information, and a slightly different setCustom helper method.

**Edit:**

In the case of a shift click event, the cursor shouldn't normally change to my knowledge.

But the slots will.

If you are unequipping a chestplate by shift clicking the chest armor slot, that contains a chestplate.

You should see transactions showing the chestslot being turned to air, and an empty space in the inventory going from air to chestplate.

Making the slot transaction invalid for **only** the chest armor slot, will cause the chestplate to remain, but a copy to be made in an empty inventory slot.

Making the slot transaction invalid for **only** the empty slot that will contain a chestplate, will cause the chestplate to no longer exist, as it was unequipped to nowhere.

Cancelling event shows that this click was denied to other plugins, and reverses **everything recorded** that would have happened had it succeed.

Does this clear anything up?

**Comment by XakepSDK** [comment]
@zhourui123 take this
```java
@Listener
public void onEquipmentChange(ClickInventoryEvent event) {
    Inventory inventory = event.getTargetInventory();
    Inventory query = inventory.query(QueryOperationTypes.INVENTORY_PROPERTY.of(EquipmentSlotType.of(EquipmentTypes.CHESTPLATE)));
    for (SlotTransaction transaction : event.getTransactions()) {
        if (query.containsInventory(transaction.getSlot())) {
            if (!transaction.getOriginal().getType().equals(ItemTypes.LEATHER_CHESTPLATE)) {
                break; // cancel 'for', if chest slot does not contain leather chestplate
            }
            if (!transaction.getFinal().getType().equals(ItemTypes.LEATHER_CHESTPLATE)) {
                event.setCancelled(true);
            }
        }
    }
}
```

**Comment by zhourui123** [comment]
@XakepSDK  it is work well,  thank you very much for you all.
