### ISSUE TITLE
Spice of life showing milestone message after every food eaten

### ISSUE THREAD

**Issue by bluelightning32** [SpongePowered/SpongeForge#2544]
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.5-RC3512
- Forge version: 1.12.2-14.23.5.2781
- Java version: OpenJDK 64-Bit Server VM, version 1.8.0_191, running on Linux:amd64:4.19.8-300.fc29.x86_64
- Operating System: Fedora 29

- Plugins/Mods:
  - Plugins: Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, Inven$ory Sync, JdaLibraryLoader, LuckPerms, Nucleus, UltimateChat
  - Mods: everything that comes with the Enigmatica 2 Expert 1.47 modpack. Here are the most relevant ones:
    - Spice of Life 1.12.2-1.3.3. Curse forge doesn't say this, but as far as I can tell it's built from commit d063ca171977841075dc45b75682141e56109bde, not the head of the git repo.
    - AppleCore-mc1.12.2-3.1.4

**Issue Description**
Once the player reaches their first food milestone, a message is shown saying the player met a food milestone. However, the message is then shown for every additional food item that the player eats, whereas the message should only be shown when the next milestone is met.

This bug occurs with the solcarrot mod running on SpongeForge servers. The bug does not occur in Forge servers.

I added some debug statements to narrow down the problem as much as I can with my limited understanding of minecraft internals. The client is generating the message, not the server. The client runs this [function](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/blob/d063ca171977841075dc45b75682141e56109bde/src/main/java/com/cazsius/solcarrot/handler/HandlerFoodTracker.java#L23) whenever the player eats some food. The client looks at the list of foods the player has eaten and recalculates what the player's max health should be for that many foods. It compares that against what the player's max health currently is.

However, somehow the server is clearing this [modifier](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/blob/d063ca171977841075dc45b75682141e56109bde/src/main/java/com/cazsius/solcarrot/handler/MaxHealthHandler.java#L49) that solcarrot is using to track the player's max health (modifier == null). So each time the client regenerates that max_health modifier and shows the milestone, because it thinks the max_health increased.

I found a neglected issue report in solcarrot mod about this:
   https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/issues/10

**Comment by bluelightning32** [comment]
I narrowed this down to Sponge's scaled health breaking it. With this patch the message is displayed at the correct times:
```
diff --git a/src/main/java/org/spongepowered/common/mixin/core/entity/player/MixinEntityPlayerMP.java b/src/main/java/org/spongepowered/common/mixin/core/entity/player/MixinEntityPlayerMP.java
index deddd1170..5753d41eb 100644
--- a/src/main/java/org/spongepowered/common/mixin/core/entity/player/MixinEntityPlayerMP.java
+++ b/src/main/java/org/spongepowered/common/mixin/core/entity/player/MixinEntityPlayerMP.java
@@ -1268,7 +1268,7 @@ public void refreshScaledHealth() {
         // of modifying the attribute instances themselves, we bypass other potentially detrimental logi
         // that would otherwise break the actual health scaling.
         final Set<IAttributeInstance> dirtyInstances = ((AttributeMap) this.getAttributeMap()).getDirtyInstances();
-        injectScaledHealth(dirtyInstances, true);
+        //injectScaledHealth(dirtyInstances, true);
 
         // Send the new information to the client.
         sendHealthUpdate();
```

The solcarrrot mod adds attributes to maxhealth. Sponge's scaled health is deleting those attributes when it sends the max health to the client. From MixinEntityPlayerMP.java:
```
        // We need to remove the existing attribute instance for max health, since it's not always going to be the
        // same as SharedMonsterAttributes.MAX_HEALTH
        for (final Iterator<IAttributeInstance> iter = set.iterator(); iter.hasNext(); ) {
            final IAttributeInstance dirtyInstance = iter.next();
            if (dirtyInstance.getAttribute().getName().equals("generic.maxHealth")) {
                iter.remove();
                break;
            }
        }
```

**Comment by bluelightning32** [comment]
[Here](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/blob/d063ca171977841075dc45b75682141e56109bde/src/main/java/com/cazsius/solcarrot/handler/MaxHealthHandler.java#L61) is where solcarrot sets its max health modifier.

**Comment by gabizou** [comment]
So, there's a reason why injecting scaled health is necessary: Sponge hacks the attribute map being sent to the client to tell the client it's "scaled" health (because a plugin setting the player's health to 200, we don't want to see 100 hearts on the screen). I'm not sure whether I'd be able to provide a compatible way of adding the modifiers back onto the scaled health attribute instance, but it might be worth a shot to fetch the modifiers applied to the real instances, and then apply them to the scaled instance being sent out to players.

**Comment by bluelightning32** [comment]
With the solcarrot (or maybe one of its dependent mods), I do want to see all the hearts on the client. After 20 hearts, the additional hearts show up as a different color.

Can you add a setting to disable Sponge's health scaling?

**Comment by gabizou** [comment]
> With the solcarrot (or maybe one of its dependent mods), I do want to see all the hearts on the client. After 20 hearts, the additional hearts show up as a different color.

I can understand you'd want to be able to show the extra health, and I see that it's being modified via AttributeModifier, so what I'm prepared to do is apply a change where I find the extra modifiers that are being applied, and re-attach the same modifier to the recreated Attribute to be sent to the client. This should suffice to get extra health showing from the mod adding more health on top of the base health (which is what sponge intends to scale).



> Can you add a setting to disable Sponge's health scaling?

Not disabling functionality that plugins would expect to work by config option. It's better to find a way to show the attribute modifiers to the client without it affecting scaling health if possible.

Edit: Just tried to set up a workspace to debug and verify whether my attribute modifier change would fix the issue, but the workspace setup for AppleCore and Slice of Life is just too complicated to get working. There's a bunch of specialized case of relocating at runtime or compile time that is making it difficult to just even run the mod without crashing because of some dependency resolution error or class loading error on the server.

**Comment by bluelightning32** [comment]
Thank you!

Everything looks good so far with 1.12.2-2768-7.1.6-RC3563.
