### ISSUE TITLE
Astral Sorcery multiblocks structures don't see updates

### ISSUE THREAD

**Issue by bluelightning32** [SpongePowered/SpongeForge#2558]
**I am currently running**
- SpongeForge version: 1.12.2-2768-7.1.5-RC3512
- Forge version: 14.23.5.2781 for Minecraft 1.12.2
- Java version: OpenJDK 64-Bit Server VM, version 1.8.0_191
- Operating System: Fedora 29

- Plugins/Mods: All the mods from the Enigmatica Expert 2 v1.51 modpack, most notably astralsorcery-1.12.2-1.10.10

**Issue Description**

For astral sorcery structures, the structure will only be recognized if it is exactly right the first time the special block (such as the starlight crafting altar) is placed. If there are any initial mistakes in the structure, fixing the blocks does not fix the structure.

If the structure is activated, breaking its blocks does not deactivate it like it should.

Breaking and replacing the starlight crafting altar does not fix it. Restarting the server does not fix it. This bug does not reproduce in single player.

Internally here's what's supposed to happen: the first time the starlight crafting altar is placed, it scans the nearby blocks to verify the match the structure pattern. It also keeps the pattern matcher live to watch for any future block changes in that area. If block changes cause the number of mismatches to go to zero, the structure is activated. If block changes cause the number of mismatches to become non-zero, the structure is deactivated. The state of that block matcher gets persisted with the chunk.

AstralSorcery [patches](https://github.com/HellFirePvP/AstralSorcery/blob/8e53ed1976cefe2ec59e96554660ef00090524e3/src/main/java/hellfirepvp/astralsorcery/core/patch/helper/PatchBlockModify.java#L31) Chunk.setBlockState to monitor for those block changes. However, Sponge is [overwriting](https://github.com/SpongePowered/SpongeCommon/blob/b0feef01ce9dd52e0782cf70b8550b324c6aca65/src/main/java/org/spongepowered/common/mixin/core/world/MixinChunk.java#L581) those changes with its Mixins.

**Comment by gabizou** [comment]
> AstralSorcery [patches](https://github.com/HellFirePvP/AstralSorcery/blob/8e53ed1976cefe2ec59e96554660ef00090524e3/src/main/java/hellfirepvp/astralsorcery/core/patch/helper/PatchBlockModify.java#L31) Chunk.setBlockState to monitor for those block changes. However, Sponge is [overwriting](https://github.com/SpongePowered/SpongeCommon/blob/b0feef01ce9dd52e0782cf70b8550b324c6aca65/src/main/java/org/spongepowered/common/mixin/core/world/MixinChunk.java#L581) those changes with its Mixins.

Wow... Well..... No. Patching that method is something I can't work around because of the innate nature of what Sponge is doing to make most all of tracking and events work. There's better ways to go about doing what they probably need out of throwing that event, and worse yet, they're patching that method *regardless whether the chunk is being generated or not* which adds stupid costs already for an already expensive operation (world generation that is).



> Internally here's what's supposed to happen: the first time the starlight crafting altar is placed, it scans the nearby blocks to verify the match the structure pattern. It also keeps the pattern matcher live to watch for any future block changes in that area. If block changes cause the number of mismatches to go to zero, the structure is activated. If block changes cause the number of mismatches to become non-zero, the structure is deactivated. The state of that block matcher gets persisted with the chunk.

And I'm going to ask: Why doesn't the pattern matcher get stored on the crafting alter TE (I'm guessing it's a TE) so it's persisted with the TE, and then either a) listen to player place/break events or b) check every few ticks (10 for a half second delay?) to update the matcher.

Ideally I'd have time to write up a PR to AstralSorcery to fix the issue and what will improve performance to world generation when the mod is installed, but I doubt I'll have time to devise a clean solution in the near future.

**Comment by HellFirePvP** [comment]
> they're patching that method regardless whether the chunk is being generated or not which adds stupid costs already for an already expensive operation

World _generation_ isn't affected. That's all buffered in the ChunkPrimer.
All that's caught in this event is the world _population_; a fraction of what worldgen itself is. Sure, not great, i see that. Will check against isTerrainPopulated for that in the next upcoming update.
And no, there is no better way going about to checking all changes done to the world. For one very vanilla example, pistons don't fire an event at all upon extending. Neither do most mods for things that do changes to the world, making detecting their changes basically impossible as all they're calling will be World#setBlockState

> Why doesn't the pattern matcher get stored on the crafting alter TE

Because the system with designed to support generally whatever kind of block changes you want to monitor. Those do not necessarily need to stem from a (single) tileentity monitoring the changes. You could for example have a tileentity render a preview of the surroundings of another tileentity in another dimension around itself without having to load the other world at all. The caching would allow to cache the preview properly, avoid unnecessary world accesses and ensure that the data you're presenting is 100% accurate (unless you go delete world folders or MCEdit chunks out. Tbf, that borders data loss and is not in the scope of this understandably).
Would also work without either being a tileentity of course. Just needs *something* that'll end up checking and holding the data.

> check every few ticks

The point was to avoid unnecessary world accesses and repeated checks to ensure the integrity of a structure and thus increase runtime performance.

**Comment by gabizou** [comment]
> World _generation_ isn't affected. That's all buffered in the ChunkPrimer.
> All that's caught in this event is the world _population_; a fraction of what worldgen itself is. Sure, not great, i see that. Will check against isTerrainPopulated for that in the next upcoming update.

My mistake, you're right in that *population* still isn't checked, but good to get that updated for generation check.



> And no, there is no better way going about to checking all changes done to the world. For one very vanilla example, pistons don't fire an event at all upon extending. Neither do most mods for things that do changes to the world, making detecting their changes basically impossible as all they're calling will be World#setBlockState

This is a majority of the reason why sponge overwrites both [World#setBlockState](https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/mixin/core/world/MixinWorldServer.java#L1327-L1356) to redirect to our [PhaseTracker#setBlockState](https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/event/tracking/PhaseTracker.java#L646-L820) which will *still call [Chunk#setBlockState](https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/mixin/core/world/MixinChunk.java#L571-L753) specifically to [track and throw events when necessary](https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/mixin/core/world/MixinChunk.java#L708-L721) if block changes are being captured. The ultimate problem is that regardless how we go about it, rewriting the `Chunk#setBlockState` as several injections would ultimately fail because of how many redirects and short circuiting we'd need to perform, especially if others are transforming that method. And Sponge is doing all of this for much the same reason as you're claiming, because block events aren't being thrown by any other entity/tileentity/whatever that is not a player left or right clicking a block that ends up changing said block, and you're 100% right, 99% of mods do not throw events prior to performing such changes.

I'd be inclined to somehow provide a better hook if possible, but short of saying "you can listen to block events if sponge is installed, guaranteed that they will be thrown, and if sponge isn't installed, just perform the transformation as you normally do", I'm not thinking of other options that would give AstralSorcery the same sort of hook without changes in AstralSorcery (or for Sponge to add direct compatibility mixin for AstralSorcery without knowing AstralSorcery is installed at the time).

> Because the system with designed to support generally whatever kind of block changes you want to monitor. Those do not necessarily need to stem from a (single) tileentity monitoring the changes. You could for example have a tileentity render a preview of the surroundings of another tileentity in another dimension around itself without having to load the other world at all. The caching would allow to cache the preview properly, avoid unnecessary world accesses and ensure that the data you're presenting is 100% accurate (unless you go delete world folders or MCEdit chunks out. Tbf, that borders data loss and is not in the scope of this understandably).

Still doesn't quite explain how the pattern matcher or caching data can't be stored onto a tile entity for saving purposes, or hell, make some uuid's for linking pattern matchers/render caches to something loaded via mod's data stored on some world level data that isn't particularly tied to that tile entity, such that when the tile entity does get loaded or ticked, it can virtually check it's surroundings. But I do understand you don't want to add TileEntities to do these sort of checks.

One point I'd like to add though, and this is something SpongeForge has had a lot of work on to try and make compatibility easier with mods: SpongeForge handles translating Sponge events to Forge events and vice versa. The advantage here is that [while AstralSorcery](https://github.com/HellFirePvP/AstralSorcery/blob/8e53ed1976cefe2ec59e96554660ef00090524e3/src/main/java/hellfirepvp/astralsorcery/common/event/listener/EventHandlerServer.java#L260-L269) listens for your event you've wedged in via transformer, [SpongeForge automatically throws any and all BlockEvents caused by Players](https://github.com/SpongePowered/SpongeForge/blob/stable-7/src/main/java/org/spongepowered/mod/event/SpongeToForgeEventFactory.java#L700-L707) for you to listen to, so even if mods are not throwing events, Sponge's tracking will still throw the very same events. One thing I've noticed even in that is that [AstralSorcery's BlockEvent.Place is not performing the same checks for table creation](https://github.com/HellFirePvP/AstralSorcery/blob/8e53ed1976cefe2ec59e96554660ef00090524e3/src/main/java/hellfirepvp/astralsorcery/common/event/listener/EventHandlerServer.java#L279-L286) (which is the root of the issue created here, granted, caused by Sponge overwriting the transformed method for similar reasons), nor is the [BlockEvent.Break](https://github.com/HellFirePvP/AstralSorcery/blob/8e53ed1976cefe2ec59e96554660ef00090524e3/src/main/java/hellfirepvp/astralsorcery/common/event/listener/EventHandlerServer.java#L289-L297) checking for [table removal](https://github.com/HellFirePvP/AstralSorcery/blob/8e53ed1976cefe2ec59e96554660ef00090524e3/src/main/java/hellfirepvp/astralsorcery/common/event/listener/EventHandlerServer.java#L255-L268). I'm not 100% sure whether that'd be a stopgap fix or whether you'd run into duplicated notifications, but that's something I'd considers a possibility as a compatibility check if sponge is installed sort of thing.



> The point was to avoid unnecessary world accesses and repeated checks to ensure the integrity of a structure and thus increase runtime performance.

I'd hate to say that in 1.12, it's not likely we'll have a way to resolve the race of "who transforms this method last", but I can say that some of us at Sponge are working on a 1.13 PR to introduce a lightweight tracker into Forge main for the reasons stated above (no bulk block captures, but something intrinsic to throwing events with appropriate causes).

**Comment by HellFirePvP** [comment]
> Still doesn't quite explain how the pattern matcher or caching data can't be stored onto a tile entity

Consider the same "extreme" case as i've outlayed above, but the data to provide the preview in question about Block A's surroundings need to be known to Block B in another world. Any update to surroundings on Block A would then need to be made known to Block B in a way, thus requiring the loading of said block or the tileentity that controls the behavior of Block B. In worst case, this causes a world load, chunk load and saving of all that data whenever you change a Block arround Block A.
Hence saving it on the tileentities themselves seems like it'd generate considerable overhead. Thus the change-sets are buffered. In the end, the pattern-matcher is also not stored in the system managing the changes. The only thing saved are not-yet-processed changesets.
In the example, Block B or the tileentity controlling the behavior, would eventually get loaded again at some point, then asking the change-system for updates, at which point the changesets would get "consumed" and the new state would be known to Block B or the tileentity controlling the behavior. The change system only acts as buffer so to speak to ensure integrity.

Regardless of what's been discussed so far now, it seems that IWorldEventListener with its notifyBlockUpdate does indeed do the job aswell. Or at least to a good-enough degree as i'd imagine hardly any mod in question would not also set the 2nd flag, which is responsible for sending updates from server -> client, upon setting a block. Always included ofc in the default flags 0011 (3) when setting a block through World#setBlockState(BlockPos, IBlockState). So... i consider the solution with the IWorldEventListener "good enough" for now. Moving forward, we'll need to see what Forge 1.13 brings i suppose.

**Comment by gabizou** [comment]
> Consider the same "extreme" case as i've outlayed above, but the data to provide the preview in question about Block A's surroundings need to be known to Block B in another world. Any update to surroundings on Block A would then need to be made known to Block B in a way, thus requiring the loading of said block or the tileentity that controls the behavior of Block B. In worst case, this causes a world load, chunk load and saving of all that data whenever you change a Block arround Block A.
> Hence saving it on the tileentities themselves seems like it'd generate considerable overhead. Thus the change-sets are buffered. In the end, the pattern-matcher is also not stored in the system managing the changes. The only thing saved are not-yet-processed changesets.
> In the example, Block B or the tileentity controlling the behavior, would eventually get loaded again at some point, then asking the change-system for updates, at which point the changesets would get "consumed" and the new state would be known to Block B or the tileentity controlling the behavior. The change system only acts as buffer so to speak to ensure integrity.

Yeah, many ways to skin the cat in this case. I'd have thought of storing caches to a Palette (like BlockState palettes in 1.12 and 1.13 has a generic class so it's not limited to just `IBlockState`) and using the id of that cache to the tile entity for storage. This way the cache would just be loaded into memory to be updated, regardless what world it exists in etc.



> Regardless of what's been discussed so far now, it seems that IWorldEventListener with its notifyBlockUpdate does indeed do the job aswell. Or at least to a good-enough degree as i'd imagine hardly any mod in question would not also set the 2nd flag, which is responsible for sending updates from server -> client, upon setting a block. Always included ofc in the default flags 0011 (3) when setting a block through World#setBlockState(BlockPos, IBlockState). So... i consider the solution with the IWorldEventListener "good enough" for now. Moving forward, we'll need to see what Forge 1.13 brings i suppose.

`IWorldEventListener` would work for the cases where notifications are sent to clients (almost always the case). Sponge does keep this working a bit better in the cases where it is installed since bulk block changes are thrown sometimes at the end of an entity's tick or packet process, so if all block changes were cancelled, no notifications are sent out to the `IWorldEventListener`. I'm in agreement that that system is a good way, regardless whether sponge is installed or not.

**Comment by Shybella** [comment]
Wow, Hellfire, you are great and you made a fix for this in 1.10.11.

Thank you.
