### ISSUE TITLE
arrows bypass sponge pvp settings

### ISSUE THREAD

**Issue by EasterncheesE** [SpongePowered/SpongeForge#2576]
Minecraft version: 1.12.2
Forge version: 2768
Spongeforge version: spongeforge-1.12.2-2768-7.1.4

As i found out, sponge doesn't handle PVP with projectile weapons correctly.

If i turn ON PVP in server.properties and turn OFF pvp in sponge global config, then sword and any melee attacks are blocked, but bow still damages players. Mobs still can hurt me and i can hurt them.

If i turn OFF PVP in server.properties and turn ON pvp in sponge global config, neither melee nor ranged attacks can hurt players. Mobs still can hurt me and i can hurt them.

I also tested it with techguns mod, which nicely follows vanilla pvp options, but still can damage players with Sponge pvp OFF and server.properties pvp ON.

How can we make Sponge per-world options follow vanialla PVP switch, as it seems to handle pvp much better then sponge? 
So, what we want is to be able to change this vanilla pvp-behaviour between worlds, to create worlds with and without pvp. Server.options enables/disables pvp globally.

**Comment by Zidane** [comment]
This is now fixed as of latest SV/SC.

Unfortunately, due to how configs and such work I cannot honor the server.properties setting. This is now controlled via global.conf or the relevant dimension/world config. Global CAN be used to set a, uh, global PVP setting.

I tested and it was indeed stopping players attacking other players via melee or ranged.
