### ISSUE TITLE
TwilightForest BOSS Buildings Lost Protection

### ISSUE THREAD

**Issue by nice-winter** [SpongePowered/SpongeForge#2582]
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.4
- Forge version: 1.12.2-14.23.5.2768
- Java version: 1.8.0_202
- Operating System: Windows/Mac/Linux

- Plugins/Mods: TwilightForest-3.8.689

**Issue Description**

Not killing Naga, To find the Lich Tower(or any BOSS buildings) and broke it. You can see that they are not protected.

I tried to remove SpongeForge, problems have been solved.

No error No crash.

**Comment by phit** [comment]
confirmed with twilightforest-1.12.2-3.8.689-universal and spongeforge-1.12.2-2838-7.1.7-RC3807

just go in any of the boss buildings and try to break blocks, it works with Sponge and blocks regen and you don't get any drops without Sponge

https://github.com/TeamTwilight/twilightforest/blob/81a8edb55abf7efa6c47dca3ebeca6f63a10a37d/src/main/java/twilightforest/TFEventListener.java#L480

**Comment by ImMorpheus** [comment]
This is because most of TF features are based on https://github.com/TeamTwilight/twilightforest/blob/f191539b2f518e96c108586017255ce19eb840a4/src/main/java/twilightforest/world/TFWorld.java#L32

That check is failing since sponge is providing its own chunkgenerator.
Edit: gabi did some trickery, this is no longer the case to an extent

They should probably switch from an instanceof check to a check on the dimensiontype. (this still stands)
