### ISSUE TITLE
Recipe stuff

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeForge#2586]
**I am currently running**

- SpongeForge version: 3543

- Plugins/Mods:

**Issue Description**
sorry @Cybermaxke still not fixed :(
https://gist.github.com/phit/badfcdd127eed433694b4d6dbb71acf4

minimal set of mods to repro 
industrialforegoing-1.12.2-1.12.4-228.jar
industrialmeat-1.12-1.0.2.jar
jei_1.12.2-4.13.1.225.jar
tesla-core-lib-1.12.2-1.0.15.jar
Forgelin-1.8.2.jar

**Comment by Aiidoneus** [comment]
Just a heads up this broke a couple of mods. Such as ThermalSolars. Tried to start up a PO3 server with the lastest build. Causes a very similar issue.

**Comment by Cybermaxke** [comment]
There is a bug in those mod which causes the ingredient/result of a smelting to be empty because they are registering them in a wrong state event. The smelting recipe is broken anyway, it just didn't spit out a error about it before. However, sponge shouldn't crash the server when that happens so I will be logging a error instead.

**Comment by Y0ungSandwich** [comment]
Very similar crash with XL Food Mod and spongeforge-1.12.2-2768-7.1.5-RC3542

**Comment by phit** [comment]
@Y0ungSandwich update to 3544 http://files.minecraftforge.net/spongepowered

**Comment by Zidane** [comment]
Closing as it is a mod bug and we don't crash the server do to that anymore.
