### ISSUE TITLE
Twilight Forest Crash

### ISSUE THREAD

**Issue by Spontini** [SpongePowered/SpongeForge#2590]
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.5-RC3553 
- Forge version: 2795
- Java version: 1.8.0_192, Eclipse OpenJ9
- Operating System: Ubuntu 18.10
 -Modpack: PO3 / 3.0.37

Issue: Most mobs from T.Forest doesn't spawn (not even naturally, with eggs or commands) or invisible, also some of them crashes the server but however they all work fine without sponge or in singleplayer.

Crash Report:
[crash-2019-02-01_15.30.12-server.txt](https://github.com/SpongePowered/SpongeForge/files/2822049/crash-2019-02-01_15.30.12-server.txt)

**Comment by Aaron1011** [comment]
Can you confirm that this doesn't occur without Sponge?

**Comment by Spontini** [comment]
Like i said, i've tried doing the same thing in singleplayer and all mobs works pretty well

**Comment by Aaron1011** [comment]
My bad - I misread your issue.

**Comment by Spontini** [comment]
It's alright

**Comment by Spontini** [comment]
I'm sorry, forge is 2795, i texted it wrong at first

**Comment by gabizou** [comment]
![screen shot 2019-02-01 at 5 39 10 pm](https://user-images.githubusercontent.com/1203877/52157961-5231b180-2648-11e9-8b3f-d454818f3620.png)
Spawned a swarm spider just fine, no exceptions. There must be a conflict from another mod in combination with TwilightForest and Sponge that is causing the exceptions.

Because your mod list is far too large to test each one individually, I'd suggest starting with taking out half the mods and attempting to test, cutting the list in half each time. Starting with the mods that are not listed as core mods (again, except TwilightForest).

**Comment by bs2609** [comment]
Crashes caused by swarm spiders are related to the JVM used, see https://github.com/TeamTwilight/twilightforest/issues/660.
