### ISSUE TITLE
Land Craft Ores not spawning

### ISSUE THREAD

**Issue by Spontini** [SpongePowered/SpongeForge#2597]
Land Craft: https://minecraft.curseforge.com/projects/land-craft (One of the mods in PO3)

Sponge Versions USED: 1.12.2-2768-7.1.5 also tried with 1.12.2-2768-7.1.6-RC3561

Issue: The ores comes with Land Craft which are `Kelline Ore, Garfax Ore, Morganine Ore, Racheline Ore and Friscion Ore` does not spawn in Landia Dimension (which is the dimension Land Craft add into the game and yes in single player or multiplayer without sponge every ores do spawn.)

--------------------------------------------

moved projecte to https://github.com/SpongePowered/SpongeForge/issues/2598 ~phit

**Comment by phit** [comment]
sounds like you don't have the modpack configs on the server

**Comment by Spontini** [comment]
I've copy, paste the modpack configs directly to my server from singleplayer (i mean the folder where the pack installed by TwitchLauncher since PO3 doesn't have server files.)

**Comment by LXGaming** [comment]
https://github.com/Landmaster/LandCraft/blob/1922e538d129f24327c8249d5740c114291a6ad8/src/main/java/landmaster/landcraft/world/gen/LandiaOreWorldgen.java#L22

For some reason the `chunkGenerator` is actually `SpongeChunkGeneratorForge` instead of the expected `LandiaChunkGenerator`. I'm not sure if this is a bug in LandCraft due to it not registering something at a specific time so that it satisfies Sponge (Works in SinglePlayer) or if this is a Sponge bug (passing a `SpongeChunkGeneratorForge` to a mod doesn't seem right?)

The fix is to replace `chunkGenerator instanceof LandiaChunkGenerator` with `world.provider instanceof LandiaWorldProvider` (Just need to verify the world is the LANDIA world so any check for that will work)

You can get a patched build/source here: https://github.com/lolnetnz/LandCraft/releases/tag/v2.2.1.2
(Original Dev hasn't touch his mod for a year so little to no chance they will fix the issue themselves if it can't be fixed on Sponge side)

**Comment by Spontini** [comment]
@LXGaming This crashes my server on startup https://pastebin.com/9bTTS1wh

**Comment by ApolloMCC** [comment]
@LXGaming Would it be possible to fork landcraft again for 2.2.3.1?

**Comment by LXGaming** [comment]
@ApolloMCC https://github.com/lolnetnz/LandCraft/releases/tag/v2.2.3.1

**Comment by Landmaster** [comment]
Fixed in LandCraft 2.3.0.2

**Comment by jinkhya** [comment]
Hello @LXGaming sorry to ping and bother you, would it be possible to get a fork for 2.3.0.1? Project ozone 3 hasn't been updated since the 19th of April and is using 2.3.0.1. It would be very much appreciated !

**Comment by LXGaming** [comment]
[landcraft-2.3.0.1-Patch.jar.zip](https://github.com/SpongePowered/SpongeForge/files/3225077/landcraft-2.3.0.1-Patch.jar.zip)
@jinkhya Remove the .zip off the end of the file, It's named like that so I can upload it to GitHub

**Comment by jinkhya** [comment]
cheers !!! thank you so much

**Comment by 123Kappa** [comment]
@LXGaming Sorry for bothering you can we get the patch again for 
landcraft-2.3.0.2.jar <3

**Comment by LXGaming** [comment]
It's already fixed in that version: https://github.com/Landmaster/LandCraft/releases/tag/2.3.0.2
