### ISSUE TITLE
java.lang.IllegalStateException: Cause Stack Frame Corruption!

### ISSUE THREAD

**Issue by LokeYourC3PH** [SpongePowered/SpongeForge#2619]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2768-7.1.6-RC3592
- Forge version: 1.12.2-14.23.5.2811
- Java version: 1.8.0_191

- Plugins/Mods:
https://pastebin.com/cBiwXiwe

**Issue Description**
The server has crashed like this multiple times randomly, and there doesn't seem to be an apparent reason for why, it happens as most crashes just randomly, nothing special is being done by players.

Server Crash: https://pastebin.com/Lq31PeFD
Debug.log (Too large, had to use my own file host): https://mega.nz/#!45UTwaza!iwPiMtAlDiSS8vHhHq20RpP68RMS1WLLDVPkDeI5HPI

**Comment by LokeYourC3PH** [comment]
Note to myself: Add JVM Argument for getting more debug information. JVM Argument: -Dsponge.debugcauseframes=true

**Comment by phit** [comment]
that debug log is not from the crash

**Comment by LokeYourC3PH** [comment]
> 
> 
> that debug log is not from the crash

Then I will not be able to find it, as the previous ones have been deleted. Once it happens again I make sure to immediately grab the debug.log, sorry about that.

**Comment by Sir-Will** [comment]
Got the same crash here only that the server gets stuck in a crash loop once it occurs and it seems to only happen on startup when the chunk loaders start loading the chunks.

Exceptions: https://pastebin.com/vX1icxjq

Where does the debugcauseframes show up when the arg is set?

**Comment by phit** [comment]
>Where does the debugcauseframes show up when the arg is set?

in the normal debug.log

**Comment by gabizou** [comment]
From @Sir-Will's exceptions, it looks like extrautils2 is either being transformed erroneously, or implementing some method that is causing the target method: `func_185929_b` to show up as abstract on it's target class. Seeing as there's several core mods at play, this issue needs to be ironed down to as few as possible to even start figuring out where things are classloading/transforming to cause such an issue (it's clear why there's frame corruption, the chunk is failing to load correctly because the `IBlockState` is not able to be deserialized from the chunk data, because the `IProperty` is missing a **very** important method: `func_185929_b` or otherwise known as `parseValue`).

If anything, I'd try to get this narrowed down to "is it reproducible" with just AstralSorcery and ExtraUtils 2 and SpongeForge. If it is, provide the world/chunk where the load is failing.

**Comment by phit** [comment]
if it shows up again let us know and I'll reopen this
