### ISSUE TITLE
Extraneous prefixes in chat messages

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/SpongeForge#2626]
**I am currently running**
- SpongeForge version: 1.12.2-2768-7.1.6-RC3600
- Forge version: 1.12.2-14.23.5.281
- Java version: 1.8.0_191-b12
- Operating System: CentOS 7

- Plugins/Mods:
FTB Ultimate 1.2.0
Mods (139): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AE2 Stuff, Advanced Machines, Advanced Solar Panels, AppleSkin, Applied Energistics 2, Aroma1997's Dimensional World, Aroma1997Core, AutoRegLib, BD Lib, Baubles, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Blockcraftery, BuildCraft, BuildCraft Builders, BuildCraft Compat, BuildCraft Energy, BuildCraft Factory, BuildCraft Lib, BuildCraft Robotics, BuildCraft Silicon, BuildCraft Transport, CC: Tweaked, Charset, Chisel, Chisels & Bits, CoFH Core, CoFH World, CodeChicken Lib, Compact Solar Arrays, Computronics, CraftTweaker JEI Support, CraftTweaker2, Crafting Tweaks, Diet Hopper, EnderStorage, Energy Converters, FTB Library, Fancy Fluid Storage, FastWorkbench, Flat Colored Blocks, FoamFix, FoamFixCore, Forestry, Forge Microblocks, Forge Multipart CBE, Gravitation Suite, Guide-API, Harvest, Immersive Cables, Immersive Engineering, Industrial Foregoing, IndustrialCraft 2, Integration Foregoing, Inventory Tweaks, Iron Chest, JEI Bees, Just Enough Energistics, Just Enough Items, LagGoggles, Long Fall Boots, MCMultiPart, MTLib, MachineMuse's Modular Powersuits, MagicBees, Minecraft Multipart Plugin, Mod Tweaker, Modular ForceField System, Modular Routers, Morph-o-Tool, Morpheus, MrTJPCore, MysticalLib, Netherending Ores, Numina, Placebo, Player Plates, PortalGun, ProjectRed Core, ProjectRed Expansion, ProjectRed Exploration, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Relocation, ProjectRed Transmission, ProjectRed Transportation, ProjectRed integration, ProjectX 2, Quick Leaf Decay, Railcraft, RandomPatches, Reborn Core, Redstone Flux, Reliquary, Retro Exchange, Shadowfacts' Forgelin, Silverfish, Simple Corn, Smooth Font Core, Soul Shards Respawn, SpongeForge, Steve's Carts 2, TOP Addons, Tech Reborn, Tech Reborn Mod Compatibility, Tell Me, Tesla Core Lib, Tesla Core Lib Registries, Thaumcrafft Inventory Scanning, Thaumcraft, Thaumic Energistics, Thaumic Tinkerer, The One Probe, The Twilight Forest, Thermal Dynamics, Thermal Expansion, Thermal Foundation, TorchMaster, Traverse, UniDict, WanionLib, WirelessRedstone-CBE, World Control, WorldEdit, YABBA, asielib, iChunUtil, projectred-compat

Plugins (19): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, AntiWDL, BetterChunkLoader, Broadcast, CatClearLag, Enjin Minecraft Plugin, GriefPrevention, LuckPerms, MagiBridge, Nucleus, PlayerShopsRPG, Prism, Server Backup, Total Economy, WrapperPing, spark

**Issue Description**
When using SpongeForge 1.12.2-2768-7.1.6-RC3600, extraneous chat prefixes are observed in chat, like so: `LemADEC: <LemADEC> hi`
Using 1.12.2-2768-7.1.6-RC3599 doesn't reproduce the issue, like so: `LemADEC: hi`
It could be an interaction with the following plugins:
- Nucleus-1.8.3-S7.1-MC1.12.2
- LuckPerms-Sponge-4.3.18build796
- griefprevention-1.12.2-4.3.0.678

**Comment by dualspiral** [comment]
https://github.com/SpongePowered/SpongeForge/commit/2ab93ca820a374c92994942d683745eb767b266e#diff-f2ad293bf653825d1ded2461cfabb502R315

This broke the way that our chat event works, because of how we split the chat up into the header, the message itself, and a footer. While the need to sync back is fine, this blew away the headers and footers. Hence, Nucleus, which is only trying to touch the header here, inserts its prefix like normal but is now unaware of the original header (yes, using beforeModifications will fix that and I'm okay with changing that, but if nothing changes in the Forge event, nothing should change in the Sponge event).

We should only sync back if a Forge mode has changed the message in order to preserve the headers etc. in this scenario. It's going to be difficult to keep the header/body/footer (and Nucleus has an option to deal with that), but if the text isn't modified then we should forgo syncing back.

**Comment by dualspiral** [comment]
(Also, @LemADEC, you can workaround it by turning on `check-body-for-minecraft-prefix` in Nucleus)

**Comment by Rasgnarok** [comment]
Still happens with spongeforge-1.12.2-2768-7.1.6-RC3601.jar
