### ISSUE TITLE
[Sponge]: Could not find ... class

### ISSUE THREAD

**Issue by bookerthegeek** [SpongePowered/SpongeForge#2633]
# Heyo
**I am currently running**
- SpongeForge version: 1.12.2-2768-7.1.5 (Also tested with 1.12.2-2768-7.1.6-RC3616) 
- Forge version: 1.12.2-14.23.5.2807
- Java version: 1.8.0_201
- Operating System: Windows 10
- Full Mod List: [HERE](https://gist.github.com/bookerthegeek/67eda441aecc3b4ea66a757a3a9aecdc)

**Issue Description**
An amount of log spam consisting of `[Sponge]: Could not find ... class`
The only other information I could find was part of #1273 but that is pretty old and also closed.

**Logs**
- Tested with 1.12.2-2768-7.1.5 ([Cut of Log](https://gist.github.com/bookerthegeek/270e29109544215e10836b0e9cb279ca)) ([Full Log](https://gist.github.com/bookerthegeek/e2273d1c4c0e3404519070518cb555ce)) 
- Tested with 1.12.2-2768-7.1.6-RC3616 ([Cut of Log](https://gist.github.com/bookerthegeek/864cf0a902293b793141052c09d8540f)) ([Full Log](https://gist.github.com/bookerthegeek/07366c0b001f1a65176d46932501e2fc))

**Comment by Grauldon** [comment]
It looks like the wrong version of mixin is used. Try renaming `spongeforge-1.12.2-2768-7.1.5` to `_aspongeforge-1.12.2-2768-7.1.5`.

**Comment by bookerthegeek** [comment]
> Try renaming `spongeforge-1.12.2-2768-7.1.5` to `_aspongeforge-1.12.2-2768-7.1.5`.

Tried and still get the same thing in the logs.

**Comment by gabizou** [comment]
These warnings can be ignored for the most part. They're warnings because the `IProperty` of the `IBlockState`s that are used by those mods are not being found "where" they come from. As such, the properties themselves are given a generated string id, and Sponge emits those generated id's so that you (the server admin) will be able to determine when the ID changes (since they can be used in configs and whatnot). I guess we could make the warning more explicit about what it's doing, but nothing really to worry about.

**Comment by bookerthegeek** [comment]
Thank you for the explanation.

Curious if you have a moment... What is most likely causing those not to be found, and is it something that should be fixed on the mods and or is it not really worth it?

**Comment by gabizou** [comment]
It's not worth, it's serving as a warning for server admins in the event a property is no longer the same string id as before (in the event the property gets moved between classes, or class renames occur).
