### ISSUE TITLE
1.10.2 RFTools Dimension Enscriber doesnt accept dimlets

### ISSUE THREAD

**Issue by xBluemist** [SpongePowered/SpongeForge#2663]
I'm playing Sky Factory 4 through the Feed the beast dimension and the Dimension inscriber is refusing to accept any dimlets, like the Dimlet Structure Type Controller. Help!

**Comment by phit** [comment]
Hey! You're running an unsupported version of Spongeforge. Support for 1.10/1.11 ended on January 2018.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please [open a new issue](https://github.com/SpongePowered/${repository_name}/issues/new) with updated information.
