### ISSUE TITLE
SkyFactory4 Recipe Problems

### ISSUE THREAD

**Issue by Spontini** [SpongePowered/SpongeForge#2689]
SpongeForge 1.12.2-2768-7.1.6-RC3616 
Forge 14.23.5.2831
Modpack: SkyFactory4

Issue: Some recipes such as BonsaiHoppers does not work with sponge installed.

**Comment by LemADEC** [comment]
sounds like world generation/type misconfiguration

**Comment by phit** [comment]
bonsai trees are locked behind prestige mode, nothing to do with sponge

**Comment by ApolloMCC** [comment]
yeah we know even if they unlock it through prestige mode they do not get the recipe. It could be a bug with prestige mod though. I will update if it is not

**Comment by Spontini** [comment]
I've tested it in both singleplayer and non sponge servers and bonsai hoppers works like it should be, the sponge deletes the recipe also even if we get em from creative mod hopping bonsai pots not working.

**Comment by krisjenner** [comment]
Can confirm after testing in singleplayer with prestige enabled the hopping bonsai recipe shows after unlock but on logging in to my server (Sponge RC3616) and having Prestige enabled in the config after I unlock the hopping bonsai I crash then log in to no recipe still.

[Crash from latest.log](https://gist.github.com/krisjenner/ab9353c643b7f96f531f4a299641639c)

**Comment by gabizou** [comment]
Try out the newest build 3659 (once it publishes)

**Comment by ApolloMCC** [comment]
After 5 minutes after I started the server the new build stalled it with this in stall reports. 
https://pastebin.com/yKWhAC6s

**Comment by gabizou** [comment]
Need more of that stall log... that's only a literal small bit of it.

**Comment by ApolloMCC** [comment]
Here it is: https://pastebin.com/WKgh2KUE
I've been running sf4 for a while i've never had stall reports (after i fixed some issues), it has to be the version.

**Comment by krisjenner** [comment]
I haven't started it on my server but tried on a test server it runs perfect and the recipes appear after unlocking them in prestige :)

**Comment by ApolloMCC** [comment]
Ore excavation used to work though

**Comment by gabizou** [comment]
> I've been running sf4 for a while i've never had stall reports (after i fixed some issues), it has to be the version.

Nothing in that report shows that sponge is stalling, the only real stall could possibly be the massive amount of threads that are being created (someone more familiar with MC's thread handling would need to comment), but I can guarantee you that the server's thread that sponge is affecting at that moment wouldn't have stalled in the middle of processing a block's transactions from a block event.



> Ore Excavation seems to not work after unlocking still. Unsure if you just focused on the recipes but thought it was worth the edit

Don't know what ore excavation is, but I did focus my commit solely on resolving the error of the prestige mod throwing a command asynchronously (which if you have verbose on, it will emit a warning about once).

Since the original issue is about recipes not unlocking (really from prestige trying to execute commands async), the original issue at hand is closed. Any other issues need to be brought up as new issues with explanation about their origins, descriptions etc.

**Comment by Zidane** [comment]
Give the latest build a try. We think the issue might be fixed with that change.

**Comment by ftog-thorgal** [comment]
> Give the latest build a try. We think the issue might be fixed with that change.

I wanted to confirm that after I updated our server to spongeforge-1.12.2-2768-7.1.6-RC3665.jar it fixed the issue with Prestige crashing and not updating to unlock recipes.

Thank you devs for your awesome work!

**Comment by ApolloMCC** [comment]
@ftog-thorgal Check the "unlock mod" prestiges
