### ISSUE TITLE
LagGoggles compatibility lost

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/SpongeForge#2696]
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.6-RC3660
- Forge version: 14.23.5.2824
- Java version: 1.8
- Operating System: CentOS

- Plugins/Mods: LagGoggles-SPONGEFORGE-1.12.2-4.1.

**Issue Description**
Newest version of SpongeForge have lost compatibility with LagGoggles.
See https://github.com/TerminatorNL/LagGoggles/issues/56

spongeforge-1.12.2-2768-7.1.6-RC3616 is the latest known version to be compatible.

**Comment by phit** [comment]
> ` [mixin]: Mixin apply failed mixins.laggoggles.json:MixinWorldServerSponge -> net.minecraft.world.WorldServer`

nothing for Sponge to fix here as far as I can tell

**Comment by Aaron1011** [comment]
This is caused by https://github.com/SpongePowered/Mixin/issues/313 - a LagGoggles mixin is failing to apply, which is causing Mixin to silently skip other mixins targeting the same class (in this case, Sponge's MixinWorld)

**Comment by LordRalex** [comment]
Cross-post from the other issue for reference:

The reason the mixin failed here is because PhaseData was removed from Sponge (SpongePowered/SpongeCommon@9c4cd22#diff-3995e0519c5bbe8e43bc8a7e27e7818f)

LagGoggles does a mixin to some methods, and it expected that class to exist. Since it doesn't, well, it fails to apply mixins.

Mixin which is impacted: https://github.com/TerminatorNL/LagGoggles/blob/master/src/main/java/cf/terminator/laggoggles/mixin/MixinWorldServerSponge.java

**Comment by LeonPhilips** [comment]
I wasn't actually going to fix this at this time, but I don't want to deny anyone from updating any longer. I have pushed a hotfix adressing this. https://minecraft.curseforge.com/projects/laggoggles/files

Sorry for the long wait for such an easy edit, folks.
