### ISSUE TITLE
ScalingHealth doesn't work in other dimentions

### ISSUE THREAD

**Issue by LANCECHEN117** [SpongePowered/SpongeForge#2732]
<ScalingHealth works well in any dimention of forge server however it only works in the overworld(Level 0) in the sponge server.

First of all, I've tried to create new world by nucleus plugin and it doesn't works as well.

Then I used Cursed Heart item in DIM-1 in order to see whether server is sync with client, however this item cannot increase difficult by right clicking it, the difficulty indication didn't increase at all！

Finally, I delete sponge forge then this mod works well in just forge server
->
Versions

    Scaling Health: <1.12.2-1.3.34+135>
    Silent Lib: <1.12.2-3.0.13+167>
    Forge: <forge-1.12.2-14.23.5.2825-universal>

   **Sponge：version 1.12.2-2825-7.1.6-RC3692
                                         1.12.2-2768-7.1.5
                                          1.12.2-2768-7.1.6-RC3686**
                                          
    Modpack (if applicable): Custom

**Comment by phit** [comment]
please add the spongeforge versions you tested with

**Comment by LANCECHEN117** [comment]
> 
> 
> please add the spongeforge versions you tested with

Added sir, plz check

**Comment by LANCECHEN117** [comment]
maybe Sponge blocked the modifiers on other dimension haha!

**Comment by phit** [comment]
reproduced with 
ScalingHealth-1.12.2-1.3.38+143.jar
SilentLib-1.12.2-3.0.13+167.jar

to test:
give yourself some experience `/xp 30L name`
rclick some heart containers, it will give you more hearts note how the last heart outline flashes thats supposed to be constantly lit
otherwise hearts seem to work okay

the second completely broken part is cursed hearts when rclicked theres supposed to be a difficulty bar going up on the bottom left of your screen, this sometimes works in the overworld and doesn't work at all in any other dimension
the difficulty simply doesnt increase, this isn't clientside only you can check with `/scalinghealth difficulty get` its not going up on the server either

thanks to the mod dev SilentChaos512 explaining me how to repro this

**Comment by ImMorpheus** [comment]
ScalingHealth is using a gamerule to enable/disable the difficulty.

Sponge is not using the overworld gamerules because we have implemented per-world gamerules. This is working as expected.

If you want the difficulty to work in other dimensions, you need to run `/gamerule ScalingHealthDifficulty true` in said dimensions.

(As an alternative, ScalingHealth could add the default gamerule to every dimension).
See https://github.com/SilentChaos512/ScalingHealth/blob/760051600cf7c5c6077c5431bf87b44ad0013985/src/main/java/net/silentchaos512/scalinghealth/ScalingHealth.java#L88
