### ISSUE TITLE
Missing plugin unknown for entity unknown:unknown (micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP)

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/SpongeForge#2842]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3822
- Forge version: forge-1.12.2-14.23.5.2836-universal

- Plugins/Mods: GalacticraftCore-1.12.2-4.0.2.190, Galacticraft-Planets-1.12.2-4.0.2.190

**Issue Description**

Getting the error below with the code below. Not sure how this would be fixable on the plugin side.

```java
    @Listener
    public void onItemDrop(DropItemEvent event, @First Player player) {
        player.getOpenInventory().ifPresent(inv -> {
            if (inv.getPlugin() == plugin) {
                ...
            }
        });
    }
```
https://gist.github.com/Sir-Will/e1097c4ea1b56b7ceb1f76831ade36e6

**Comment by JBYoshi** [comment]
From a brief look at the code and the error, it looks like this is caused by Galacticraft creating [its own class for players](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/entities/player/GCEntityPlayerMP.java) ([transformer](https://github.com/micdoodle8/MicdoodleCore/blob/1105d09f3c8d0227095625c13adfd6f1437c7cb8/src/main/java/micdoodle8/mods/miccore/MicdoodleTransformer.java#L563-L593)) which subclasses EntityPlayerMP. Sponge doesn't detect that this is still a player, and so it breaks.

**Comment by Zidane** [comment]
I've added the ability for you to at least be able to interact with the inventory in the next SF but the `getPlugin` call will still return the base `PluginContainer` (AKA Minecraft) and not GalacticCraft.
