### ISSUE TITLE
Block showing as wrong BlockType

### ISSUE THREAD

**Issue by Pulverizer** [SpongePowered/SpongeForge#2880]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3848
- Forge version: forge-1.12.2-14.23.5.2838-universal
- Java version: 1.8.0_171
- Operating System: Windows 10 64-bit

Plugins/Mods:
- worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist
- Movecraft for Sponge In-Dev

**Issue Description**
A block of Flowing Water in-game is seen as `BlockTypes.WATER` in the SpongeAPI instead of `BlockTypes.FLOWING_WATER`.

I only noticed the issue due to it seriously messing up one of my listeners.

[debug.log](https://github.com/SpongePowered/SpongeForge/files/3401238/debug.log)
[latest.log](https://github.com/SpongePowered/SpongeForge/files/3401239/latest.log)

**Comment by Pulverizer** [comment]
Worked fine in spongeforge-1.12.2-2838-7.1.7-RC3782

**Comment by gabizou** [comment]
Reviewing this at the moment, and I'm not seeing any flowing water being labeled as `BlockTypes.WATER` when they move. What is the context where your listener is picking up `BlockTypes.WATER`?

Edit No. 1:
When NeighborNotificationEvents are being processed, the world itself is providing the static `minecraft:water[level=1]` because the flowing water will replace itself with a static block on it's own update. This is intended.

What you can do however, is check for liquid matter by `blockstate.getProperty(MatterProperty.class)` and it'll provide you with the `Matter.LIQUID` value. In API 8, we'll have better support for getting the `FluidType` from a state, but for now, it's unimplemented to get the FluidType from a BlockState.

**Comment by Pulverizer** [comment]
ExplosionEvent.Detonate

https://github.com/Pulverizer/Movecraft-for-Sponge/blob/276436ab5943b128fc7316415e4229b2b22d2d47/src/main/java/io/github/pulverizer/movecraft/listener/BlockListener.java#L191

**Comment by gabizou** [comment]
Adding screenshot of replacement taking place:
![imaage](https://i.imgur.com/eKmoxtb.png)

**Comment by Pulverizer** [comment]
So this has been fixed recently?
