### ISSUE TITLE
Location.restoreSnapshot() does not invalidate old TileEntity

### ISSUE THREAD

**Issue by Pulverizer** [SpongePowered/SpongeForge#2881]
**I am currently running:**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3848
- Forge version: forge-1.12.2-14.23.5.2838-universal
- Java version: 1.8.0_171
- Operating System: Windows 10 64-bit

**Plugins/Mods:**
- worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist
- Movecraft for Sponge In-Dev

**Issue Description**
When `Location.restoreSnapshot()` is called the block is placed but the TileEntity of the previous block has not been invalidated. This can cause the previous block to fire a ChangeBlockEvent.Break and drop as an item the next time the TileEntity is ticked.

This is particularly bad when combined with a listener that is intended to prevent blocks from breaking. The ChangeBlockEvent.Break is cancelled but the drop remains. However, cancelling the event also causes the TileEntity to continue to exist so it tries to break again and again until it causes the server to crash.

@gabizou has helped quite extensively to track down and resolve the issue.

Original issue can be found here: https://github.com/Pulverizer/Movecraft-for-Sponge/issues/6

**Comment by Pulverizer** [comment]
Nevermind, the crash seems to still happen even with the tile entity invalidated.

**Comment by Pulverizer** [comment]
Nevermind, that was due to me reactivating some old code.
However, a new crash indicated that restoring the BlockSnapshot may have triggered a block update even though it was specified not to.

**Comment by Pulverizer** [comment]
No error occurs only if done in this order:
- Invalidate the Tile Entities.
- Place the new blocks.
- Remove the old blocks that are not in the new locations.

**Comment by gabizou** [comment]
So, looking at the issue further, for starters, to make this quite clear:
Snapshot restoration is working as expected, as [shown here, it's calling to remove the `TileEntity` before changing the block state](https://github.com/SpongePowered/SpongeCommon/blame/ede9bc31495409037003356822b82a2c32237b8b/src/main/java/org/spongepowered/common/block/SpongeBlockSnapshot.java#L197) which will invalidate the tile entity as well. 

Since the `TileEntity` is already being invalidated and removed, I can't see any reason why the `BlockSnapshot#restore` would cause drops, especially since the drop logic already checks for restores (it's how all block cancellation logic ends up not causing drops for protection plugins).

So, your workaround isn't so much of a bug with restoring block snapshots, it's more of a side effect of how block replacement works unless you use restoration, i.e. ask for all of your block replacements to be restorations and no block drops will occur. Because you're performing block changes outside of restoration, the normal block break will still occur and some tile entities perform inventory drops as if their block has been actually broken (though different from player breaking).

What I've suggested in the past was using snapshots only to restore the new blocks and replacing any existing blocks in the way of the moving vessel, since their restores restore everything sans scheduled block updates (which honestly, shouldn't be fiddled with the exception of if you're able to re-attach updates in the original order in which they were received).

Since the logic in snapshot restore is fine, I'm going to close this.
