### ISSUE TITLE
Biomes O' Plenty trees and other decoratives not generating

### ISSUE THREAD

**Issue by Techjar** [SpongePowered/SpongeForge#2882]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.7-RC3848
- Forge version: 14.23.5.2838
- Java version: Java 8 (multiple subversions)
- Operating System: Windows/Linux

- Plugins/Mods: Biomes O' Plenty

**Issue Description**
When SpongeForge is installed and the Biomes O' Plenty world type is used, trees and various other decoratives do not generate at all, producing barren landscapes. Here's an example of a Coniferous Forest:
![](https://qimg.techjargaming.com/i/yvZtfWgm.png)

I have removed all other mods except SpongeForge and Biomes O' Plenty, so it's definitely an interaction between the two exclusively.

https://gist.github.com/Techjar/3e7bcb43c8b05c60f53acc0e02f492b5
Yeah it's a client log, but that's just where I reproduced the issue as someone else reported it to me. It does also occur on a dedicated server.

**Comment by yagomont** [comment]
Having this problem on my server as well. It also seems to affect water body generation. Clay, sand, aquamarine ores do not generate. Only dirt and gravel.

It's very much broken.

(Why did you name your world penis?!?!)

**Comment by yagomont** [comment]
Solved by reverting to spongeforge RC3826.

**Comment by gabizou** [comment]
Found the issue, [this mixin was never actually applied](https://github.com/SpongePowered/SpongeCommon/blob/f39db6bf46c27fe90c6c7f13f3d8262bf3f1a0ae/src/main/java/org/spongepowered/common/mixin/core/world/biome/MixinBiomeDecorator.java#L35) and in my audit, I made sure that all mixins were being applied, causing the biome decorators to not actually function. Dead code begone! Will be fixed in the next build.
