### ISSUE TITLE
Changes in modded Container were not captured when using TinkersForgin

### ISSUE THREAD

**Issue by Caishangqi** [SpongePowered/SpongeForge#2900]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3854.jar
- Forge version:  forge-1.12.2-14.23.5.2838
- Java version:  jre1.8.0_221
- Operating System:Windows 10

- Plugins/Mods:
grapplemod@1.12.2-v11.1,
enderiointegrationforestry@5.0.44,
alcatrazcore@1.0.4,
modularmachinery@1.10.0,
questbook@3.1.EXP_NET2-1.12,
universalmodifiers@1.12.2-1.0.16.1,
creativecoredummy@1.0.0,
teastory@3.3.1-B30.413-1.12.2,
animania@1.6.2,
zevac.survivalflight@0.1.11,
cofhcore@4.6.2,
chineseworkshop@1.2.6,
craftstudioapi@1.0.0,
plustic@7.0.7.0,
endercore@1.12.2-0.5.57,
thaumicjei@1.6.0,
betterquesting@3.5.300,
cookingforblockheads@6.4.70,
xnet@1.8.1,
neid@1.5.4.4,
ae2stuff@0.7.0.4,
justthetips@1.12-1.0.1.1,
forgelin@1.8.2,
itemzoom@1.10,
llibrary@1.7.19,
cofhworld@1.3.0,
waila@1.8.26,
ftblib@5.4.3.129,
enderioconduitsrefinedstorage@5.0.44,
guideapi@1.12-2.1.8-63,
carryon@1.12.2,
jeresources@0.9.2.60,
thaumcraft@6.1.BETA26,
mcjtylib_ng@3.5.3,
bq_standard@3.4.159,
enderioconduits@5.0.44,
immersivetech@1.3.10,
industrialforegoing@1.12.2-1.12.2,
crafttweakerjei@2.0.3,
enderiomachines@5.0.44,
geolosys@3.0.1,
mtlib@3.0.6,
biomesoplenty@7.0.1.2439,
redstoneflux@2.1.0,
valkyrielib@1.12.2-2.0.20.1,
modtweaker@4.0.17,
botania@r1.10-361,
gendustry@1.6.5.8,
openfm@0.1.0.19,
resourceloader@1.5.3,
teslacorelib_registries@1.0.15,
actuallyadditions@1.12.2-r149,
ic2@2.8.169-ex112,
patchouli@1.0-20,
pewter@1.4.3,
veinminer@0.38.2,
teslacorelib@1.0.15,
FML@8.0.99.99,obfuscate@0.2.6,
thermalexpansion@5.5.4,
tombstone@3.5.5,
customnpcs@1.12,
enderiointegrationtic@5.0.44,
enderioconduitsappliedenergistics@5.0.44,
survivalist@2.1.6,
cfm@6.3.0,
environmentaltech@1.12.2-2.0.20.1,
deepmoblearning@1.12.2-2.5.2,
bigreactors@1.12.2-0.4.5.67,
i18nmod@1.12.2-1.0.7,
soot@1.6,
instantunify@1.1.2,
codechickenlib@3.2.2.353,
coffeework@1.2.8.1,
betteradvancements@0.1.0.77,
ctgui@1.0.0,
simplyjetpacks@2.2.12.65,
cgm@0.12.1,
mineralogy@3.4.0,
xray@1.3.3,
customskinloader@14.7,
itemfilters@1.0.3.12,
hungeroverhaul@1.12.2-1.3.3.jenkins148,
smoothfont@1.12.2-1.16,
jei@4.15.0.268,
custommainmenu@2.0.9,
modulardiversity@1.8,
bibliocraft@2.4.5,
mekanism@1.12.2-9.7.9.380,
thermalfoundation@2.6.3,
bdlib@1.14.3.12,
waystones@4.0.67,
mcp@9.42,
smoothfontcore@1.12.2-1.16,
journeymap@1.12.2-5.5.4,
appliedenergistics2@rv6-stable-6,
naturescompass@1.5.1,
sereneseasons@1.2.2,
enderiointegrationticlate@5.0.44,
compactmachines3@3.0.18,
chameleon@1.12-4.1.3,
conarm@1.2.4,
inventorytweaks@1.63+release.109.220f184,
harvestcraft@1.12.2zb,
foamfixcore@7.7.4,
fossil@8.0.0,
inventorypets@2.0.1,
crafttweaker@4.1.19,
nutrition@4.3.0,
immersivepetroleum@1.1.9,
forge@14.23.5.2838,
bloodmagic@1.12.2-2.4.1-103,
ftbutilities@5.4.0.100,
zerocore@1.12.2-0.1.2.8,
minecraft@1.12.2,
tconstruct@1.12.2-2.12.0.157,
theoneprobe@1.4.23,
immersiveengineering@0.12-89,
psi@r1.1-77,
thermaldynamics@2.5.5,
baubles@1.5.2,
creativecore@1.9.9,
applecore@3.2.0,
yabba@1.1.2.53,
veinminermodsupport@0.38.2,
enderiopowertools@5.0.44,
rustic@1.1.0,
integrationforegoing@1.12.2-1.9,
enderio@5.0.44,
eiintegration@1.5.1.36,
vanillafix@1.0.9-97,
mantle@1.12-1.3.3.55,
quark@r1.5-168,
autoreglib@1.3-30,
storagedrawers@1.12-5.3.5,
jecharacters@1.12.0-3.3.0,
toughasnails@3.1.0.139,
hardcorerevival@1.1.10,
structurize@1.12.2-0.10.79-ALPHA,
enderiobase@5.0.44,
opframe@1.4.0,
minecolonies@1.12.2-0.10.259-RELEASE,
embers@1.13-hotfix2,
appleskin@1.0.9,
enderioconduitsopencomputers@5.0.44,
foamfix@0.10.5-1.12.2,
tinkersforging@1.1.4,
backpack@3.0.2,
soundfilters@0.10_for_1.12,
betterfoliage@2.1.10,
forestry@5.8.2.387 

**Plugins:**

MMCRestrict-1.7.1-API-7.jar 
UniverseGuard-2.17.jar
holograms-3.2.0.jar
PlaceholderAPI-4.4.jar
Nucleus-1.12.2-S7.1-MC1.12.2-plugin.jar
lottery-2.0.2.jar
LuckPerms-Sponge-4.3.109.jar
ServerListPlus-3.4.8-Universal.jar
CatClearLag.jar 
KaroglanSignEditor-3.4.1.jar
UniversalMarket-1.12.2-v1.3.jar
flexiblelogin-0.17.4.jar
EconomyLite-7.1.0-2.15.1.jar 
UltimateChat-1.8.8-b196-Universal.jar 

**Issue Description**
When I put TinkersForgin in sponge server, I found that the temperature of the metal in BrickForge is lost when I drag the metal to my inventory slot (metal lose its temperature property)

Inside the BrickForge
![2019-07-24_21 24 23](https://user-images.githubusercontent.com/39553613/61797322-c27ff980-ae59-11e9-8b5e-7b405b0d7363.png)

When I drag into inventory
![2019-07-24_21 28 03](https://user-images.githubusercontent.com/39553613/61797413-f0fdd480-ae59-11e9-9a29-81f36c91ed61.png)

It cause player can not forge metal through anvil due to low temperature. Besides, console would give a warn log:
![image](https://user-images.githubusercontent.com/39553613/61797626-5782f280-ae5a-11e9-8cfa-4dd05175c3f2.png)

`[Server thread/WARN] [Sponge]: Changes in modded Container were not captured. Inventory events will not fire for this. Container: class com.alcatrazescapee.tinkersforging.common.container.ContainerForge `

I found the same issue on issue[ page ](https://github.com/alcatrazEscapee/tinkers-forging/issues/22)of tinkers-forging, but it looks like author do not want to fix the problem. So I ask you try to fix the issue.

The **full** [server log](https://gist.github.com/Caishangqi/59a16265997a167ea6eb988b3baeda3e) is here.

**Comment by gabizou** [comment]
Sponge can't do any extra transformations on mod classes, however, the mod author can inadvertently support Sponge by modifying their code [here](https://github.com/alcatrazEscapee/tinkers-forging/blob/94a1f0d5d29beb578b63e76545da35aa973ea7e0/src/main/java/com/alcatrazescapee/tinkersforging/common/container/ContainerForge.java#L41) to instead be written as:
```java
@Override
public void detectAndSendChanges() {
  super.detectAndSendChanges();
  detectAndSendFieldChanges();
}
```
Because their core code [here](https://github.com/alcatrazEscapee/alcatraz-core/blob/f1077d25fb187a33f6e06cc7f9ef3f882cca48c4/src/main/java/com/alcatrazescapee/alcatrazcore/inventory/container/ContainerTileInventory.java#L46-L49) will already call the method that [Sponge has modified, to allow for transactional tracking](https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/mixin/core/inventory/ContainerMixin.java#L234-L245), and [performs the same listener update](https://github.com/SpongePowered/SpongeCommon/blob/7a19f298f6b998fbe9106860181df01b5eefedcb/src/main/java/org/spongepowered/common/mixin/core/inventory/ContainerMixin.java#L253-L306) as the mod's [core library code would otherwise call](https://github.com/alcatrazEscapee/alcatraz-core/blob/f1077d25fb187a33f6e06cc7f9ef3f882cca48c4/src/main/java/com/alcatrazescapee/alcatrazcore/inventory/container/ContainerTileInventory.java#L171-L190). I would PR the change (as it doesn't alter the mod's performance, they're using the same fields and methods that Sponge is using), but I'm not 100% positive on their acceptance of such a PR with their prior attitude towards Sponge. 

Otherwise, this isn't so much of an issue that we can fix on our end, as it's something the mod author has to call the same virtual methods that every other container does normally to update their contents to the client.

**Comment by Caishangqi** [comment]
Sent from Mail for Windows 10
