### ISSUE TITLE
Dupe with GriefPrevention 

### ISSUE THREAD

**Issue by soncemvo** [SpongePowered/SpongeForge#2907]
I am currently running

SpongeForge version: 1.12.2-2825-RC3848

Forge version: forge-1.12.2-14.23.5.2838-universal

Java version: latest

Operating System: win10

Plugins/Mods: griefprevention-1.12.2-4.3.0.692, industrialcraft-2-2.8.169-ex112

Theris dupe bug while using GriefPrevention claim system.

Place any block that can hold an item(furnace for ex) in claim, then u need 2 players. One player open block interface, then in !same time! first player took item from block, second player destroy block. As result first player get item, and block drops same item again. Works on ANY block, vanila or moded(tested on ic2) and only in claim.

This dupe didnt work outside GriefPrevention claim.

**Comment by gabizou** [comment]
If the dupe isn't working outside a GriefPrevention Claim, then it's a bug with GriefPrevention. Sponge provides all the events necessary to cancel this, but it's not.

**Comment by bloodmc** [comment]
@gabizou The dupe only occurs when an event is cancelled so of course it's not going to happen outside of protected claims.

**Comment by Shybella** [comment]
This also happens with fluid cows pens.

**Comment by gabizou** [comment]
> @gabizou The dupe only occurs when an event is cancelled so of course it's not going to happen outside of protected claims.

When what event is cancelled? How is it cancelled? There's a lot more information I need to know what sort of bug it can be, as it stands, even with shouldfire, the dupe doesn't occur, so there's no extra amount of events being processed from sponge's end that is leading to a dupe. If GP however is performing a delayed process of an event because the event took place in a claim, then the bug lies in GP performing the event process after Sponge has already moved on. But all of that is speculation, because without the extra information about what the timeline of events are taking place and what GP is cancelling and not cancelling, there's no way for me to know what the bug actually is, let alone being able to say that the bug is within Sponge or GP's handling (in the past, GP actively ignoring events to save performance has caused dupe issues).

**Comment by soncemvo** [comment]
> @gabizou The dupe only occurs when an event is cancelled so of course it's not going to happen outside of protected claims.

btw, theris no canceled events in this scenario, both players have rights in claim
