### ISSUE TITLE
HarvestDropsEvent broken | NoTreePunching broken with sponge

### ISSUE THREAD

**Issue by Bennyboy1695** [SpongePowered/SpongeForge#2997]
**I am currently running**

- SpongeForge version: 2838-7.1.7-RC3926
- Forge version: 14.23.5.2838
- Java version: 1.8.0_201
- Operating System: Linux (5.3.1-1.el7.elrepo.x86_64/amd64)

- Plugins/Mods: Mostly custom plugins, none that interfere with the mentioned event except maybe GriefPrevention
Modpack: RLCraft

**Issue Description**
When breaking blocks in the pack like cobblestone its meant to check if you have a valid tool to break this level of block, if you dont it will clear the drops. But the drops are always cleared even when using above that tier. Upon inspecting i mixin'd in a bunch of logging to the method to show what was happening and right before the block is fully broken everything appears to be cleared about the event.
As seen in the log below. I even try converting the sponge stack to the minecraft stack to see if that helped but it didnt change anything,
This is where the event is used in the mod: https://github.com/alcatrazEscapee/no-tree-punching/blob/1.12-2.0.0/src/main/java/com/alcatrazescapee/notreepunching/ModEventHandler.java#L86

https://gist.github.com/Bennyboy1695/b38be9ed01346db4aa29c8798224626c

**Comment by LXGaming** [comment]
Remove the MultiMine mod (It can be removed Server side without breaking the Client), Because MultiMine essentially re-implements how blocks are broken Sponge isn't able to track those events.

The issue with notreepunching is that the [breakEvent](https://github.com/alcatrazEscapee/no-tree-punching/blob/e1250b30c4498d5104b17709123c0417215367ed/src/main/java/com/alcatrazescapee/notreepunching/ModEventHandler.java#L51) isn't getting fired due to the incompatibility with MultiMine & Sponge this means that it is unable to set the ItemStack in the Capability and so when [onHarvestBlock](https://github.com/alcatrazEscapee/no-tree-punching/blob/e1250b30c4498d5104b17709123c0417215367ed/src/main/java/com/alcatrazescapee/notreepunching/ModEventHandler.java#L86) is called there is no "valid" ItemStack to check resulting in you getting no drops.

MultiMine does manually fire a [BlockEvent.BlockBreak](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/blob/5f71aab490f9bb47aca2764750b2260c298f0e42/MultiMine/src/main/java/atomicstryker/multimine/common/MultiMineServer.java#L137) but from the little testing I did it seemed that Sponge was intercepting the event but not propagating it over to Forge's EventBus but I haven't really bother to look any further into it as simply removing the mod is the safest bet especially if you're running GriefPrevention.

**Comment by gabizou** [comment]
Yeah, reviewing the MultiMine code, there’s no way for us to add compatibility for them because they’re effectively bypassing all of our block handling code (mixing). It’s unfortunate, but we can’t mix in to mod code dynamically to add our hooks for compatibility.
