### ISSUE TITLE
Hearth Well core grafting doesn't work, throws a NullPointerException during PhaseState

### ISSUE THREAD

**Issue by xElementzx** [SpongePowered/SpongeForge#3001]
**I am currently running**

- SpongeForge version: RC3928
- Forge version: Build 2847
- Java version: 1.8.0 221
- Operating System: Windows 10 1903, Ubuntu 18.04 LTS

- Plugins/Mods: SpongeForge, Patchouli-1.0-20, jei 0 4.15.0.289, CraftTweaker2 4.1.19, Hearth Well 0.5.2

**Issue Description**
Core Grafting does not work with SpongeForge RC3928, PhaseState Exception NPE is thrown in console when this happens.
https://youtu.be/OkBXtxKIpD8

Server Log
https://gist.github.com/a5d14018d4c2d618a8e7e3ffea0351aa

**Comment by LXGaming** [comment]
So the issue here (Cause I've had to fix this issue in the TileActivePile from pyrotech) is due to a TileEntity changing a BlockState during its tile tick, Sponge will capture the block change and hold onto it until its finished capturing (This could at the end of the tile tick, server tick or something else entirely)

Because the BlockState hasn't actually changed the subsequent call to getTileEntity typically results in a exception occurring as most mods are expecting the block to have change and their TileEntity to be present.
