### ISSUE TITLE
Sponge duplication bug

### ISSUE THREAD

**Issue by focamacho** [SpongePowered/SpongeForge#3008]
**I am currently running**

- SpongeForge version: 7.1.7-RC3928
- Forge version: 14.23.5.2847
- Java version: 8
- Operating System: Windows 10

- Plugins/Mods:
Mods (9): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Chameleon, SpongeForge, Storage Drawers
Plugins (4): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge

**Issue Description**
1. Place a empty drawer on the ground.
2. Type "/" ou any command in the chat.
3. Right click the drawer with any item in your hand.
4. Infinite items.

Video: https://youtu.be/vDk3xRsKKI0

Works with Mekanism bins & Thermal Expansion cache too.

**Comment by LXGaming** [comment]
Debugging this I've discovered that this issue is very similar to this one:
https://github.com/SpongePowered/SpongeCommon/issues/2187#issuecomment-482799197

This line throws a CommandException:
https://github.com/SpongePowered/SpongeCommon/blob/257331d774c78faf8557a4e8f27dd46ab0bf04af/src/main/java/org/spongepowered/common/command/SpongeCommandManager.java#L340

Which causes it to skip this very important line:
https://github.com/SpongePowered/SpongeCommon/blob/257331d774c78faf8557a4e8f27dd46ab0bf04af/src/main/java/org/spongepowered/common/command/SpongeCommandManager.java#L342

This causes the players inventory to be in a capture state for future events when it shouldn't be.

**Comment by dualspiral** [comment]
https://github.com/SpongePowered/SpongeCommon/commit/341e4cc81c63426795cdfd9065d6b320c0acee72
