### ISSUE TITLE
Immersive Engineering Multiblock crash

### ISSUE THREAD

**Issue by bigenergy** [SpongePowered/SpongeForge#3050]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.8 stable
- Forge version: 1.12.2-14.23.5.284
- Java version: 1.8.0_211
- Operating System: Ubuntu 19.04

- Plugins/Mods:
Mods (123): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AI Improvements, Advanced Solar Panels [GamePoint Edition], Applied Energistics 2, BD Lib, Bad Wither No Cookie! Reloaded, Baubles, Better Questing, BetterBedrockGen, Bewitchment, Bigger Packets, please !, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Blockcraftery, Blood Arsenal, Blood Magic: Alchemical Wizardry, Botania, Botania Needs These Things!, Brandon's Core, Cases, Champions, ChickenChunks, CoFH Core, CoFH World, CodeChicken Lib, CraftTweaker JEI Support, CraftTweaker2, CustomNPCs, Cyclops Core, Draconic Additions, Draconic Evolution, Electro-Magic Tools, Ender IO, Ender IO Base, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, EnderCore, Energy Converters, Engineered Golems, EventHelper, EvilCraft, EvilCraft-Compat, Extra Cells 2, Extra Utilities 2, ExtraBotany, FoamFix, FoamFixCore, Forestry, GamePoint Mod, GamePoint Mod, GenDustry, Grand Economy, Gravitation Suite, Guide-API, Hammer Core, Immersive Engineering, IndustrialCraft 2, Inventory Tweaks, Just Enough Energistics, Just Enough Items, LagGoggles, Lazy AE2, LunatriusCore, MTLib, MagicBees, Mantle, Mekanism, MetalChests, MineTweakerRecipeMaker, Mod Tweaker, Mystical Lib, NoMoreRecipeConflict, OpenBackup, OpenFM, Oxygen Core, Oxygen: Exchange, Oxygen: Friends List, Oxygen: Grand Economy CP, Oxygen: Groups, Oxygen: Mail, Oxygen: Trade, Patchouli, Phosphor Lighting Engine, PlusTiC, Project Intelligence, RF Expansion, RandomPatches, Realistic Terrain Generation, Redstone Flux, Shadowfacts' Forgelin, SpongeForge, Standard Expansion, Surge, TBone, TOP Addons, Thaumcraft, Thaumic Additions: Reconstructed, Thaumic Energistics, Thaumic Periphery, The One Probe, Thermal Expansion, Thermal Foundation, Tinkers Tool Leveling, Tinkers' Construct, ToroHUD Damage Indicators, Trade, Tree Chopper, UniDict, Varied Commodities, WanionLib, gpaddons, libnine, tileentitylimiter

Plugins (23): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, FastAsyncWorldEdit, AdamantineShield, AutoPickup, ClearMob, DupeFixer, EconomyLite, GriefDefender, LuckPerms, MMCRestrict, NanoChat, Night-Vision-Toggle, Nucleus, PixelAutoMessages, Plan, PlayTimeCounter, Simple Scavenger, WorldEdit, spark

**Issue Description**
Any multiblock from Immersive Engineering causes crash if it is built at the intersection of two chunks.

Crash report: https://gist.github.com/bigenergy/83494bac0f18cfe14b62e0174765a8a5

**Comment by bigenergy** [comment]
Related https://github.com/BluSunrize/ImmersiveEngineering/issues/3532

**Comment by gabizou** [comment]
Here's some questions and answers:

1) Does this happen with *just* SpongeForge and ImmersiveEngineering? Your mods list is too large to test by itself, and the crash report lists too many core mods to consider who is changing what to the game.
2) Does the crash happen without any Sponge plugins?
3) Start the server with `-Dmixin.debug.export=true -Dlegacy.debugClassLoading=true -Dlegacy.debugClassLoadingSave=true` and zip up the `CLASSLOADER_TEMP` and `.mixin.out` folders for me please, if and only if you have the game crash with the minimum mods required (for example, since ExtraUtils2 is installed and in the crash log, if it's required, it's required, but Nucleus isn't required, nor is LagGoggles etc.)
4) With the minimum amount of mods + SpongeForge and `-Dsponge.shouldFireAll=true -Dmixin.debug.export=true -Dlegacy.debugClassLoading=true -Dlegacy.debugClassLoadingSave=true` can you list the steps required to set up to crash? I don't know half of what most mods do, but I know how to read code and I don't want to be reading code to figure out how to reproduce the error if I'm trying to solve it.

If you can get that done, I'll be able to maybe pinpoint where the issue lies (if it's sponge code, it'll be fixed, if it's mod code, well, there'll be a nice well explained issue on the mod's issue tracker).

**Comment by bigenergy** [comment]
I checked this on a clean server with a sponge and immersive eng and did not receive such an error.
I think the thing is ExtraUtils2 when connecting transfer nodes to the multiblock IE

**Comment by bigenergy** [comment]
Any ideas?
Excavator some crash https://paste.dimdev.org/izejocotew.mccrash

**Comment by gabizou** [comment]
There's 4 steps that I asked to get clarification. Your crash report doesn't tell me anything more to try and fix the issue or locate where the issue is. 

> 4\. With the minimum amount of mods + SpongeForge and `-Dsponge.shouldFireAll=true -Dmixin.debug.export=true -Dlegacy.debugClassLoading=true -Dlegacy.debugClassLoadingSave=true` can you list the steps required to set up to crash? I don't know half of what most mods do, but I know how to read code and I don't want to be reading code to figure out how to reproduce the error if I'm trying to solve it.

This is very much what I need to know at this point.

**Comment by dimon7147** [comment]
I have same issue with IE multiblock constructions.
You can watch the video and find out how you can crash client with IE arcfurnace multiblock structure. (and some others but this cause crash more often)
I also disabled foamfix, betterfps, optifine before making this video.
https://www.youtube.com/watch?v=2IelBkqsxyw&feature=youtu.be
And also crashlog https://paste.dimdev.org/sahevawuqe.mccrash

UPD: Player rebuild arcfurnace in another chunk and no crash.

Java 1.8.0_201
Sponge 1.12.2-2838-7.2.1-RC4010
Forge 1.12.2-14.23.5.2847

And sometimes i receive following messages in console. I do not know whether this is related to this topic at all or not. But suddenly it will help.
![image](https://user-images.githubusercontent.com/20266345/78194577-3d3bf280-7486-11ea-8e7d-e84cf78302f1.png)

**Comment by bigenergy** [comment]
https://pastebin.com/MPggj3Vc
same crash excavator

An error occurs on this line
https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/blocks/metal/TileEntityExcavator.java#L344

@gabizou I think that something is not working properly in the sponge, since it cannot be played on the server without a sponge

**Comment by bigenergy** [comment]
@gabizou I did everything you said, here is zip archive
https://drive.google.com/file/d/1EwQKi_Wv5A96nsDmHyacbi3D0FbV2xsy/view?usp=sharing

Please fix this error.

**Comment by bigenergy** [comment]
@dualspiral @gabizou will you fix the error? Since the beginning of the year, a lot of issue have accumulated, 1.12.2 is no longer lts?

**Comment by gabizou** [comment]
> will you fix the error?

Since the issue is still open, yes, we'll get to fixing it. Just might not be highest priority.

>  Since the beginning of the year, a lot of issue have accumulated

Aside from stating for the Nth time: Sponge is purely a volunteer project, everyone volunteers their time when they want and how they want. I do have a fairly limited amount of time, and as does the rest of the team, and some issues are easier than  others to reproduce and fix. This issue is somewhat complicated by itself due to the nature of the logic that gets called, so it's going to take someone much longer to actually find the bug and a bit more time to figure out a proper fix.

> 1.12.2 is no longer lts?

We would've announced that long in advance if it was no longer LTS. As you can see from the commit history and reporting history, there's still actively maintenance being done.

**Comment by bigenergy** [comment]
Thanks for the answer! We will wait for a solution.
