### ISSUE TITLE
Incompatibility with JEID and SpongeForge 7.1.9 and Mixin 0.8

### ISSUE THREAD

**Issue by LordRalex** [SpongePowered/SpongeForge#3069]
- SpongeForge version: 1.12.2-2838-7.1.9

- Plugins/Mods:
JustEnoughIDs-1.0.3-48

After the update to Mixin 0.8, servers that use JustEnoughID no longer start up with the below crash.
Since JustEnoughID uses a custom mixin to do constructor hacks (which has been told it's not good), there is no way to resolve this as a user except to remove JEID from the server. And with the amount of IDs needed for 1.12, this basically forces the server to either not use Sponge, or to use 7.1.8.

This does not occur with other mods that use the shipped Mixin (bewitchment is an example mod I used which would properly start up and it uses the 0.7 Mixin).

I do not expect there is anything that Sponge can do about this, however filed an issue for tracking and reporting to JEID.

```
[16:39:13] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
java.lang.IllegalAccessError: tried to access class org.spongepowered.asm.mixin.transformer.MixinTransformer from class net.minecraftforge.fml.common.Loader
	at net.minecraftforge.fml.common.Loader.handler$zze000$beforeConstructingMods(Loader.java:1632) ~[Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:594) ~[Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) ~[FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

https://gist.github.com/LordRalex/ead30e177ab42facb34007a1ac466d5a

**Comment by gabizou** [comment]
So the problem code in question:

[MixinTransformer became an abstracted transformer](https://github.com/SpongePowered/Mixin/blob/master/src/main/java/org/spongepowered/asm/mixin/transformer/MixinTransformer.java#L44) with Mixin 0.8, and JEID is [injecting into Loader to ask MixinTransformer to reload configs](https://github.com/DimensionalDevelopment/JustEnoughIDs/blob/ccc581a76fefcd605c58897599f68e967a5bb2ec/src/main/java/org/dimdev/jeid/mixin/init/MixinLoader.java#L50-L58). Of course, the problem is that `MixinTransformer` is now `package private` so inaccessible outside the transformer package.

You're right in saying that there's nothing Sponge can do, but a "lazy workaround" can be done on JEID to use `Class.forName` etc. reflection. Alternatively, they can update their mixin code since I'm fairly certain that code was initially added for some unmanaged handling that Mixin can now handle. Would need @Mumfrey to comment or correct me of course....

**Comment by icemagetv** [comment]
Since this is the sponge github;
Or downgrade to Sponge 7.1.8 until mod authors update their packs for Mixin 0.8 - AFAIK the biggest change for 7.1.9 from 7.1.8 will be mixin - which is going to break a few things.

While mixin updates have previously stressed backwards compatibility, it has been documented that the update to 0.8 may break things - https://github.com/SpongePowered/Mixin/wiki/Release-Notes---Mixin-0.8

**Comment by icemagetv** [comment]
Your options appear to be get an updated version of the mod, or downgrade sponge to 7.1.8 due to the mixer update - https://github.com/SpongePowered/Mixin/wiki/Release-Notes---Mixin-0.8 - which may break other mods.

**Comment by gabizou** [comment]
> which may break other mods.

Not necessarily break other mods, it's other mods that are using *internal code of our own tools* without version checking or any other sanity checking. As it is, I'm going to leave the issue closed since I've already said that there's nothing we can do ourselves to resolve the startup issue.

**Comment by Mumfrey** [comment]
I mentioned in the 0.8 release notes that certain changes would be backward-incompatible but that I had gone to some lengths to ensure that at least the failures would provide a deterministic failure mode, and those backward compatibility shims would work for mods using the features in question.

On the other hand, mods using reflection to access internal parts of mixin are not in any way supported, and it's absolutely not Sponge's responsibility to account for their recklessness.
