### ISSUE TITLE
Hammer Core 2.0.6.12 Update Breaks SpongeForge

### ISSUE THREAD

**Issue by Falcion** [SpongePowered/SpongeForge#3084]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.9
- Forge version: forge-1.12.2-14.23.5.2838-universal
- Java version: Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_241
- Operating System: Windows 10:amd64:10.0

- Plugins/Mods: FoxCore, FoxGuard, LuckPerms, CommandUtils, MultiChat, MMCLogger, EasyKits, StatusProtocol, ServerListPlus, PlayerJoinMessage, MMCReboot, Vanish, KeepInventory, Item Blacklist, World Edit CUI Forge Edition 2, MysticalLib, Mystical World, Roots, ThaumicJEI, AbyssalCraft Integration, AbyssalCraft, AkashicTome, Albedo, Apotheosis, AppleSkin, Astral Sorcery, AutoRegLib, B.A.S.E, Baubles, BetterFPS, Biomes O'Plenty, BloodMagic, Botania, Botanic Additions, Carry On, Ceramics, Chameleon, Chisel, CodeChickenLib, COFHWorld, Common Capabilities, ContainerFix, Controlling, CraftTweaker 2, CTM, Cucumber, Custom NPCs, Cyclic, Cyclops Core, Dynamic Surroundings, Electroblobs Wizardry, Embers Rekindled, EvilCraft, Expanded Equivalence, Extended Crafting, Extra Alchemy, Extra Spells, Extra Utilities 2, FoamFix, Forbidden Arcanus, FTB Backups, FTB Library, FTB Quests, FTB Utilities, Guide-API, HammerCore, Hwyla, Inventory Tweaks, Iron Backpacks, Iron Chests, Item Filters, JEI, Journey Map, JER, Less lag, Mantle, McJTYlib, Minerva Lib, Mod Name Tooltip, MouseTweaks, Mystical Agradditions, Mystical Agriculture, OpenBlocks, OpenModsLib, Optifine, Ore Excavation, OreLib, Patchouli, Phosphor, Placebo, ProjectE, Quark, Reliquary, Roguelike Dungeons, Storage Drawers, Storage Drawers Extras, TC6 Aspects, Tinker Construct, Thaumcraft, Thaumic Additions, Thaumic Equivalence, Thaumic Inventory Scanning, Thaumic Periphery The One Probe, Tinker Tool Leveling, Totemic, Twilight Forest

**Issue Description**
I tried everything I could, renamed files, downloaded new and old versions, removed BetterFPS and FoamFix, removed mods that affect the loading of the world, tried to run without Sponge, the build works perfectly and the server too, tried to run without plugins, allocated less and more RAM.
Nothing solves the problem, please help!

My first error that is attached on the forum:
[latest.log](https://gist.github.com/FalcionML/9ce226679af3e3ae18d55ab57b80ca4b)
[debug.log](https://gist.github.com/FalcionML/a0ff9b4ac15c151bf67784913a7521de)

Attached files with the recommended Sponge:
[debug.log](https://github.com/SpongePowered/SpongeForge/files/4213021/debug.log)
[latest.log](https://github.com/SpongePowered/SpongeForge/files/4213022/latest.log)

Without plugins, BetterFPS and FoamFix (Less Lag removed too):
[latest.log](https://github.com/SpongePowered/SpongeForge/files/4213038/latest.log)
[debug.log](https://github.com/SpongePowered/SpongeForge/files/4213039/debug.log)

**Comment by gabizou** [comment]
Add `-Dmixin.dumpTargetOnFailure=true` before the `-jar` portion on your startup command. Then zip up and export the `.mixin.out` contents please.

**Comment by Falcion** [comment]
> Add `-Dmixin.dumpTargetOnFailure=true` before the `-jar` portion on your startup command. Then zip up and export the `.mixin.out` contents please.

Here's the archive:
[.mixin.out.zip](https://github.com/SpongePowered/SpongeForge/files/4218363/default.mixin.out.zip)

**Comment by gabizou** [comment]
[HammerCore added a "tick slip" feature](https://gitlab.com/DragonForge/HammerLib/-/commit/1dd7fc6a099c4a950cd2116d30b7d49e8f4da8d7#9c8ac65ab9fea438ab9513070cb18fc6117f0eb6_220_206) recently and because they're replacing a core method that Sponge otherwise has been using for the last several years, it no longer is compatible with the changes necessary for Sponge to function with it's tracking system. 

For the HammerCore dev (@Zeitheron) , it'd be possible to simply implement this tick slip system without replacing the `ITickable.update()` call by implementing it within their interface and overriding your own logic to determine if `update()` should continue or not, reducing the invasive changes to a core logic method, then [Sponge can keep using the same method to wrap around to support it's tracking systems](https://github.com/SpongePowered/SpongeCommon/blob/ae9221f088b0e57749301651808785182298209a/src/main/java/org/spongepowered/common/mixin/core/world/WorldMixin.java#L422) (which is [overridden for it's ultimate tracking logic here](https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/mixin/core/world/WorldServerMixin.java#L1622)).

For the user (@FalcionML): Unfortunately, unless HammerCore reverses course and doesn't do it's changes as it is currently doing, SpongeForge will no longer be compatible with the newer versions of HammerCore.

**Comment by Zeitheron** [comment]
Tick slip is intended to work with any tile entity from any mod. I added a config to disable this feature, and won't do any more on my side either.

**Comment by Explosivee** [comment]
> Tick slip is intended to work with any tile entity from any mod. I added a config to disable this feature, and won't do any more on my side either.

In which part of the config we can disable this feature? I couldn't managed to find it.

**Comment by gabizou** [comment]
This has since been fixed with a configuration workaround from HammerCore, thanks @Zeitheron!

For those that run into the crash, you can edit the file in:
`<minecraft_game_dir>/asm/hammercore.xml`
and change `<entry key="World.ITickable.Override">true</entry>` to `false` will allow Sponge to start up again.

We'll be adding some extra "known" warning about the change so that if the version of HammerCore matches (or doesn't, if it's 2.0.6.12) we can advise appropriately. Many thanks again for giving the config option so we don't have to resort to massive workaround hacks :D

**Comment by PepijnTrampe** [comment]
anny update im getting the same issue where do i poste the bootstrap?
