### ISSUE TITLE
[Bug] ClickInventoryEvent.NumberPress copys items

### ISSUE THREAD

**Issue by SettingDust** [SpongePowered/SpongeForge#3097]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.10
- Forge version: forge-1.12.2-14.23.5.2847-universal
- Operating System: Windows 10
- Plugins/Mods:
None. Just my own plugin. Code below

**Issue Description**
When pressing any number hover on craft slots in survival inventory, the items will be copied.
```
@Plugin(id = "test", name = "test", version = "1.0")
public class Test {
    @Listener public void onClickInventoryNumberPress(NumberPress event) {
        event.setCancelled(true);
    }
}
```
Click 4
![image](https://user-images.githubusercontent.com/19922286/75681242-26ab4b80-5cce-11ea-8351-aa74a472c3ac.png)

**Comment by Faithcaio** [comment]
Cause is the Transaction on the Slot in the crafting grid is not getting captured for this event.
Capture is turned off here:
https://github.com/SpongePowered/SpongeCommon/blob/4a9742b465d095769fa4e6ca5fbf22865e3de87b/src/main/java/org/spongepowered/common/event/tracking/phase/packet/PacketPhaseUtil.java#L102
so that changes made in event-transactions do not get captured.
