### ISSUE TITLE
worldgencrash on old spongeforge

### ISSUE THREAD

**Issue by Lanyangzhi** [SpongePowered/SpongeForge#3102]
- SpongeForge version: 2768-7.1.6-RC3686
- Forge version: 2768
- Java version: 8
- Operating System:linux

[crash-2020-03-12_00.11.27-server.txt](https://github.com/SpongePowered/SpongeForge/files/4319320/crash-2020-03-12_00.11.27-server.txt)

I can't upload the full log, it has 175MB

**Comment by gabizou** [comment]
Try against 7.1.10 please.

**Comment by Lanyangzhi** [comment]
i have too many mods,cannot change forge version
7.1.10 unable to work with forge2768

**Comment by dualspiral** [comment]
I'm sorry, but we're not going to go back to fix an old version like this - as newer versions are where the fixes go. This issue may/possibly/probably has been fixed in later versions. Due to our limited resources we can only support the latest recommended (and latest) builds of Sponge.

You are welcome to try later builds of SpongeForge as you see fit as one of those builds might work with the forge version you seem to be locked to, as one of those might fix your issue. However, the better solution is to try to update your mods and then be able to update to Forge to make use of the latest SpongeForge version.
