### ISSUE TITLE
Crash involving Sponge powered.

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#3147]
I am currently running a modded Minecraft and I had this issue however I don't know why sponge powered is involved. 
- SpongeForge version: n/a
- Forge version: 1.12.2-14.23.5.2856
- Java version: 8.0.2510.8
- Operating System: 64 bit Windows 10

I know what mods caused the crash but I don't know how to resolve it, haven't used much java.
The mods in question are Bewitchment and Patchouli. The crash doesn't mention these mods but when removed Minecraft works fine. Here is the crash report.

[crash-2020-05-01_06.45.13-client.txt](https://github.com/SpongePowered/SpongeForge/files/4562818/crash-2020-05-01_06.45.13-client.txt)

**Comment by RedNesto** [comment]
This error has nothing to do with Sponge, it's not even installed on your server.
This is likely caused by mods using different versions of Mixin. I've had a similar issue with an outdated version of vanillafix so try to update it to 1.0.10-150.
If that doesn't work then ask the authors of the mods you suspect, that issue is not related to SpongeForge in any way.

**Comment by ghost** [comment]
Ok thank you. I just saw individuals with the same error attributing it to sponge because it was mentioned in the error. Thanks for the quick response.

- Jachute

**Comment by ghost** [comment]
The issue was an outdated version of VanillaFix. Thanks again!
