### ISSUE TITLE
[1.12.2] Server crash during tile entity registration (from #3122)

### ISSUE THREAD

**Issue by stfwi** [SpongePowered/SpongeForge#3155]
**I am currently running**
- SpongeForge version: 1.12.2-2838-7.2.1
- Forge version: 14.23.5.2847
- Java version: 1.8.0_252
- Operating System: Linux

Hi guys, have to revive issue #3122 ("[1.12.2] Sideness handling for nested classes in tile entity registration hook"). We concluded there that with a dead-reference fix in the ED mod the issue could be circumvented. Unfortunately I did get another report here after that, same situation:

- issue https://github.com/stfwi/engineers-decor/issues/96
- crash report: https://github.com/stfwi/engineers-decor/files/4604265/crash-report.zip

... as a reference the complete crate class is here:

- https://github.com/stfwi/engineers-decor/blob/master/1.12/src/main/java/wile/engineersdecor/blocks/BlockDecorLabeledCrate.java

Could you please take a look again at your class scan? The issue on servers is only in combination with Sponge, and I am admittedly out if ideas.

**Comment by gabizou** [comment]
Caused by: java.lang.RuntimeException: Attempted to load class wile/engineersdecor/blocks/BlockDecorLabeledCrate$BGui for invalid side SERVER

Mod class is referencing client class either statically or another way. 

The [Sponge mod id resolution](https://github.com/SpongePowered/SpongeForge/blob/02c60ce95e25cf00ee2ace7fd3d4dec45b15eb6e/src/main/java/org/spongepowered/mod/util/StaticMixinForgeHelper.java#L320) is rather simple, but because the mod class has a client side reference, it's going to throw this exception.

**Comment by stfwi** [comment]
Not so fast, please. There are no references to the client side GUI class in my module, especially not during the registration. As I already said in the related issue here in the repository, you guys appear to scan a class without checking for nested client-only classes. There are no mods except Sponge causing trouble with that. Please check your code. I did check mine,

**Comment by phit** [comment]
there is right at the end of the file https://github.com/stfwi/engineers-decor/blob/master/1.12/src/main/java/wile/engineersdecor/blocks/BlockDecorLabeledCrate.java#L591

you should read https://www.minecraftforge.net/forum/topic/22558-why-not-to-use-sideonly/

it should be okay if you mark that method that references bgui as clientside and whatever calls it

**Comment by gabizou** [comment]
So instead of opening a new issue, continue the discussion in the old issue?



> There are no references to the client side GUI class in my module, especially not during the registration.

There are no obvious references, but there's some class level static references. The simple fact that `class.getSimpleName()` fails because it's referencing a client only class means that the class is referencing the client name in some way. I'm not saying that you're explicitly doing it, but the way that your class is set up, it's more likely a nice little bug happenstance that side only doesn't get stripped at that minute level when you nest your classes like so. 

That being said, this is the first time I've ever seen this sort of issue potentially due to the class structure you're building, since all previous issues have been related to the `@SideOnly` annotation not being applied in some reference.



> As I already said in the related issue here in the repository, you guys appear to scan a class without checking for nested client-only classes.

Sponge shouldn't actually be caring about sided classes, it's the responsibility of the mod to apply the annotations correctly so there's no client-side code being referenced, this is why it's generally recommended to have the client only classes completely split from the class file itself, so you don't have any references, even synthetic ones (like it appears may be the case).


> There are no mods except Sponge causing trouble with that. Please check your code. I did check mine,

I do check my code, pretty often, and it's within the contract that no one should have to worry about side only checks when referencing classes via reflection, if there are leaks, then that's on the mod author providing the class that didn't apply the side only annotation correctly in some way or another.


Phit's response pretty much sums it up: Any sort of client-side class references are still included in reflection api. Nothing sponge can really do to prevent that (you can even refer to the [issue we had](https://github.com/SpongePowered/SpongeForge/issues/2770) in the past that's caused by [class.getMethods()](https://github.com/SpongePowered/SpongeCommon/commit/d84fdaec9e338a7d3b14e192be36ea94ecf2405a) exposing [client-references](https://gitlab.com/BetterWithMods/1.12/BetterWithMods/-/commit/8f4546c8b5031a1d787b3b4e153004a274188309)) because at a certain point, the client side classes should have no references in server-only code.

**Comment by stfwi** [comment]
Ok, thanks phit for taking a glimpse, and gabizou for the clarification.
(The issue was not reopened because I do not have a reopen option, neither for this thread).
I'll double check if the additional marker does the trick, or if other measures can circumvent that problem. Cheers -
