### ISSUE TITLE
Sponge has problems with executing Minecraft Functions properly Part 2

### ISSUE THREAD

**Issue by CedeLovesKat** [SpongePowered/SpongeForge#3160]
**I am currently running**

I am currently running
SpongeForge version: spongeforge-1.12.2-2838-7.2.2-RC4027
Forge version: 3238
Java version: 8
Operating System: x64 Windows 10

Mods: [19:57:48] [Server thread/INFO] [minecraft/DedicatedServer]: Mods (24): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Armourer's Workshop, Chisels & Bits, CreativeCore, CreativeCoreDummy, CustomNPCs, Dynmap, Fluids++, LegendaryPlus, LittleTiles, LittleTilesCore, MrCrayfish's Furniture Mod, Pixelmon, Pixelmon Trainer Commands, SpongeForge, Thut Core, Thut's Elevators, ThutCore Compat, Wondertrade

sponge plugins:
[19:57:55] [Server thread/INFO] [nucleus]: Server ran the command: /sponge plugins
[19:57:55] [Server thread/INFO] [minecraft/DedicatedServer]: Plugins (17): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, CarrotShop, CommandSigns Reloaded, GriefPrevention, LuckPerms, Nucleus, PixelHunt, PixelMoney, PixelmonBroadcasts, PixelmonEconomyBridge, SimpleDexRewards, Total Economy, VoxelSniper, WorldEdit

Hey : )
I made a world extra for you where you can test out the Function stuff without setting up anything too complicated!

The world: https://drive.google.com/file/d/1S5M5JWU08ER65OSykBNVjJUKnnR-jUmA/view

Ingame Manuals: 
Apply those commands to yourself in order to hear the music:
/scoreboard players set @a MusicCooldown 0
/scoreboard players set @a MusicState 1

Put a Carrot on a Stick on to your secondary hand with "F"
Switching between them will trigger the music state from 0 - 1
This can be seen at the command block redstone torch. When your Music State is at 0 you cant hear music within the areas. If it is at 1 you can hear music. The Musicstate depends on having a Carrot on a Stick in your inventory or not. It behaves as our radio.

By rightclicking while having the carrot on a stick equipped in our secondary hand we can stop/reset the Music Timers. This is needed to switch to a new music area and also applies a stopsound command that stops any music right now and the music will refresh if you still stand within a music area.

I made 2 Music Areas. The first one is the Iron Block square which plays the "cat.record" music. If you stay within the Gold Block and reset your music with the carrot on a stick right click you can hear the "mellohi.record". The first command in the function line has always priority. Thats how you make Music within areas. That means, no matter what, the gold area has always priority over the iron area as long as the gold line string stands above the iron line in the function

I hope you can fix the sponge issue : (

You can test it in SP at first to see if it works

Good Luck : )

Log: https://gist.github.com/CedeLovesKat/1c401a1e12367d8bb06910e7a3fab9e1

**Comment by dualspiral** [comment]
There are some issues with the report that makes it very difficult to work out what might actually be wrong:

* The mod/plugin list is way too complicated. For example, we probably don't need most of mods and plugins. Which ones do we need?
* I downloaded the world, which world is the problem? I haven't run it, but I know I'm going to get some errors and warnings when trying to run it because I don't have the mods.
* It's not clear what should happen vs what does happen. You've told us how to reproduce what you want to happen but I have no idea what actually happens. We need to know
  * What you expect to happen (sorta explained there)
  * What _does_ happen (not explained at all)

This is why I asked for a **simple** reproduction. By just throwing a world at us and not telling us what is wrong we have no idea where to start, and we have a lot of code we have to go through.

Please help us to help you by providing simple steps, perhaps a simple function. A small world is fine if it really comes to it, but please make sure that there are no mods involved if they aren't needed, similarly with plugins. With our limited time, we cannot setup an entire server world with all these mods we are unfamiliar with, only to have no idea what we're looking for.

**Comment by CedeLovesKat** [comment]
There are no mods needed duh ...
 WHat part you dont understand?

The problem is: Music doesnt play as it should on sponge

**Comment by Zidane** [comment]
Okay since you have decided to not do as dual asked, I have decided to not investigate your issue further.

**Comment by clienthax** [comment]
Tested, works fine for me 🤷‍♂️
