### ISSUE TITLE
Stuck on "Creating injector in stage 'PRODUCTION'"

### ISSUE THREAD

**Issue by cifesk** [SpongePowered/SpongeForge#3161]
- SpongeForge version: 1.12.2-2838-7.2.2-RC4027
- Forge version: 1.12.2-2838
- Java version: 1.8.0_252
- Operating System: Ubuntu 20.04

It doesn't open even when I don't have any mod on. I have reinstalled sponge and the server multiple times but the issue continues. It gets stuck forever in "Creating injector in stage 'PRODUCTION'". I've waited for HOURS for it to boot but it never does.

Command I use to launch the server: java -Xmx1024M -Xms1024M -jar forge-1.12.2-14.23.5.2838-universal.jar -nogui

At first I thought it was a RAM issue, but using the exact same files from the VPS on my computer it doesn't launch as well, maybe I did something wrong.

Log: https://gist.github.com/cifesk/cc6d9d90a3f8e5cde36714563c43ad0e

**Comment by clienthax** [comment]
[09:05:29] [Server thread/INFO] [Sponge]: Found mcmod.info at jar:file:/home/ubuntu/minecraft/./mods/spongeforge-1.12.2-2838-7.1.8.jar!/mcmod.info

Give us the updated log and debug log

**Comment by cifesk** [comment]
[latest.log](https://github.com/SpongePowered/SpongeForge/files/4649492/latest.log)
[debug.log](https://github.com/SpongePowered/SpongeForge/files/4649493/debug.log)

**Comment by clienthax** [comment]
[09:05:01] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from spongeforge-1.12.2-2838-7.1.8.jar
[09:05:01] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from spongeforge-1.12.2-2838-7.2.1.jar

You have multiple sponge versions in the mods folder.

**Comment by cifesk** [comment]
Even after deleting the other version it still gets stuck in the same spot.

**Comment by clienthax** [comment]
Then provide logs.

**Comment by cifesk** [comment]
[latest.log](https://github.com/SpongePowered/SpongeForge/files/4649555/latest.log)
[debug.log](https://github.com/SpongePowered/SpongeForge/files/4649556/debug.log)

**Comment by clienthax** [comment]
Does this work without any mods?

And are you using the server version of pixelmon? (lower ram requirements)

**Comment by cifesk** [comment]
It does not work without any mods.
I am using the latest Pixelmon Reforged version, 7.2.2.

**Comment by clienthax** [comment]
> It does not work without any mods.

Hmm, that's worrying, Can you try it with no mods locally with say 4G ram?

**Comment by cifesk** [comment]
I am sorry that I do not know how to do that :(
Can you tell me how to do it?

**Comment by clienthax** [comment]
> I am sorry that I do not know how to do that :(
> Can you tell me how to do it?

```
 java -Xmx4G -Xms4G -jar forge-1.12.2-14.23.5.2838-universal.jar -nogui
```

**Comment by cifesk** [comment]
Sadly my VPS only has 1 GB of RAM. It runs on Windows VPS just fine as well, but lags more because Windows is more heavy, with also 1 GB of RAM.

**Comment by clienthax** [comment]
To be blunt, 1GB of ram will not be enough for a 1.12.2 server with sponge and is likely the cause of the problem here.

**Comment by cifesk** [comment]
But since it runs on Windows (but lags more, with also 1 GB of RAM) and there's always more free space of RAM on Ubuntu, shouldn't it run better?

**Comment by dualspiral** [comment]
Not necessarily. 

I'm guessing that your Windows machine is your local machine and has more than 1GB RAM available to the OS (must be at least four), while your Linux VPS has 1GB RAM available to the entire system. If it's the latter, that's the problem, and this ticket can be closed.

Remember that the OS requires some RAM too - so while your Windows machine will have 1GB RAM spare after Windows uses the RAM it needs, the Linux machine won't because it will be using some of that 1GB for itself. Thus, you try to allocate 1GB RAM and it fails because you don't have that amount remaining. Such freezing like this is totally consistent with that - you don't get an Out of Memory error because the JVM hasn't hit the limit you set, but it can't hit that limit because you don't have enough free RAM to do so (though it's anybody's guess as to why the JVM doesn't just error out in these cases...)
