### ISSUE TITLE
Pixelmon Johto map isn't supported by SpongeForge

### ISSUE THREAD

**Issue by ajzhang2** [SpongePowered/SpongeForge#3181]
It works without SpongeForge, but SpongeForge says it's outdated.

**Comment by dualspiral** [comment]
* The template is there for a reason. Please use it. If there is a message about things being outdated, versions are especially important.
* What message?
* Logs?

I'm closing this because absolutely no effort went into this message and the template was just blown away. Also, Sponge does nothing with actual maps, so I'm willing to bet the message you saw was a warning and actually, everything is fine.

If there is an actual bug, use the template and give us all the information it asks for. This issue is useless.
