### ISSUE TITLE
Sign Exploit

### ISSUE THREAD

**Issue by Shybella** [SpongePowered/SpongeForge#3199]
**I am currently running**

- SpongeForge version: 7.2.3 (Recommended)
- Forge version: 2854
- Java version: 1.8
- Operating System: null

- Plugins/Mods: Spongeforge/Forge.

**Issue Description**

There seems to be a exploit similar to the OP sign exploit from 1.8.4 that's allowing JSON to be executed via a sign without user privileges. 

I was able to dump the NBT block data from the blank sign on my local machine, I can provide the server/zip. Link: https://i.imgur.com/9sJlqLf.png

Believe it's related to something like this: https://github.com/devversion/Forge-OP-Exploit/blob/master/src/main/java/items/NBTSign.java

I talked to Bloodshot, he asked me to open a report here. 

Thank you.

**Comment by dualspiral** [comment]
This is something I looked at before and could not get it to fire. We have it set up so that someone trying to execute commands on a sign require the command block permission. I:

* Created a sign with some command JSON in
* Placed the sign
* Tried to execute the sign by clicking it

I tried a variety of combinations and could not get the sign to do anything other than sit there and look pretty when I wasn't OP or had a permissions plugin installed. I traced this all the way down to a permission check we are blocking execution.

With this in mind, I need concrete steps to reproduce without any mods. From a fresh world, would you be able to tell us how to do it?

If you can only do this with mods involved, my suspicion is that mods may be playing about with the interact logic and it might be on them to fix.

**Comment by Shybella** [comment]
Thanks for the reply. 

I do not have a method of replication. It seems to be a private exploit. Do you have another alternative means of communication instead of here. I would love to send you more information.

Thank you.

**Comment by Shybella** [comment]
https://github.com/SpongePowered/SpongeCommon/commit/83098c1f05fdb40a8d3d5e7af047a20c7d2ebae0#diff-950d0274e9ca78827f51a7d23895437dR178

https://github.com/SpongePowered/SpongeCommon/commit/83098c1f05fdb40a8d3d5e7af047a20c7d2ebae0

**Comment by Shybella** [comment]
This code should have never been removed.
