### ISSUE TITLE
Garbage Collector may close the Server..

### ISSUE THREAD

**Issue by faitarus** [SpongePowered/SpongeForge#3286]
### Version

1.12.2-2838-7.4.7

### Operating System

CentOS 7

### Java Version

 java-1.8.0-openjdk.x86_64 

### Plugins/Mods

```shell
Pixelmon
```

### Describe the bug

During the last Update of Spongeforge the Garbage Collector seems to make the Server Crash.

Before the Update the following Start.sh woked well:

java -XX:+UseG1GC -XX:MaxGCPauseMillis=50 -XX:CompileThreshold=100 -XX:MaxPermSize=12048M -Xmx12048m -jar server.jar

During my tests, the Server Crashes and the last Console message was "Killed 20000".
I did different researches and i figure out, that the following Start.sh solved this:

java  -XX:MaxPermSize=12048M -Xmx12048m -jar forge.jar

I think the GarbageCollector Prints a Console Output which makes the server Crash..

**Comment by dualspiral** [comment]
> I think the GarbageCollector Prints a Console Output which makes the server Crash..

This is something you need to show us.

This is definately something we would need logs for - "Killed 20000" means nothing to me - _but I also don't see this as a SF issue specifically_. Garbage collection feels a bit like a black art sometimes - and sometimes you'll need to tweak the GC. What works for one doesn't necessarily work for another.

It's likely this will just be closed for that reason - but let's see the logs first.

**Comment by faitarus** [comment]
![2022-01-15 18_11_46-Window](https://user-images.githubusercontent.com/60380712/149980384-e360e77d-b159-4091-aba4-b4400badc8f5.png)
![2022-01-15 20_37_26-mods](https://user-images.githubusercontent.com/60380712/149980554-87862ab0-bca1-473d-ab79-0ebb908da319.png)

For the Start.sh i used this Tutorial in which it explains how to create a Centos automatic restart Sh-File:
https://www.youtube.com/watch?v=A39iC5LpgXY&ab_channel=Mighty

**Comment by faitarus** [comment]
![sh_2](https://user-images.githubusercontent.com/60380712/149981162-f641cbab-38f0-4c7d-932f-f804b7af84aa.png)
![sh_1](https://user-images.githubusercontent.com/60380712/149981168-38929c84-665b-472c-bfc9-9c4830896269.png)
The SH-Files looks like this and i use it for other non-sponge Servers without any problems

**Comment by dualspiral** [comment]
Text files, not screenshots please.

**Comment by dualspiral** [comment]
...that said - those errors are something external to Sponge killing the server, those numbers you refer to are proccess IDs. They're not messages because of the garbage collector. For example, I just killed a `bash` shell using `kill -9` and got the message:

```
[1]    284 killed     bash
```

Admittedly, I'm not running CentOS here, I'm running Ubuntu 20.04, and I'm prmarily using `zsh` rather than plain `sh`, but the concept is the same. I think something else is killing your server, probably something that monitors memory usage, but it's not Sponge itself.

Now, I still find it interesting that the GC flags have had to change - but there are also problems with your flags. For example, `XX:MaxPermSize` does nothing, and in Java 7, setting it that high would be catastrophic. If you're going to use G1GC, there are plenty of other flags that you should probably set - GC tuning is very fickle.

We recommend the use of Aikar's flags: https://aikar.co/mcflags.html. You're also using Pixelmon I see, so I'd advise talking with that community too.

Ultimately, not a Sponge issue.
