### ISSUE TITLE
Update sdk to ForgeGradle 2

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/SpongeForge#377]

**Comment by liach** [comment]
Btw you cannot just add spongeforge from maven, because you cannot get spongecommon from maven. Example: https://travis-ci.org/ForgeEssentials/ForgeEssentials/builds/81361129

**Comment by Minecrell** [comment]
You could try `transitive = false` if you're using Gradle for now. We're aware of this problem and will be most likely fixed together with this issue.

**Comment by JBYoshi** [comment]
Also, the dependency name in the SDK `build.gradle` will need to be changed from `org.spongepowered:sponge` to `org.spongepowered:spongeforge`.

**Comment by kenzierocks** [comment]
If https://github.com/SpongePowered/SpongeCommon/issues/289 is resolved, we should also use `deobfCompile` in the SDK instead of `compile`.

**Comment by Zidane** [comment]
@Minecrell 

This has been MIA for months now...I want this updated ASAP. This also needs to be usable for SpongeVanilla as well.

**Comment by simon816** [comment]
I have a PR open https://github.com/SpongePowered/SpongeForge/pull/519

**Comment by Minecrell** [comment]
@Zidane That was kind of on purpose, because the intention most people have when using that SDK is for testing for which the sdk is definitely the wrong choice, because it a) locks your plugin to be tested on one platform and b) introduces compile time dependencies on the Minecraft source which a normal Sponge plugin shouldn't have.

The only reason why someone should use the SDK is for making a Sponge plugin that is also a Forge mod (**and depends on SpongeCommon/SpongeForge implementation classes**), or if someone wants to make a Sponge plugin for SpongeVanilla (**and depends on SpongeCommon/SpongeVanilla implementation classes**).

For all other use cases:

- For testing they should either [add it manually to an implementation setup it their IDE](https://docs.spongepowered.org/en/plugin/debugging.html), I'm planning to add something to SpongeGradle which will allow easier testing on multiple platforms. The base has already been made with the plugin-meta integration, however the exact implementation is not that easy if you want to allow them to properly debug.

- For accessing MCP classes (when access to Sponge implementation classes is not needed), the plugin should use a simple ForgeGradle workspace with SpongeAPI added.

I kept this inactive because I'm not sure if this is something that should be attached as an artifact to every build without a chance to give a proper comment about it, because as already mentioned plugin authors should choose their setup based on what they need, and not add an unnecessary dependency to their plugin which may easily lock your plugin to a specific platform if not careful.

In my opinion this would be probably better explained to developers in a SpongeDocs article presenting the different options with templates they can copy and modify for their needs.

**Comment by simon816** [comment]
Adding SpongeForge/Vanilla to the workspace and making it a dependency of your plugin seems like a weird and unnecessary way to setup an environment. When creating a forge mod I don't need to pull and compile forge's sources and I shouldn't need to do that for sponge either.
It would make more sense to just have a dependency in the gradle.build that pulls a deobf spongeforge/vanilla build along with any of it's dependencies.

**Comment by Minecrell** [comment]
@simon816 Usually you're not making a **SpongeVanilla plugin** or **SpongeForge plugin/mod**, you're making a **Sponge plugin**, which should work on SpongeVanilla, SpongeForge, and any other implementation of SpongeAPI. By using one of the SDKs you directly integrate the plugin with proprietary Minecraft code instead of building only on our API, which requires extra steps for compilation and adds extra classes to the classpath which will not be available in all platforms.

Unless developers know what they're doing they should **never** see Minecraft classes from a Sponge plugin workspace, because they should be only used when necessary because that will usually lock the plugin a) to one Minecraft version and b) to MCP based Sponge implementations instead of depending only on our API.

At the same time using the SDK for testing is extremely inflexible because you fix your testing and the testing of all contributors **to one platform**, without an easy way to switch without rewriting the whole build script.

As I said, it's possible there will be ways to do testing similar to the one provided by the SDK with SpongeGradle in the future, I've simply not found the time to implement this yet.

**Comment by Mumfrey** [comment]
See, this is why you guys should actually come to the SPAMs because all this was discussed extensively and decided **weeks** ago. For the benefit of those who didn't attend, let me explain the problem and the intention of the SDK to address it:

* People are setting up full SpongeForge or SpongeVanilla workspaces in order to develop a plugin, this has a lot of drawbacks because it's
 * complicated
 * difficult for them to keep up-to-date
 * allows them to accidentally reference implementation
* For a "quick start" scenario, plugin authors shouldn't have to jump through hoops and/or write a gradle script from scratch, they should be able to download a template, edit it a bit, and go
* For testing, the gradle setup should include some kind of runServer (eg. allow testing against an implementation) so a user doesn't have to go through the bukkit plugin dev hell of constantly making jars and putting them in a production folder and running a production server

To this end, the SDK should:
* Provide a template gradle script
* Allow a chosen version of the API to be selected
* Allow a chosen implementation to be launched (not added to compile classpath, just bootstrappable)

People are still free to do their own thing right from scratch, but the SDK should represent the **simplest** workflow for people who aren't platform evangelicals and just want to make something that works in the simplest possible way.

SDK should thus become the go-to thing when people ask "how do I start".

> *"Oh, you need to set up a full workspace for X implementation"*

and

> *"Oh, you just add API as a dependency then you can compile it and copy it into an implementation mods folder and run it and then connect your debugger remotely and then do that again over and over because we have no integrated solution because we  like to make your life miserable and aren't you glad this is such a clean way of working you can't accidentally link against implementation isn't it great"*

just don't work.

We had a chat with @AbrarSyed about adding the necessary stuff to forgegradle to support this, and decided that first we need to create some kind of central JSON which maps API versions to available implementations so that gradle can set up the chosen testing environments automatically. We just didn't get around to that.

**Comment by Minecrell** [comment]
@Mumfrey That's pretty much what I had in mind actually. The current PR for the SDK update is exactly not what you described though, because it adds Forge to the compile classpath and does not allow choosing the implementation either.

**Comment by Mumfrey** [comment]
Yeah, we were pretty much unanimous on the current SDK not being much help.

**Comment by AbrarSyed** [comment]
I gotta say here that FG is designed for a single purpose. To make deobfuscated MC a compile dependency. If you don't need that, you don't need FG.

As I said in the meeting @Mumfrey referenced, o think it would be best if you guys have something like the SpongeStart plugin someone put on the forums. https://forums.spongepowered.org/t/spongestart-gradle-plugin/11318

**Comment by simon816** [comment]
As it stands there is a broken SDK currently in master: https://github.com/SpongePowered/SpongeForge/tree/1c95edad7a163593f45db699effcc1db13d3682f/sdk
We need to either 1) Remove it, or 2) Re-purpose it perhaps for forge modders looking to integrate with spongeforge

**Comment by AbrarSyed** [comment]
nuke it IMO. Forge modders know how to add a dependency, or can make a quick wiki page for that or something.
As for a way to run the things, I believe I already mentioned the SpongeStart plugin someone made...

**Comment by liach** [comment]
Should we make it in spongeapi?

**Comment by Minecrell** [comment]
Not needed for now, there are (or will be) detailed instructions on the docs how to setup a Gradle/Maven/... project for a Sponge plugin.
