### ISSUE TITLE
Command blocks issues with certain commands 

### ISSUE THREAD

**Issue by chrismack** [SpongePowered/SpongeForge#381]
Some commands ran from commands blocks don't seem to be working (see pastebin dump). I was told by @gabizou to put this here.

http://pastebin.com/VvSXmDX5

@JBYoshi

**Comment by JBYoshi** [comment]
Ah... I get it!

Here's what happens in a normal case (I'll use `/playsound` as an example):

Time | What Happens | Value of `currentError`
---- | ---------- | ----------
1 | `/playsound` begins running | `null` (inactive)
2 | `/playsound` sets `currentError` to "no error" | "no error"
3 | `/playsound` plays the sound | "no error"
4 | `/playsound` checks `currentError`. It's "no error", so nothing happens. | "no error"
5 | `/playsound` sets `currentError` to `null` (inactive) | `null` (inactive)
6 | `/playsound` finishes running | `null` (inactive)

But when one command calls another command, it blows up:

Time | What Happens | Value of `currentError`
---- | ---------- | ----------
1 | `/execute` begins running | `null` (inactive)
2 | `/execute` sets `currentError` to "no error" | "no error"
3 | `/playsound` begins running | "no error"
4 | `/playsound` sets `currentError` to "no error" | "no error"
5 | `/playsound` plays the sound | "no error"
6 | `/playsound` checks `currentError`. It's "no error", so nothing happens. | "no error"
7 | `/playsound` sets `currentError` to `null` (inactive) | `null` (inactive)
8 | `/playsound` finishes running | `null` (inactive)
9 | `/execute` checks `currentError`. It's `null`, so Sponge blows up because it thinks it can't happen. | `null` (inactive)

I'll get to work on a fix immediately.

**Comment by gabizou** [comment]
Fixed in SpongePowered/SpongeCommon@b0f261fd8dc046f91132d65814b63c964dc46621.

**Comment by gabizou** [comment]
@JBYoshi Would it be possible you could hop on IRC at some point? It would help with some communications as a contributor.
