### ISSUE TITLE
getTranslation().get() returns 'item.fish.name' for fish

### ISSUE THREAD

**Issue by Grinch** [SpongePowered/SpongeForge#418]
Title says the issue. getTranslation().get() works for leather boots when fishing but not fish.

**Comment by ST-DDT** [comment]
Could you add a code example of your event handler or something that uses your method in question? 

What exactly does not work? Exception? Value is absent?

**Comment by Zidane** [comment]
@ST-DDT 

```
stack.getType().getTranslation.get()
```

Which should return the fish's name but in Vanilla, fish are strange.

**Comment by Zidane** [comment]
@kashike can also post a code snippet.

**Comment by kashike** [comment]
@Zidane It's a bit more than Fish:
- `ItemBlock`
- `ItemCloth`
- `ItemCoal`
- `ItemColored`
- `ItemDye`
- `ItemFishFood`
- `ItemLeaves`
- `ItemMultiTexture`
- `ItemSkull`
- `ItemSlab`

All of the above require `getUnlocalizedName(ItemStack)` to be called to get the __real__ translation id.

**Comment by ST-DDT** [comment]
There is already a PR with a fix for this in Common.
https://github.com/SpongePowered/SpongeCommon/pull/155

**Comment by ST-DDT** [comment]
I found the solution.
Call it this way:
````java
stack.getTranslation().get()
````
[ItemStack#getTranslation()](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/mixin/core/item/inventory/MixinItemStack.java#L193)

**Comment by Zidane** [comment]
@ST-DDT 

Sure lol...and he fixed it on his plugin :P...still needs to print a more proper translation.

**Comment by ST-DDT** [comment]
> still needs to print a more proper translation.

Well the `ItemType` [`FISH`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/item/ItemTypes.java#L148) has no details which variant it is, so there is no way to print a more proper translation from the `ItemType`. Only the `ItemStack` can do that for you.

**Comment by ST-DDT** [comment]
@Grinch If you want to tell the user in the chat what he has caught you could just use the stack for that,
````java
player.sendMessage(Texts.of("You have caught ", stack, "!"));
````

**Comment by Zidane** [comment]
@ST-DDT 

Not sure how many times you must be told that he FIXED IT ON HIS PLUGIN. Also, I don't care that it doesn't know the fishtype...it should just say "Fish" then.

This is an issue, end of.

**Comment by ST-DDT** [comment]
@Zidane First of all, sorry for annoying you.

I outlined the solution and other ways he or any other dev with the same issue could use to solve similar problem(s) in the future. (If they are use best practices like the search function and find this issue). Because he did not explain how he had fixed it for himself. Also I too don't know how he fixed it for himself: Generics are also a solution, but none that I would recommend.

Next point the `Translation` id.

The easiest solution that is also future proof, to modify the `getTranslation()` method in `MixinItem`.

````java
private Translation translation = null;

@Override
public Translation getTranslation() {
    if (translation == null) {
        // Or do this at the end of the constructor, I don't know if this works properly that early
        translation = ((Translateable) new ItemStack(this)).getTranslation();
    }
    return translation;
}
````

or use Mixins to overwrite the `getTranslation()` method in special subtypes (ex `ItemFishFood`), but this is potentially extra work to maintain (update to new translation ids or detect new special cases)

There might be other solutions out there, but all others I could think of were highly dangerous.
(Changing getUnlocalizedName() or remapping translation ids somewhere else)

**Comment by Zidane** [comment]
He didn't fix it for himself. He adjusted his plugin to just use stack.getTranslation :P.

**Comment by Zidane** [comment]
Closing this as it is the base game that doesn't have a proper name for this unless the fish is in an ItemStack.
