### ISSUE TITLE
Server crash with VintageCraft mod

### ISSUE THREAD

**Issue by hunter688** [SpongePowered/SpongeForge#443]
When use SpongeForge together with VintageCraft mod, server does not start and crash. Without sponge server start fine.
Mod url: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2373390-vintagecraft-vintage-terraingenerator

Crashlog: http://pastebin.com/tiu632jj

**Comment by Deamon5550** [comment]
Good to know, I'll take a look at this.

**Comment by Deamon5550** [comment]
Alright after some investigation I'm pretty sure that this isn't to do with any of our world generation changes. Might possibly be to do with the changes we make to the nether world to make it a world in its own right.

**Comment by simon816** [comment]
OK I fixed "part 1" of this issue which was the original issue, but since the recent world gen changes it broke in another place.
It seems that `ChunkProviderGenerateVC.provideChunk(int, int)` is not getting called. I think the generator is never initialized. I think this is because sponge overwrites a call to `WorldProvider.createChunkGenerator` but I couldn't fix it without breaking everything so I'll let @Deamon5550 take a look if you don't mind :)

**Comment by hunter688** [comment]
Tested with build 950:

http://pastebin.com/XXCcfJJy

**Comment by hunter688** [comment]
with updated vintagecraft mod 0.8.100 and sponge build 978:

http://pastebin.com/c75bNyyz

**Comment by tyronx** [comment]
Looking at that crash log I would confirm your theory @simon816 

ChunkProviderVC.provideChunk() ist not getting called, but WorldGenDeposits.generate() is, which however relies on some nbt data to be initialized by ChunkProviderVC.provideChunk() 

I'm the creator of vinatecraft, so let me know if i can assist. You can also ready the source code freely at https://github.com/tyronx/vintagecraft

**Comment by Deamon5550** [comment]
Ahhh I think I know what the issue is, replacing the chunk provider shouldn't be an issue, but I think because its extending ChunkProviderGenerate which at runtime implements GenerationPopulator I'm assuming that I can use it like a genpop rather than a chunk provider. Blocking that should cause your provideChunk method to be called.

**Comment by Mumfrey** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  adam@eq2.serveftp.net
    Domain eq2.co.uk has exceeded the max emails per hour (73/60 (121%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:22137)
	by web3.cov.yesit.co.uk with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86)
	(envelope-from <bounces+848413-d0b0-adam=eq2.co.uk@sgmail.github.com>)
	id 1aGINY-000CN5-Bn
	for adam@eq2.co.uk; Tue, 05 Jan 2016 03:33:48 +0000
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=sLFxqLBQT/Ehi3jcgPRGNa5ZPB8=; b=REwY6BMeF5Z3ssXQ
	m2jBytLfvKCqnoiNza7EZjlMcQLGORDFIYPBPjZKCqXDBS2op3LuiRZelrAxLt/z
	IeK8341Fq3JLd0Dh5IByqXfKZYas2WQxNWE6qmztAX4YmHCMrCZTuCKhzJGvPPEf
	LDONx9098nPttZ5vS/EFfjb/Wvs=
Received: by filter0562p1mdw1.sendgrid.net with SMTP id filter0562p1mdw1.14693.568B396C2F
        2016-01-05 03:33:00.516739563 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id 2G3Iw4LqQamp5Y9PmDx2pQ
	for <adam@eq2.co.uk>; Tue, 05 Jan 2016 03:33:00.625 +0000 (UTC)
Date: Mon, 04 Jan 2016 19:33:00 -0800
