### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by RafaelPL** [SpongePowered/SpongeForge#465]
spongeforge-1.8-1577-2.1-DEV-967

Crash when server is starting.
http://pastebin.com/H4XpVbwZ

**Comment by Aaron1011** [comment]
@RafaelPL: This is a bug in the version of the `JRE` you're using. You'll need to upgrade to `1.8.0_66` or higher to run Sponge.

**Comment by ryantheleach** [comment]
Can we catch this in java8 code to give a friendlier message?

**Comment by Aaron1011** [comment]
@ryantheleach: I thought about doing this, however, I wasn't aware of the exact JRE build which fixed this issue. The java8 checker is mainly targeted at people running an older major version (1.6 or 1.7). Since they would presumably upgrade to the latest version, I didn't want to unnecessarily force other people to upgrade who might not be on the *very latest* build.

**Comment by mcsnetworks** [comment]
@Zidane can't we hard check the version of local JRE installed and stop the server if a required build or higher isn't found?

**Comment by Zidane** [comment]
@mcsnetworks 

Right we can. @gabizou what was the JRE build again? I'll have @Aaron1011 check for it in the tweaker.

**Comment by gabizou** [comment]
The minimum required JRE is 1.8u40, the `CopyOnWriteArrayList` had a change with it's streaming utils that I use in the `SpongeDataManager`.

**Comment by Minecrell** [comment]
Should be fixed in https://github.com/SpongePowered/SpongeCommon/commit/658554e150456b34a6a48f303d790be460c35950
