### ISSUE TITLE
Overriding Vanilla Commands

### ISSUE THREAD

**Issue by mrgoodrich** [SpongePowered/SpongeForge#469]
My commands overriding vanilla commands were working a few months ago (for example "/time"), however they are now not working.  I have verified my other commands are being registered correctly.  Here's how I'm registering them for good measures:

    cmdManager.register(this, timeCommand, "time");

Let me know if there's anything else I can do at this point.  I know the command manager is valid at that point.

**Comment by Zidane** [comment]
@mrgoodrich 

When are you registering them? Show us a listener with the line above.

**Comment by mrgoodrich** [comment]
@Listener
	public void onServerStarting(GameStartedServerEvent event) {

**Comment by JBYoshi** [comment]
@mrgoodrich Try registering it earlier, e.g. `GameInitializationEvent`. (Also, note that the client can start and stop the server multiple times, so if you register it in one of the server startup events, it can be registered multiple times.)

**Comment by Aaron1011** [comment]
@mrgoodrich: As far as I can tell, this is the intentional behavior for commands. 

Vanilla commands are all registered at `GameStartedServerEvent`. When this happens, the normal behavior of `CommandManager`/`CommandDispatcher` kicks in. The disambiguator is used to determine which command to pick for the specified alias.

Unfortunately, the only way to customize this at the moment seems to be to use the `commands` section of the Sponge global config. The `commands` node should contain a mapping from command aliases to plugin ids.

I'm not sure if it's @zml2008's intention to allow setting the `Disambiguator` for the `CommandManager` or not. He'd be the one to talk with further about this.

**Comment by mrgoodrich** [comment]
@Aaron1011 Could you expand on how to use the command config method?  There are no comments in the config and I don't think I understand what you're saying.  An example maybe?  Also, would it be possible to register the events in something earlier than the ```GameStartedServerEvent```, so they have priority over the vanilla commands?

**Comment by mrgoodrich** [comment]
@JBYoshi Sorry I missed your message!  You were right, thanks a million :heart:

**Comment by MarkTwoFive** [comment]
Has anything regarding this changed so far? I guess plugin commands taking lower priority than vanilla commands is somewhat counter-intuitive...

**Comment by ryantheleach** [comment]
@MarkL4YG unless a bug or intentional change has changed the behaviour then whoever registers first, wins.

If you register plugin commands before vanilla does, then your plugin will have priority, if registered after, the user will have to manually override the clash in the configuration file.

Did you have anything specific to add? Have your experiences been different to what I just described? Or was this behaviour just surprising to you?

**Comment by MarkTwoFive** [comment]
I register my commands at ``onGameInitialization`` when my Managers are initialized. However Vanilla commands still take priority over them.  

And yes, this behavior does sound counter-intuitive to me. I get why the priority is a race condition between plugins and mods but if I add a plugin to extend vanilla behavior - why would I choose the vanilla command/behavior over the plugin command ___by default___.

**Comment by ryantheleach** [comment]
It's possible something has changed since this issue was first created then, I suggest making a new issue, with versions tested, and expected behaviour detailed, and if this is a recent occurrence, document the last version tested where this behaviour was not observed.

**Comment by MarkTwoFive** [comment]
I guess I'll do that if this behavior continues past API 5.
