### ISSUE TITLE
Restructured-1.8.9-1.1.0.1ALPHA - Server crash

### ISSUE THREAD

**Issue by cauliflower69** [SpongePowered/SpongeForge#498]
http://pastebin.com/6gJkV5Qs

**Comment by gabizou** [comment]
The stack trace is pointing to Schematica crashing, not SpongeForge.

**Comment by cauliflower69** [comment]
This is very strange as it works fine with no sponge. That's why I posted the crash here

**Comment by simon816** [comment]
```
Caused by: java.lang.NullPointerException
    at net.minecraft.world.World.getWeather(World.java:1766)
    at net.minecraft.world.World.onConstructed(World.java:324)
    at net.minecraft.world.World.<init>(World.java:125)
    at org.blockartistry.mod.Restructured.world.FantasyIsland.<init>(FantasyIsland.java:55)
    at org.blockartistry.mod.Restructured.world.FantasyIsland.<clinit>(FantasyIsland.java:52)
    ... 41 more
```
`onConstructed` and `getWeather` are methods in our [`MixinWorld`](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/mixin/core/world/MixinWorld.java) so Sponge does have something to do with this.

It looks like this is passing null into the constructor https://github.com/OreCruncher/Restructured/blob/master/src/main/java/org/blockartistry/mod/Restructured/world/FantasyIsland.java#L55

**Comment by gabizou** [comment]
Good catch @simon816, for some reason, I didn't quite read that last important bit of the stack trace.

**Comment by simon816** [comment]
I've fixed the actual crash by moving some initialization things from the world constructor to `init()` so that only worlds that are actually going to be loaded will be initialized with sponge settings. A fake world like Restructured's `FantasyIsland` will no longer cause problems.
I also set the `WorldInfo` to a non-null value and include an error message to say a mod is creating a world without WorldInfo.
Commit: https://github.com/SpongePowered/SpongeCommon/commit/681bd6c93c1e32295023ecb60ac4a0e369dae40e

@SpongePowered/developers if this seems alright I'll push it to master. One thing that I'd also like to do at some point is to only initialize a `WorldInfo` config when the world properties are actually called. This will stop a config getting generated for a fake world.

**Comment by Aaron1011** [comment]
@simon816: Was this fixed?

**Comment by simon816** [comment]
Commit not in master so not yet

**Comment by bloodmc** [comment]
@simon816 please get the fix into master so this issue can be closed.
