### ISSUE TITLE
Can't run setupDecompWorkspace

### ISSUE THREAD

**Issue by CodingMonkeyXYZ** [SpongePowered/SpongeForge#516]
I'm following the instructions in the documentation to set up my clone of the SpongeForge project, so that I can debug my plugin but When I try running

    gradle setupDecompWorkspace --refresh-dependencies

I get loads of missing dependencies.

Gradle is installed on the Windows command line ok, I can run it with just 'gradle'. Am I missing something?

**Comment by ST-DDT** [comment]
Have you downloaded/updated SpongeCommon (the folder should be located inside SpongeForge) and SpongeAPI (the folder should be located inside SpongeCommon).

Are there any error messages showing up?

**Comment by CodingMonkeyXYZ** [comment]
The SpongeCommon folder is there. Earlier, I did:
    git clone --recursive https://github.com/SpongePowered/SpongeForge.git
    cd SpongeForge
    cp scripts/pre-commit .git/hooks
    git pull
    git submodule update --recursive

Are there any steps I'm missing?

**Comment by Deamon5550** [comment]
Try it with the gradle-wrapper (`gradlew setupDecompWorkspace --refresh-dependencies`) just to be sure its not an issue based on the version of gradle that you installed.

**Comment by CodingMonkeyXYZ** [comment]
Tried that, it isn't. I've narrowed the problem down to a very slow-downloading 5MB eclipse library at this address: https://repo.eclipse.org/content/repositories/eclipse-staging/org/eclipse/jdt/org.eclipse.jdt.core/3.12.0.v20150913-1717/org.eclipse.jdt.core-3.12.0.v20150913-1717.jar

No idea why this project needs it but it's killing my build because of network issues. I suspect because there is a lot of demand in their servers. It would be a good idea to cache this if we need it - ideally somewhere that isn't getting absolutely hammered by requests.

**Comment by JBYoshi** [comment]
> https://repo.eclipse.org/content/repositories/eclipse-staging/org/eclipse/jdt/org.eclipse.jdt.core/3.12.0.v20150913-1717/org.eclipse.jdt.core-3.12.0.v20150913-1717.jar

That would be... the Java module of Eclipse? Probably explains why it's so big.

I checked, and it's not in SpongeForge's build path, or on `build.gradle`'s build path.

**Comment by kenzierocks** [comment]
You'll want to check `gradle dependencies` if you want to know where it
comes from.

**Comment by bloodmc** [comment]
This is not a bug in SpongeForge. If you have any more issues, create a post on our forums.

**Comment by CodingMonkeyXYZ** [comment]
> This is not a bug in SpongeForge.

I never said it was, I simply reported an issue.

It's more of a 'performance' issue with the build script but since It has potential to prevent people from getting started using your project by causing the script to fail (and turn them off it), I think it qualifies as 'an issue'.

> If you have any more issues, create a post on our forums.

No see, if I wasn't sure if it was an issue, I'd go there. I was sure it's an issue, so I went here (the place to report issues).

Do what you like with it but I just thought you guys should know - in the spirit of community and open source and all that stuff.

**Comment by Mumfrey** [comment]
This seems like a problem with your setup though, potentially your ISP has a crappy peering arrangement to the repo, or some firewall/parental control/security software on your computer is affecting the connection, but this isn't a problem with the project it's a problem specifically with your computer fetching dependencies from a remote repository. Since this issue tracker is for things which need to be fixed, not people who need support, what blood is saying is that this issue shouldnt be here it should be on the forums.

> No see, if I wasn't sure if it was an issue, I'd go there. I was sure it's an issue, so I went here (the place to report issues).

This is an issue at your end though, and so the forums are a more appropriate venue for support.

> Do what you like with it but I just thought you guys should know - in the spirit of community and open source and all that stuff.

We can help you but you need to provide more details about your setup, net connection etc.

> It's more of a 'performance' issue with the build script but since It has potential to prevent people from getting started using your project by causing the script to fail (and turn them off it), I think it qualifies as 'an issue'.

It's not an issue with the build script per se. All the build script does is specify a bunch of dependencies and sources to obtain them from. All the sources are large, well-peered, multiply-redundant repositories used by a vast number of projects worldwide. If you find that a particular repo is slow for you then you can specify your own alternatives. For example I like to add my own local `.m2` repository so that anything in my local maven cache can be used instead of downloading it: [example init.gradle file](https://gist.github.com/Mumfrey/632f37a405d93075d7e7).

> It would be a good idea to cache this if we need it - ideally somewhere that isn't getting absolutely hammered by requests.

Once you've successfully downloaded it once, it **is** cached in your local gradle cache. This means if you can successfully download it once then it'll be there for subsequent builds. This works the same as ivy/maven.

> No idea why this project needs it

JDT is used by Srg2Source which is used during the reobfuscation phase.

How you should proceed:

* Attempt to identify any network issues/software firewall/parental control software which may be throttling connections to maven repositories.
* Specify alternate repos in your `init.gradle` if you find a maven repository which performs well on your ISP and has the JDT/equinox libraries
* If you still experience problems then ask on the forums as they are where support requests like this should be handled, this issue tracker is reserved for bugs in SpongeForge
