### ISSUE TITLE
Ticking entity exception with SpongeForge and The BigTrees Mod

### ISSUE THREAD

**Issue by klangg** [SpongePowered/SpongeForge#531]
Build number: 1147
Forge version: 1732

Crash report/Log files: https://gist.github.com/klangg/fb855a7e28f19ca7d27c

Description:

On world creation the Minecraft server crashes a few seconds after the world finishes loading. This does not happen every time only on some seeds. If a seed crashes it will happen every time a world is created with that seed. Running the server again after the crash the world stays loaded with no issues. Removing either Sponge or BigTrees results in no crash. I was not able to duplicate this using the Recommended Sponge build 1046 with Forge 1691 and the same version of BigTrees.

I'm glad to provide any other info needed or run additional tests.

**Comment by gabizou** [comment]
There's already an issue for @SpongePowered/SpongeCommon#497.

**Comment by klangg** [comment]
Thanks! I didn't think to look there. Is there an easy way to tell if a crash is related to SpongeForge or SpongeCommon?

**Comment by gabizou** [comment]
One way is if you know how to read the stack trace and figure out which mixin the calls are originating from (namely MixinWorld in SpongeCommon), then that'd be the place to report the bug with. Otherwise, usually if you can reproduce the same exact issue in SpongeVanilla, then it also is a bug in SpongeCommon.
