### ISSUE TITLE
Chat Event Error

### ISSUE THREAD

**Issue by seanamor** [SpongePowered/SpongeForge#583]
Minecraft: 1.8.9
SpongeAPI: 4.1.0-SNAPSHOT-dd7e8e2
SpongeForge: DEV
Minecraft Forge: 11.15.1.1764

http://hastebin.com/pufoluroji.avrasm

**Comment by windy1** [comment]
Either you aren't on 4.1.0 like you say you are or you are building your plugin incorrectly because this is the result of an outdated API.

`java.lang.NoSuchMethodError: org.spongepowered.api.event.message.MessageChannelEvent$Chat.getMessage()Ljava/util/Optional;`

This method no longer returns an `Optional` but rather a `Text` object.
