### ISSUE TITLE
No thunder/lightning storms 

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeForge#586]
Spongeforge 1227 (and earlier versions)

Weather can be changed by command to sunny/rain/thunder but no lightning/thunder is generated during the storm - have surveyed various biomes out, kept changing weather to storm mode, no success.  Forge with spongemod disabled= thunderstorms work fine.

Nor does summoned LightningBolt trigger a spawnentity event

**Comment by modwizcode** [comment]
I'll investigate.

**Comment by modwizcode** [comment]
With respect to the lack of any lightning during a storm  the cause was not easy to find, but the fix was a single character, the code in SpongeCommon checked for a canceled `ConstructEntityEvent.Pre` rather than a non-canceled one.

As for the non-fired `SpawnEntityEvent`, weather effects are handled slightly differently from standard entities, in this case, before Minecraft creates the lightning bolt entity **during a storm** a `ConstructEntityEvent.Pre` is fired with a `WeatherSpawnCause` as it's source wrapping the type of weather that caused it.

When the summon command is used, minecraft simply adds the lightning bolt entity straight to the list of weather effects attached to a world, which Sponge does not capture in a mixin to create a spawn event. Since this isn't really spawning I'm questioning on whether or not it's needed or even proper to post a spawning event. 

Additionally, more data is provided in the `LightningEvent`, which is used instead for the same purpose as `EntitySpawnEvent` except specifically handling the unique facts about lightning and it's sort of spawn.

@SpongePowered/developers thoughts on firing `EntitySpawnEvent` for adding lightning? My opinion is not to add as `LightningEvent` covers the use case.

As for the first part, I'll post a patch shortly.

**Comment by theboomer** [comment]
Not being in the spawn event for a summon makes sense ..sorta.. from a non-necessary point of view, if it throws a specific event in exchange, as well as the construction event.

I had issues with the construction events not being triggered the last time I was trying to play with them a week or so ago and figured it was one of the nonimplimented things, so I didn't test it.

Thank you for addressing the native lightning-block issue.  Surprising no one noticed before now...

**Comment by modwizcode** [comment]
Indeed it is, it was a tricky problem to track down though.
