### ISSUE TITLE
Eye of ender not working with bop and sponge

### ISSUE THREAD

**Issue by mblob** [SpongePowered/SpongeForge#606]
[https://github.com/Glitchfiend/BiomesOPlenty/issues/739](https://github.com/Glitchfiend/BiomesOPlenty/issues/739)

Can't throw any eye of ender. Only happening when level-type set to BIOMESOP
Steps to reproduce:

    Set level-type to BIOMESOP in server.properties
    Delete world/*
    Start server

Additional Information:

[fml-server-latest.log.txt](https://github.com/SpongePowered/SpongeForge/files/211210/fml-server-latest.log.txt)

  Biomes O' Plenty BiomesOPlenty-1.8.9-3.0.0.2001

    Minecraft: 1.8.9
    SpongeAPI: 4.1.0-SNAPSHOT-44b5f5e
    SpongeForge: 1.8.9-1808-4.1.0-BETA-1254
    Minecraft Forge: 11.15.1.1808

**Comment by Aaron1011** [comment]
@Deamon5550: This appears to be a word-gen related issue, as `worldIn.getStrongholdPos("Stronghold", new BlockPos(playerIn))` in `ItemEnderEye` is returning `null`.

**Comment by simon816** [comment]
If that's returning `null` then [`SpongeChunkProvider#getStrongholdGen`](https://github.com/SpongePowered/SpongeCommon/blob/ce903298ff8293513495c865509e2af5b0fc1239/src/main/java/org/spongepowered/common/world/gen/SpongeChunkProvider.java#L337-L346) is returning null.

Which means the `genpop` list doesn't contain a `MapGenStronghold`
By looking at where the [genpop list is set](https://github.com/SpongePowered/SpongeCommon/blob/b0eb94e7d7c3bd0f3eea42b5662c8f0942dec99e/src/main/java/org/spongepowered/common/mixin/core/world/MixinWorld.java#L555), it gets the list  from `SpongeWorldGenerator#getGenerationPopulators`. This list is originally empty, and gets populated when [`IPopulatorProvider#addPopulator`](https://github.com/SpongePowered/SpongeCommon/blob/ce903298ff8293513495c865509e2af5b0fc1239/src/main/java/org/spongepowered/common/mixin/core/world/gen/MixinChunkProviderGenerate.java#L113-L187) is called. 
In BOP, they have a [`ChunkProviderGenerateBOP`](https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.9-4.0.x/src/main/java/biomesoplenty/common/world/ChunkProviderGenerateBOP.java) which does not extend vanilla classes therefore doesn't implement `IPopulatorProvider`, this is where the problem lies.
IMO Sponge must be able to work with mods that don't extend the vanilla generators.

**Comment by Deamon5550** [comment]
short of doing static code analysis to guess which stronghold generator it is in modded chunk generators theres fuck all we can do. Sponge does work with mods that don't extend vanilla generators as far as the actual generation goes this is just a strange case of something trying to reference the generator.

**Comment by gabizou** [comment]
@Addubz is probably the person you'd want to prod about gen structures with BoP.

**Comment by simon816** [comment]
It should be possible for sponge to handle generators that don't extend vanilla classes, perhaps with reduced SpongeAPI compatibility/interoperability but still allow modded dimensions and generators to work as intended.

**Comment by Deamon5550** [comment]
@simon816 
>Sponge does work with mods that don't extend vanilla generators as far as the actual generation goes this is just a strange case of something trying to reference the generator.
