### ISSUE TITLE
SpongeForge Core Mod support?

### ISSUE THREAD

**Issue by CreativeMD** [SpongePowered/SpongeForge#649]
Hello,
lately i got an issue report about SpongeForge (https://github.com/CreativeMD/ItemPhysic/issues/19). My mod ItemPhysic can't be used on a SpongeForge Server due to some ASM Transformer crashes.

So my question is, is there a way to fix an issue like that? I'm sure that this is a lot more difficult because those files don't exits like in forge, so my transformation end up ruining everything.

In Regards
CreativeMD

**Comment by simon816** [comment]
There are a few things that I have spotted that are potential issues.
You are accessing a logger field on the mod container [here](https://github.com/CreativeMD/ItemPhysic/blob/1.8.9/src/main/java/com/creativemd/itemphysic/ItemTransformer.java#L65) (and in other places)  which in turn will load the mod container whilst transforming another class, and on the wrong classloader.
Try putting the logger in a separate class.
Also your `IFMLLoadingPlugin` is loading the mod container class ahead of time (see [here](https://github.com/CreativeMD/ItemPhysic/blob/1.8.9/src/main/java/com/creativemd/itemphysic/ItemPatchingLoader.java#L22)).
The method returns a string because you're supposed to return a literal string reference to the class.

**Comment by Zidane** [comment]
Closing this as its an issue on ItemPhysic's end.
