### ISSUE TITLE
[1.9.4] Exception in server tick loop

### ISSUE THREAD

**Issue by LuxusDarkangel** [SpongePowered/SpongeForge#667]
Crash-Report: http://pastebin.com/m5d8vQn9
SpongeForge version: 5.0.0-BETA-1406

Using EnderIO and EnderCore.

**Comment by Deamon5550** [comment]
This issue is already known and is pending a fix by the EnderCore developers. See [SleepyTrousers/EnderCore#37](https://github.com/SleepyTrousers/EnderCore/pull/37) and related issue #610.

**Comment by Zidane** [comment]
@LuxusDarkangel 

This is because EnderCore is classloading several events and other game objects during their transformer:

https://github.com/SleepyTrousers/EnderCore/blob/master/src/main/java/com/enderio/core/common/transform/EnderCoreTransformer.java#L253

This line invokes a Logger field from EnderCore which cascades into loading the classes in EnderCore's class file. You need to tell the developers of EnderCore to not classload this.

**Comment by LuxusDarkangel** [comment]
Whooops, sorry for the duplicated report.

**Comment by Aaron1011** [comment]
I have an open PR for that issue: https://github.com/SleepyTrousers/EnderCore/pull/37
