### ISSUE TITLE
[1.9.4] Loosen restrictions for flight with motion limits

### ISSUE THREAD

**Issue by LuxusDarkangel** [SpongePowered/SpongeForge#688]
When you're flying on a spigot or vanilla server and it's a bit overloaded, you may experience some block lag (if you stop to break blocks) or the world loading slower, but it's nothing too bad. While using Sponge, if it lags even just a bit, will spam the console with "moved wrongly" and teleport you back ALL THE TIME, which is a terribly unsatisfactory feel.

**Comment by Zidane** [comment]
@LuxusDarkangel 

This does happen on a Vanilla server. Its basically because the moved too quickly check is wayyy to harsh and pulls you back. Spigot patches it to be forgiving, we need to do the same. If you can generate a timings report, we can make sure nothing is getting encumbered from our code.

Also, your plugins and mods installed will heavily affect this.

**Comment by LuxusDarkangel** [comment]
I'm running the server with very low resources because it's a test server, i'm not blaming sponge for performance, but yeah, patching it to be forgiving is the best.

**Comment by Zidane** [comment]
Reopen this in Common please.
