### ISSUE TITLE
[1.8.9] Thaumcraft selecting focus on wand not work behind BungeeCord

### ISSUE THREAD

**Issue by hunter688** [SpongePowered/SpongeForge#731]
Tested with pure forge server - no problems. When add spongeforge (no another plugins) then cannot change focuses on the Thaumcraft wand wand. Looks like spongeforge break clicking in the selecting gui.

Steps to reproduce:
 - give to inventory some focuses and wand.
- hold wand
- press F
- then try to click focus

expected result is change focus to clicked.

SF(build 1538)

**Comment by LuxusDarkangel** [comment]
Probably an issue with packets, as happened with BungeeCord. Please, post your server log.

**Comment by gabizou** [comment]
I've got a fairly decent idea as to what's going on and how to handle it for 1.10.2+. @bloodmc basically, when a foreign packet is received, we should be checking the content changes for the player's inventories and throwing events accordingly. In this case, Thaumcraft is changing the itemstack in the player's main hand and modifying the tag.

**Comment by ryantheleach** [comment]
But couldn't that foreign packet be doing a number of different things? Won't some foreign packets get spammed a *lot*?

**Comment by gabizou** [comment]
Yes, @ryantheleach but without being able to tell when something happens, since itemstacks are interacted with directly, i's not really well possible unless we basically flag to capture anything that does change during the packet being handled.

**Comment by hunter688** [comment]
In the server is no exceptions, errors etc. Yes its behind bungeecord.

**Comment by hunter688** [comment]
Yay, without bungeecord it works. Im using SpongePls plugin for forwarding in the BungeeCord. In the logs of sponge and bungee see no errors or exceptions.

**Comment by SilverCory** [comment]
This is probably something to contact the thaumcraft author about. I've no clue of it's protocol or how it works, so the chances of me fixing this are slim.

**Comment by LuxusDarkangel** [comment]
The issue is with BungeeCord, not SpongeForge nor SpongePls. See [this](https://github.com/SpigotMC/BungeeCord/issues/1439) for reference.

**Comment by bloodmc** [comment]
@dualspiral Can you look into this with your BungeeCord fork?

**Comment by dualspiral** [comment]
@bloodmc When I get chance I'll take a look - though @hunter688, have you tried this using [Waterfall](https://ci.aquifermc.org/job/Waterfall/) instead of Bungee yet?

**Comment by Zidane** [comment]
Closing this but discussion can continue as it is not a Sponge issue and is a bungee issue.

**Comment by hunter688** [comment]
Found source of problem. Lobby server is 1.10.2 with protocolsupport plugin. When connect through this server, got issue. When remove protocolsupport and join to modded server as fallback, all is ok.

**Comment by thomas15v** [comment]
Took me a while to figure out this issue. But the problem isn't bungeecord nor thaumcraft. The problem lies in the minecraft protocol and the challenge bungeecord brings. 

When a player join a server on bungeecord, it gets asigned a entity id on that specific server. However when the client switches to another server the client id on the new server will be different. Bungee itself counteracts this problem by rewriting all know packets and changing their id's. 

However thaumcraft is one of those mods that uses the entity id of the player for some of it's packets. What causes everything to go haywire when a player switches servers. As a proof of concept I also fixed the problem in the form of a bungeecord plugin: https://github.com/densitycraft/ForgePacketFix

**Comment by hunter688** [comment]
Hey Thanks a lot!

**Comment by hunter688** [comment]
Looks like it does not work for me. :(

Latest Waterfall, ForgePacketFix, lobby server with 1.10 and latest protocolsupport, latesst 1.8.9 sponge with thaumcraft. Still cannot change focuses.

**Comment by thomas15v** [comment]
Yeah I tested this for 1.7.10. I guess the packet id's for the new thaumcraft are different. Ill add the id's for 1.8.9 tho. See: https://github.com/densitycraft/ForgePacketFix/issues/1.

**Comment by hunter688** [comment]
Great!

**Comment by RhythmNz** [comment]
@thomas15v https://github.com/densitycraft/ForgePacketFix/ is 404 
Do you have a file?

**Comment by thomas15v** [comment]
@RhythmNz I removed that repo with the densitycraft group. Also I am not re-uploading that repo since it is not the correct way to fix it, see: https://github.com/MinecraftForge/MinecraftForge/issues/3284. 

By modifying bungeecord to send the correct packet on server switch, you can easily fix the problem. However I am pretty sure that change will never get pulled in the original bungeecord since it breaks the team api inside bungee. Wich is also the reason why I never send a PR.

**Comment by ghost** [comment]
Try this: https://www.rebelgames.net/ForgePacketFix-1.0.1.jar

**Comment by RhythmNz** [comment]
@thomas15v You mean I can write a plugin to fix?
I will try it thanks

**Comment by thomas15v** [comment]
@RhythmNz Ehm no. You have to path your bungee in order to support it. This is the path I applied on my server: https://gist.github.com/thomas15v/3768613bce327caa2f46b319eadea615.

**Comment by RhythmNz** [comment]
@thomas15v Do you have the finished version of the Jar. For 1.7.10
I still don't learn how to use Git

**Comment by RhythmNz** [comment]
@thomas15v Do you have the finished version of the Jar. For 1.7.10
I still don't learn how to use Git
