### ISSUE TITLE
[1.10.02] Chickens not laying eggs

### ISSUE THREAD

**Issue by dakattack** [SpongePowered/SpongeForge#774]
On the latest version and previous versions of sponge, the sounds of a chicken laying an egg is played, however no egg spawns.  Only other mod is biomes o plenty and the server is in survival mode.

**Comment by Aaron1011** [comment]
@gabizou: This is an issue with the CauseTracker. When item premerging is enabled, a chicken laying an egg causes an itemstack to be added to `PhaseContext#getCapturedItemStackSupplier()`. However, that supplier is only checked in the `CLOSE_WINDOW`, `USE_ENTITY`, and `UNKNOWN_PACKET` `PacketFunctions`. So, since `EntityTickPhaseState#processPostTick` ignores those `ItemStack` captures, the item never gets spawned into the world.

**Comment by FiveEYZ** [comment]
using build 1623 and can now see eggs laying around again

**Comment by dakattack** [comment]
fixed in [9f85a52](https://github.com/SpongePowered/SpongeForge/commit/9f85a521315762fe5444f5932079c31ec3429ffe)
