### ISSUE TITLE
Incompatability with LycanitesMobs

### ISSUE THREAD

**Issue by SaibaX** [SpongePowered/SpongeForge#809]
For some reason when loading LycanitesMobs and SpongeForge together this happens. http://pastebin.com/E7jrnfc1

It prevents anything from this mod from being spawned into the world by any means.

http://lycanitesmobs.com/

**Comment by SaibaX** [comment]
https://github.com/Lycanite/LycanitesMobs/blob/master/java/lycanite/lycanitesmobs/junglemobs/entity/EntityUvaraptor.java#L55

Lycanite asked that I send this to you. Not sure why but he thought it may be useful.

**Comment by gabizou** [comment]
@Aaron1011 some small investigating for you, the AI tasks are being added while the entity was spawned on a `WorldClient`.

@Lycanite You should really consider overriding the appropriate method: `protected void initEntityAI()` to add ai tasks instead of performing that on the constructor. Reason being is that AI tasks should likely never be performed on the client world, only on the server world. This is partially why Sponge is crashing the client when one of your mobs is trying to spawn, because on `WorldClient`, `initEntityAI` is never called, so for our ai systems, the `owner` is still `null`.

**Comment by Zidane** [comment]
I'm closing this issue as no one should EVER add their tasks to the client-side and the crash is completely valid.

**Comment by Lycanite** [comment]
Oooh, that explains a few problems! Lol! I completely forgot about initEntityAI(), is that new with 1.8+?
