### ISSUE TITLE
labyrinth + SpongeForge Server crash

### ISSUE THREAD

**Issue by knoxhack** [SpongePowered/SpongeForge#890]
https://gist.github.com/knoxhack/90370893525af2bc53eed8ef0e80dd4b

**Comment by knoxhack** [comment]
https://github.com/abecderic/labyrinth/issues/1

**Comment by abecderic** [comment]
SpongeForge devs: call the server lifecycle events properly, especially call `FMLServerStartingEvent` before any world gen happens

**Comment by Aaron1011** [comment]
@abecderic: I'm not sure what you mean. `FMLServerStartingEvent` is always fired after world gen happens (both with and without Sponge installed.)

**Comment by Deamon5550** [comment]
@abecderic Perhaps you are wanting FMLServerAboutToStartEvent instead ([for ref](https://github.com/MinecraftForge/MinecraftForge/blob/5eeda7923471cd6fe3ce168ab1d1671094e62c7c/patches/minecraft/net/minecraft/server/dedicated/DedicatedServer.java.patch#L40-L49))

**Comment by abecderic** [comment]
@Aaron1011 You are right with world gen when it comes to the overworld. The loading of a dimension does not trigger any world gen when you don't have Sponge installed but it does if you do have Sponge installed. Then comes preparing of start region / spawn area. This only happens for the overworld when you don't have Sponge installed; Sponge however makes Minecraft prepare a spawn area for every dimension.

@Deamon5550 When `FMLServerAboutToStartEvent` is fired I can't get the world data needed since the world isn't loaded yet.

Since (obviously) the world has to be loaded before world gen, I changed my world gen code to load the world data if it isn't loaded yet.

So this is fixed on my side and can be closed.
