### ISSUE TITLE
level.dat zero size when server power loss

### ISSUE THREAD

**Issue by hunter688** [SpongePowered/SpongeForge#896]
On the same server hardware is running spongeforge, cauldrons, spigots. When server sometimes loss power, in the world directory files level.dat (sponge_level.dat) have zero size and must overwrite from backups. Spigots, Cauldrons world directories are fine and have no problems.

I think sponge have these files still open, not only when need. Will be possible handle with these files similar way like bukkit/spigot/cauldron ?

**Comment by Deamon5550** [comment]
If we're not already we could also me more robust and write to a temp file before copying it over the original.

**Comment by Dockter** [comment]
Spigot and Cauldron's world directories are NOT fine in the example given.  

Here's the problem with this;

If a server is running and loses power, tons of things are not necessarily written to the disk, this includes but is not limited to server world files, server player files, dynmap files etc.  I have even seen plugins become corrupt.

I would hope that anyone runnign a server is smart enough to use a good UPS.

I've ran a server for almost 5 years on craftbukkit, craftbukkit++, spigot, cauldron etc etc.  I've seen world corruption on all of these servers in the event of a server failure whether its a JVM crash, motherboard / hardware failure or power loss due to UPS failure.

**Comment by ghost** [comment]
It is silly to buy a UPS because three files in one directory after power loss have zero size. Other tons of files are fine. The problem is that those files are always open for writing.

**Comment by NyleGarcia** [comment]
This may not even be a sponge issue it's possible just a data loss issue and I wouldn't recommend and server to be hard rebooted /unplugged for it can cause more damage. Also preform backups

**Comment by ghost** [comment]
Setting auto-player-save-interval and auto-save-interval to higher values solves my issue.
