### ISSUE TITLE
Lag when placing Redstone on top of Redstone Clock (ExtraUtils)

### ISSUE THREAD

**Issue by dogboy21** [SpongePowered/SpongeForge#941]
When redstone is placed on top of a ExtraUtils redstone clock the server begins to lag pretty bad. When redstone is placed on the 4 sides, it works as expected.

ExtraUtils 1.10.2-alpha-1.0.1
Sponge 1.10.2-2092-5.0.0-BETA-1756
Forge 12.18.1.2092

**Steps to reproduce:**

- Place down ExtraUtils Redstone Clock

- Place Redstone on top of it (=lag)

- Place Redstone on the sides (=no lag)

Timings: https://timings.aikar.co/v2/?id=e890449656ae4c23961cc47bbf8cf20e
Warmroast: Warmroast instantly dies with a StackOverflow when the redstone is placed down

**Comment by Aaron1011** [comment]
This is caused by us capturing block snapshots during scheduled block updates. The mod redstone clock block is implemented by repeatedly scheduling updates for itself. When its `updateTick` method sets itself to either powered or unpowered, it expects neighbor notification to happen instantly (it sets a flag to avoid running certain logic if it receives any transitive neighbor notifications from attached wire). However, because the notification logic gets delayed due to capturing, the block is unable to function correctly.

**Comment by gabizou** [comment]
@Aaron1011 @Zidane @bloodmc Here's what I'm thinking, in this circumstance, it does suit to make it configurable for specific blocks to enable bypassing the tracker for block capturing to only throw instant block change events as they happen while a certain block tick takes place. Why this would make sense is that ultimately, there are going to be some blocks that do require customary bypasses such as this one to avoid issues later on.
