### ISSUE TITLE
[1.10.2] Range cannot have identical boundaries

### ISSUE THREAD

**Issue by Tencao** [SpongePowered/SpongeForge#954]
So I tried to use the latest sponge, however, it crashes with the error -

org.spongepowered.plugin.meta.version.InvalidVersionSpecificationException: Range cannot have identical boundaries: [${version},${version}]

Full crash report - https://paste.ee/r/lzNmt
Forge version - 12.18.2.2102
Sponge version - 1.10.2-2098-5.0.0-BETA-1792

**Comment by Zidane** [comment]
@Minecrell 

That error should never EVER crash the server. Fix that as soon as you can.

**Comment by Zidane** [comment]
Also, the exception is entirely unhelpful. You don't show the offending plugin...

**Comment by Tencao** [comment]
Any news on this getting fixed? It's preventing me from using sponge at all

**Comment by Tencao** [comment]
I know this issue is being looked into, but I want to say that it wasn't a plugin that specifically caused this problem. After testing and removing all plugins, it turned out a mod was causing this problem, which is weird. the mod in question was https://mods.curse.com/mc-mods/minecraft/229598-ice-shards

**Comment by JBYoshi** [comment]
This is a Forge bug (although plugin-meta should probably be updated with the fix when it comes). [`Restriction.toString()`](https://github.com/MinecraftForge/MinecraftForge/blob/1.10.x/src/main/java/net/minecraftforge/fml/common/versioning/Restriction.java#L184) does not take into account identical lower and upper bounds, so (in this case) it returns `[${version},${version}]` when it should return `[${version}]`. `VersionRange` then refuses to parse it because the bounds are identical.

**Comment by stephan-gh** [comment]
I'm pretty sure I have fixed that in https://github.com/SpongePowered/SpongeForge/commit/cb6b2d9a89e076c75ca759cf8fa73538f8b8fffe#diff-ada9f267324c695c8a357c6769b3449eR133
